### ISSUE TITLE
Получение версий из ранее сокращенного хранилища

### ISSUE THREAD

**Issue by abirambul** [oscript-library/gitsync#1]
При попытке получения версий из хранилища, которое подверглось сокращению, получаем ошибку:
`ОШИБКА - {Модуль C:\Program Files (x86)\OneScript\lib\gitsync\src\core\Классы\Ме
неджерСинхронизации.os / Ошибка в строке: 666 / Преобразование к типу 'Дата' не
поддерживается}.`
![default](https://cloud.githubusercontent.com/assets/19974980/18811425/6e50c32e-82b7-11e6-92b5-2dd83c1d9c8f.png)
Причина первая строка в истории хранилища.

**Comment by EvilBeaver** [comment]
От такого номера строки ничего хорошего ждать не приходится :)
Спасибо за инфо, выясним.

**Comment by asosnoviy** [comment]
@abirambul а какой версией платформы сокращали? И в каком режиме совместимости хранилище? 
Сократил свое, пустой строки не появилось.

**Comment by abirambul** [comment]
@asosnoviy в данный момент использую версию платформы 8.2.19.76. Эта версия платформы и использовалась при сокращении хранилища. 
Воспроизвести данное поведение у меня не получается. Пробовал даже на 8.1.15.14.
