### ISSUE TITLE
Распаковка Module.bin

### ISSUE THREAD

**Issue by dmpas** [oscript-library/gitsync#106]
Если текст модуля отсутствует, выгружается бинарь `Module.bin`. Его можно распаковать в два условно-текстовых (скобочники) файла: `image` и `info`. Наглядности не прибавит, но уберёт лишний бинарь из гита.

Вопрос: есть ли в этом смысл?

**Comment by artbear** [comment]
если текст модуля отсутствует, то и черт с ним.
Пусть будет бинарь.
