### ISSUE TITLE
Не удается экспортировать исходники в репозитарий

### ISSUE THREAD

**Issue by ivan-kovtun** [oscript-library/gitsync#107]
Пытаюсь на Ubuntu настроить gitsync, получаю ошибку ниже:
root@ip-xxxx1:/DATA/gitsync# gitsync export /DATA/REPO_8.3.9.2233/test/ /DATA/gitsync/test/                     GitSync v2.4.0
ИНФОРМАЦИЯ - Начинаю выгрузку исходников
ИНФОРМАЦИЯ - Начало синхронизации с git
КРИТИЧНАЯОШИБКА - {Модуль /usr/share/oscript/lib/tool1cd/table-reader.os / Ошибка в строке: 41 / Внешнее исключение (System.ComponentModel.Win32Exception): Cannot find the specified file}

пробовал настраивать лог через LOGOS_CONFIG, но так и не удалось вывести его ни в консоль, ни в файл.

**Comment by khorevaa** [comment]
@ivan-kovtun Лечение по фото!

Установи wine!

**Comment by ivan-kovtun** [comment]
Какие мануалы, такие и вопросы.

**Comment by nixel2007** [comment]
oscript <> gitsync. Требования оскрипта применимы к гитсинку, но не наоборот.

Вроде хватает коробочного. 

@dmpas раз пошла такая пьянка - далеко ли до сборки ctool1cd нативно под линукс? Это последний exe в гитсинке

**Comment by khorevaa** [comment]
Пойдет любой

**Comment by khorevaa** [comment]
@ivan-kovtun  Я доделываю версию которая из коробки работает без tool1cd. А tool1cd вынес в плагин

Можно посмотреть тут https://github.com/khorevaa/gitsync/tree/use-lib-cli

**Comment by ivan-kovtun** [comment]
> Можно посмотреть тут https://github.com/khorevaa/gitsync/tree/use-lib-cli

**Comment by dmpas** [comment]
>  далеко ли до сборки ctool1cd нативно под линукс

до релиза далеко. Тестовая версия давным-давно выкладывалась, не освежали ещё.

**Comment by nixel2007** [comment]
@dmpas ну ты же знаешь мой следующий вопрос :) оно покроет требования гитсинка или надо ещё ковырять?

**Comment by dmpas** [comment]
@nixel2007 вообще, должно. Но я сам не пробовал.

**Comment by ivan-kovtun** [comment]
Установка wine, чит с LOGOS и эксперимены с правами позволили экспортировать хранилище демонстрационной базы. Но при попытке экспортировать данные из реального хранилища возникла следующая ошибка: `ИНФОРМАЦИЯ - Код возврата равен 0
ИНФОРМАЦИЯ - Раскладываем модули по папкам согласно иерархии метаданных
ИНФОРМАЦИЯ - Найдено файлов выгрузки: 7910 шт.
Can't find custom attr constructor image: /usr/share/oscript/lib/v8unpack/v8unpack.dll mtoken: 0x0a00000f due to: Could not find method with signature string,string assembly:/usr/share/oscript/bin/ScriptEngine.dll type:ContextMethodAttribute member:.ctor
ИНФОРМАЦИЯ - Откатываем файл VERSION после ошибки
ИНФОРМАЦИЯ - ПутьКФайлуВерсий =</DATA/gitsync/test2/VERSION>
КРИТИЧНАЯОШИБКА - {Модуль /usr/share/oscript/lib/gitsync/src/core/Классы/МенеджерСинхронизации.os / Ошибка в строке: 484 / Внешнее исключение (System.MissingMethodException): Method 'ScriptEngine.Machine.Contexts.ContextMethodAttribute..ctor' not found.}
`

**Comment by dmpas** [comment]
@ivan-kovtun версия односкрипта какая? такое было в старом 19-м релизе.

**Comment by ivan-kovtun** [comment]
@dmpas , root@ip-172-31-32-231:~# oscript -version
1.0.19.104
Пошел обновляться:) Спасибо!

**Comment by ivan-kovtun** [comment]
Переполняется диск за счет конфигураций в /tmp они очищаются после экспорта?

**Comment by dmpas** [comment]
> они очищаются после экспорта?

оо, тут тонкий момент :trollface:

**Comment by dmpas** [comment]
> при падении можно руками почистить

пусть меня поправят, но насколько я помню, надо **ВКЛЮЧИТЬ** режим отладки - тогда будут удаляться временные файлы.

**Comment by dmpas** [comment]
> почитал внимательно вывод - у группы нет прав на запись...

права на запись вообще не должны требоваться.

**Comment by nixel2007** [comment]
@dmpas верно говорит. В версии 2.4.0 надо передать гитсинку -debug on для того, чтобы временные файлы начали удаляться.

**Comment by nixel2007** [comment]
Интересно, сколько раз ещё мы это починим и снова сломаем. Хоть тест на это пиши.

**Comment by igostv** [comment]
Даже с `-debug on` остаются файлы: 1 файл - лог чтения USERS AUTHORS. И по 2 файла на каждую версию: лог сохранения файла конфигурации из хранилища, и файл с сообщением коммита. 
Правда они почти невесомы.

**Comment by doleynikov** [comment]
Добрый день. Вынужден присоединиться к обсуждению.
Установил на пробу gitsync. на Дебиан. Запускаю 1С клиент для LINUX. Создаю хранилище (UT 11 Demo база). При попытке синхронизировать:
gitsync export /home/dimao/1C/1c-storage/ut11 /home/dimao/1C/1c-storage/git -v8version 8.3.8.0
GitSync v2.4.3
ИНФОРМАЦИЯ - Начинаю выгрузку исходников
ИНФОРМАЦИЯ - Начало синхронизации с git
wine: Call from 0x7b84bda7 to unimplemented function ndis.sys.NdisRegisterProtocol, aborting
wine: Unimplemented function ndis.sys.NdisRegisterProtocol called at address 0x7b84bda7 (thread 0020), starting debugger...
���� ������ 1CD �����
	���� = Z:\home\dimao\1C\1c-storage\ut11\1cv8ddb.1CD
	����� ���� = 8.3.8.0
	Locale = ru_RU
	����� = ���쪮 �⥭��
	������⢮ ⠡��� = 10
�믮���� �ᯮ�� ⠡���� � 䠩�.
	������ = USERS
	���� = Z:/tmp/6v6o2tli.s8f.tmp\USERS.xml
�믮���� �ᯮ�� ⠡���� � 䠩�.
	������ = VERSIONS
	���� = Z:/tmp/6v6o2tli.s8f.tmp\VERSIONS.xml
ИНФОРМАЦИЯ - Номер синхронизированной версии: 0
ИНФОРМАЦИЯ - Номер последней версии в хранилище: 1
ИНФОРМАЦИЯ - Получаем исходники для версии 1, 28.08.2018 16:55:51
���� ������ 1CD �����
	���� = Z:\home\dimao\1C\1c-storage\ut11\1cv8ddb.1CD
	����� ���� = 8.3.8.0
	Locale = ru_RU
	����� = ���쪮 �⥭��
	������⢮ ⠡��� = 10
err:winediag:FILE_CreateFile Too many open files, ulimit -n probably needs to be increased

Abnormal program termination
ОШИБКА - 28.08.2018 16:55:51 <ok> База данных 1CD открыта
	Файл = Z:\home\dimao\1C\1c-storage\ut11\1cv8ddb.1CD
	Версия базы = 8.3.8.0
	Locale = ru_RU
	Режим = Только чтение
	Количество таблиц = 10


КРИТИЧНАЯОШИБКА - {Модуль /usr/share/oscript/lib/tool1cd/config-storage.os / Ошибка в строке: 48 / Tool_1CD вернул код возврата 3}

Подскажите, что бы это значило?
