### ISSUE TITLE
Подключение библиотеки "tool1cd"

### ISSUE THREAD

**Issue by necessitudo** [oscript-library/gitsync#115]
Добрый день! Подскажите - скачал onescript, поставил. Скачал gitsync. 

C:\Program Files (x86)\OneScript\bin>oscript.exe C:\Users\dubrovinom\Downloads\gitsync-master\gitsync-master\src\gitsync.os
{Модуль C:\Users\dubrovinom\Downloads\gitsync-master\gitsync-master\src\core\Классы\МенеджерСинхронизации.os / Ошибка в строке: 11 / Библиотека не найдена tool1cd}

А собственно куда этот tool1cd положить надо?

**Comment by nixel2007** [comment]
Это одна из зависимостей данного пакета. Их надо располагать в каталоге библиотек - по умолчанию в C:\Program files (x86)\OneScript\lib

Однако не надо ее ставить так же с гитхаба (да и гитсинк тоже не стоит, если вы не собираетесь его разрабатывать). Для установки пакетов служит отдельный пакетный менеджер. 
Ознакомьтесь с этой статьей - https://infostart.ru/public/699642/

**Comment by artbear** [comment]
закрываю как выполненную
