### ISSUE TITLE
Ошибка получения изменений.

### ISSUE THREAD

**Issue by theshadowco** [oscript-library/gitsync#12]
После обновления на свежий gitsync получил ошибку 

> ИНФОРМАЦИЯ - Получение изменений с удаленного репозитория
> ОШИБКА - {Модуль C:\osl\oscript-library\src\gitsync\src\core\Классы\КомандныйФайл.os / Ошибка в строке: 19 / Конструктор не найден (ЗаписьТекста)}

Подозреваю в ночных сборках 'oscript' уже есть новые параметры конструктора ЗаписьТекста, но в последней официальной нет, увы

**Comment by theshadowco** [comment]
коммит, который сломал https://github.com/oscript-library/gitsync/commit/cee60a8e1957ce61237ec25b23159e729eb2e318

**Comment by artbear** [comment]
Ага, у меня сегодня джоб гитсинка на билд-сервере также обломался :(

**Comment by artbear** [comment]
@pumbaEO Женя, исправляй!

**Comment by pumbaEO** [comment]
Так oscript обновите и все заработает. Ну или скачали 14 версию то используем библиотеку из поставки.

**Comment by nixel2007** [comment]
Ребят ну логично же, новая версия библиотеки требует новый движок.

**Comment by theshadowco** [comment]
@pumbaEO, все бы ничего, но 15 версия oscript токо найтбилд, а такие версии на продуктив ставить не могу по идеологическим соображениям. 

Если новая фича для тестовой ветки oscript'а, так может ее положить не в мастер репозитория, а в дев?

**Comment by nixel2007** [comment]
@theshadowco а откуда вы новую версию гитсинка поставили?)

**Comment by theshadowco** [comment]
с данного репозитория

**Comment by nixel2007** [comment]
а почему вы на продакшн ставите версию, не вошедшую в релиз оскрипта?) она точно такой же найтбилд, пока ее нет в опм

**Comment by nixel2007** [comment]
или хотя бы не обновлен сабмодуль в репо evilbeaver/oscript-library

**Comment by nixel2007** [comment]
а, вижу обновлена в evilbeaver/oscript-library, эта часть вопроса снимается

**Comment by theshadowco** [comment]
ранее, идеология была -мастер все отлично, дев - новинки. если парадигма поменялась, то ок

**Comment by theshadowco** [comment]
если пр внесении исправлений и минорных изменениях происходит обновление 14 сборки, то можно вернутся на либу из поставки оскрипта, но мои наблюдения говорят об обратном

**Comment by nixel2007** [comment]
@theshadowco тут конфликт интересов получается. парадигма та же, в мастер - стабильная версия библиотеки. но работает она на нестабильной версии движка.

в принципе если бы была возможность проверять необходимую версию движка перед установкой новой версии библиотеки (например, через опм), то это частично решило бы проблему.

в целом у нас получился прецедент, который хорошо бы зафиксировать и стараться в дальнейшем такого не допускать.

тут 2 варианта:
* либо релиз не выпускается в мастер, пока нет stable-версии оскрипта
* либо не обновляется набор библиотек в evilbeaver/oscript-library, пока физически там нет новой версии. возможно имеет смысл в evilbeaver/oscript-library сделать так же две ветки - текущий стэйбл, который пакуется вместе с оскриптом и девелоп.

**Comment by nixel2007** [comment]
@EvilBeaver @artbear @pumbaEO discuss

**Comment by theshadowco** [comment]
@nixel2007 при любом из варинтов, надо все-таки как-то понимать, какой минимальной версией движка поддерживается данный скрипт

**Comment by nixel2007** [comment]
@theshadowco можно добавить новое поле в packagedef для opm. и проверять версию при установке. это должно быть не сложно.

**Comment by theshadowco** [comment]
@nixel2007 с пальцев снял)

**Comment by EvilBeaver** [comment]
В манифесте opm есть фиксация требуемой версии движка. Но за этим мы пока не успеваем следить.

**Comment by artbear** [comment]
Да, 
1 предлагаю в opm добавить функционал проверки требуемой версии движка при установке библиотеки
2 предлагаю в мастер-ветки библиотек заливать только тот код, который работает в мастер-ветке 1скрипта.

**Comment by EvilBeaver** [comment]
@artbear функционал есть. Но никто из авторов не ставит минимально требуемую версию в манифесте.

**Comment by nixel2007** [comment]
@EvilBeaver ловите PR

**Comment by nixel2007** [comment]
https://github.com/oscript-library/opm/pull/9

**Comment by nixel2007** [comment]
Создана ветка develop. В манифест добавлена зависимость от версии оскрипта 1.0.15.

**Comment by nixel2007** [comment]
В новый opm добавлена функциональность проверки версии движка перед установкой.

Предлагаю тогда закрыть этот ишуз. Будем стараться выпускать релизы с оглядкой на релизы движка.

**Comment by pumbaEO** [comment]
Ну еще дополнительно надо в https://github.com/EvilBeaver/oscript-library создать ветку develop и там переподвязать подмодули на develop ветки.

**Comment by artbear** [comment]
Проблема исправлена в рамках решения #15

Проблема все-таки была в движке :( [обсуждение в giiter](https://gitter.im/EvilBeaver/oscript-library?at=584a91a29ce5147013cd0817)
А все рассуждения выше об opm были ни при чем :(

Хотя по opm в итоге делаем полезную вещь!
