### ISSUE TITLE
Хранилище расширения конфигурации и gitsync

### ISSUE THREAD

**Issue by VoronyukM** [oscript-library/gitsync#122]
Добрый день!

Не получается выполнить синхронизацию хранилища расширения конфигурации с git. Пробовал на версии oscript 1.0.20. Привожу лог:

```
oscript "C:\\bin\\OneScript\\lib\\gitsync\\src\\gitsync.os" export q:/cf-rep/my-extesion ./src/cf -v8version 8.3.12 -format hierarchical 
GitSync v2.4.2
ИНФОРМАЦИЯ - Начинаю выгрузку исходников
ИНФОРМАЦИЯ - Начало синхронизации с git
ИНФОРМАЦИЯ - Номер синхронизированной версии: 0
ИНФОРМАЦИЯ - Номер последней версии в хранилище: 3
ИНФОРМАЦИЯ - Получаем исходники для версии 1, 23.05.2018 12:04:10
КРИТИЧНАЯОШИБКА - {Модуль C:\bin\OneScript\lib\tool1cd\config-storage.os / Ошибка в строке: 34 / Tool_1CD не выгрузил файл конфигурации.}
```

**Comment by khorevaa** [comment]
Этого gitsync не умеет

**Comment by VoronyukM** [comment]
@khorevaa А план на реализацию этого есть?

**Comment by khorevaa** [comment]
У меня нет. Может кто из сообщества сделает

**Comment by VoronyukM** [comment]
Если Tool_1CD не умеет выгрузить cfe из хранилища расширения конфигурации, то копаться в его исходниках точно нет возможности, и, насколько понимаю логику gitsync, нужно будет переписывать получение файла расширения конфигурации из хранилища расширения конфигурации при помощи нативного метода конфигуратора
`/ConfigurationRepositoryDumpCfg [-Extension <имя расширения>] <имя cf файла> [-v <номер версии хранилища>] `

Как минимум, у нас потребность делать gitsync с хранилищем расширения конфигурации появилась, а вот удастся ли это самим сделать и насколько быстро - ответить пока не сложно.

**Comment by khorevaa** [comment]
@VoronyukM Счас gitsync3 выйдет в beta. Там это сделать быстро

**Comment by khorevaa** [comment]
@VoronyukM вот v8storage уже почти умеет работать с хранилищем расширения https://github.com/khorevaa/v8storage/issues/4

**Comment by khorevaa** [comment]
Реализовано в версии 3.0.0
