### ISSUE TITLE
Оптимизировать чтение таблицы истории хранилища

### ISSUE THREAD

**Issue by khorevaa** [oscript-library/gitsync#126]
Сейчас при каждом запуске таблица истории хранилища читается полностью. Необходимо сделать чтобы чтение происходило только с последней синхронизированной версии

**Comment by khorevaa** [comment]
Сделано

**Comment by nixel2007** [comment]
@khorevaa в где? надо пересобрать гитсинк? или обновить какие-то зависимости?

/cc @igostv

**Comment by igostv** [comment]
@nixel2007 нашёл https://github.com/oscript-library/gitsync/commit/f11a042f0eb4c970a93def35329b4df9a6577065

**Comment by khorevaa** [comment]
Внутри ветки releases/3.0.0
