### ISSUE TITLE
Вопросы по развертыванию gitsync3

### ISSUE THREAD

**Issue by artbear** [oscript-library/gitsync#135]
В продолжение https://github.com/oscript-library/gitsync/pull/123#issuecomment-392560508

@khorevaa По хранению плагинов - тут важен вопрос развертывания gitsync.

+ Каким образом разворачивать гитсинк при наличии интернета?
  + учесть наличие прокси, при необходимости
+ Каким образом разворачивать гитсинк при отсутствии интернета?
+ Не забыть про Enterprise

**Comment by nixel2007** [comment]
и что предполагается делать для решения этого ишуза?

**Comment by artbear** [comment]
@nixel2007 @khorevaa Извините, я не ту цитату вставил :(
Исправил шапку.

**Comment by artbear** [comment]
Нужно получить ответы=реализацию этих вопросов.

**Comment by khorevaa** [comment]
@artbear 
По развертыванию `gitsync` в частности установки плагинов. Я сделал PR https://github.com/oscript-library/opm/pull/111 в `opm` когда любую библиотеку (а пакет плагина - это либа) можно упаковать с зависимостями в каталог `oscript_modules` и при установке `opm`  будет сначала устанавливать зависимости из `oscript_modules` установленного пакета, а топом тянуть с хаба. 
Данный подход позволяет развернуть `gitsync` без использования интернета со всеми необходимыми зависимостями

**Comment by khorevaa** [comment]
Посмотреть как это происходит можно собрав пакет через команду
`opm build -mf ./build_packagedef ./`
После выполнив
`gitsync p init` 
Установки через интернет не будет

**Comment by khorevaa** [comment]
@artbear @nixel2007  Все готово к бета-релизу.

**Comment by nixel2007** [comment]
@khorevaa бета релиз - это который полноценный, но просто "ололо, баги, сейчас пофиксим?")

**Comment by khorevaa** [comment]
@nixel2007 Да, это такой релиз.

**Comment by khorevaa** [comment]
Итого:
Плагины должны идти со всеми зависимостями в `oscript_modules`
Приложение `gitsync` поставляется со всеми зависимостями  в `oscript_modules`
