### ISSUE TITLE
Не подтягивается файл AUTHORS

### ISSUE THREAD

**Issue by DTX-92** [oscript-library/gitsync#142]
![image](https://user-images.githubusercontent.com/20479161/42451084-db52d35c-838e-11e8-8d26-976ed384891d.png)

**Comment by khorevaa** [comment]
Версия gitsync?

**Comment by DTX-92** [comment]
@khorevaa, 2.4.2 (opm install gitsync)

**Comment by nixel2007** [comment]
покажите строку запуска gitsync

**Comment by DTX-92** [comment]
@nixel2007, gitsync export "C:\Users\epanteleyev\Documents\InfoBase2 - копия\Хранилище" src\config

**Comment by nixel2007** [comment]
@DTX-92 лог работы гитсинка в режиме отладки можете показать?

**Comment by DTX-92** [comment]
@nixel2007 как это сделать?
![image](https://user-images.githubusercontent.com/20479161/42460756-5f8162c0-83a7-11e8-88ac-0028d2fd236d.png)

**Comment by nixel2007** [comment]
Установить переменную среды LOGOS_CONFIG=logger.rootLogger=DEBUG и выполнить гитсинк экспорт

**Comment by DTX-92** [comment]
Проблема была в кодировке. Спасибо!
![image](https://user-images.githubusercontent.com/20479161/42463473-e42ec100-83ae-11e8-88a8-cfd4c661242f.png)
