### ISSUE TITLE
Номер версии пустой по умолчанию в файле VERSION

### ISSUE THREAD

**Issue by fishca** [oscript-library/gitsync#147]
https://github.com/oscript-library/gitsync/blob/fae69e4f9a144f8b786a22ceed3f8ae9ed35a45f/src/core/%D0%9A%D0%BB%D0%B0%D1%81%D1%81%D1%8B/%D0%9C%D0%B5%D0%BD%D0%B5%D0%B4%D0%B6%D0%B5%D1%80%D0%A1%D0%B8%D0%BD%D1%85%D1%80%D0%BE%D0%BD%D0%B8%D0%B7%D0%B0%D1%86%D0%B8%D0%B8.os#L1290

В процедуре ЗаписатьФайлВерсийГит(Знач КаталогФайлаВерсий, Знач Версия = "") значение по умолчанию для параметра "Версия" указано пустая строка. В результате при выполнении команды 

**Клонирование существующего пустого репо**
Часто бывает, что удаленный репо уже создан и нужно наполнить его служебными файлами синхронизатора.

Запустить gitsync с параметрами 
**gitsync clone <каталог или файл хранилища> <url-git> [локальный каталог git] [-email домен почты пользователей]**

файл version принимает вид:
```
<?xml version="1.0" encoding="UTF-8"?>
<VERSION></VERSION> 
```
при попытке экспорта gitsync ругается на незаполненность файла версий, 

а должен 
```
<?xml version="1.0" encoding="UTF-8"?>
<VERSION>0</VERSION>
```

**Comment by nixel2007** [comment]
Насколько я помню, это сделано осознанно. чтобы руками и думая устанавливали нужную версию.

**Comment by fishca** [comment]
Тогда это должно быть где-либо описано. А так это не очевидное поведение. И при попытке экспорта в гит гитсинк должен рассматривать незаполненное значение как "0" - т.е. брать все версии из хранилища.

**Comment by EvilBeaver** [comment]
Я тоже помню, что это не баг, а фича. Хотя, мне кажется, от этой фичи можно и отказаться...

Пусть решает коллективный разум. Призову изначальников v8unpack, от которого родился гитсинк:

@pumbaEO @artbear

**Comment by khorevaa** [comment]
Сделано #148
