### ISSUE TITLE
Ошибка при выгрузке исходников из хранилища

### ISSUE THREAD

**Issue by realMaxA** [oscript-library/gitsync#15]
В gitsync.os при вызове метода "СинхронизироватьХранилищеКонфигурацийСГит" класса "МенеджерСинхронизации" (https://github.com/oscript-library/gitsync/blob/master/src/gitsync.os#L361) передаётся 8 аргументов, в то время как сам метож принимает только 7 аргументов (https://github.com/oscript-library/gitsync/blob/master/src/core/%D0%9A%D0%BB%D0%B0%D1%81%D1%81%D1%8B/%D0%9C%D0%B5%D0%BD%D0%B5%D0%B4%D0%B6%D0%B5%D1%80%D0%A1%D0%B8%D0%BD%D1%85%D1%80%D0%BE%D0%BD%D0%B8%D0%B7%D0%B0%D1%86%D0%B8%D0%B8.os#L892)

**Comment by artbear** [comment]
Исправлено
