### ISSUE TITLE
Не могу синхронизировать хранилище в репозиторий.

### ISSUE THREAD

**Issue by doleynikov** [oscript-library/gitsync#150]
Добрый день. Вынужден присоединиться к обсуждению.
Установил на пробу gitsync. на Дебиан. Запускаю 1С клиент для LINUX. Создаю хранилище (UT 11 Demo база). При попытке синхронизировать:
gitsync export /home/dimao/1C/1c-storage/ut11 /home/dimao/1C/1c-storage/git -v8version 8.3.8.0
GitSync v2.4.3
ИНФОРМАЦИЯ - Начинаю выгрузку исходников
ИНФОРМАЦИЯ - Начало синхронизации с git
wine: Call from 0x7b84bda7 to unimplemented function ndis.sys.NdisRegisterProtocol, aborting
wine: Unimplemented function ndis.sys.NdisRegisterProtocol called at address 0x7b84bda7 (thread 0020), starting debugger...
���� ������ 1CD �����
���� = Z:\home\dimao\1C\1c-storage\ut11\1cv8ddb.1CD
����� ���� = 8.3.8.0
Locale = ru_RU
����� = ���쪮 �⥭��
������⢮ ⠡��� = 10
�믮���� �ᯮ�� ⠡���� � 䠩�.
������ = USERS
���� = Z:/tmp/6v6o2tli.s8f.tmp\USERS.xml
�믮���� �ᯮ�� ⠡���� � 䠩�.
������ = VERSIONS
���� = Z:/tmp/6v6o2tli.s8f.tmp\VERSIONS.xml
ИНФОРМАЦИЯ - Номер синхронизированной версии: 0
ИНФОРМАЦИЯ - Номер последней версии в хранилище: 1
ИНФОРМАЦИЯ - Получаем исходники для версии 1, 28.08.2018 16:55:51
���� ������ 1CD �����
���� = Z:\home\dimao\1C\1c-storage\ut11\1cv8ddb.1CD
����� ���� = 8.3.8.0
Locale = ru_RU
����� = ���쪮 �⥭��
������⢮ ⠡��� = 10
err:winediag:FILE_CreateFile Too many open files, ulimit -n probably needs to be increased

Abnormal program termination
ОШИБКА - 28.08.2018 16:55:51 База данных 1CD открыта
Файл = Z:\home\dimao\1C\1c-storage\ut11\1cv8ddb.1CD
Версия базы = 8.3.8.0
Locale = ru_RU
Режим = Только чтение
Количество таблиц = 10

КРИТИЧНАЯОШИБКА - {Модуль /usr/share/oscript/lib/tool1cd/config-storage.os / Ошибка в строке: 48 / Tool_1CD вернул код возврата 3}

Подскажите, что бы это значило?

**Comment by khorevaa** [comment]
@doleynikov пробелма  с wine! Попробуй версию 3.0 https://github.com/oscript-library/gitsync/releases/tag/3.0.0-beta1

**Comment by doleynikov** [comment]
Установил
cat sync1.sh 
--------------------------------------------------------------
export GITSYNC_WORKDIR=./git/
export GITSYNC_STORAGE_PATH=./ut11/

export GITSYNC_STORAGE_USER=Администратор
export GITSYNC_STORAGE_PASSWORD=
export GITSYNC_V8VERSION=8.3.7
export GITSYNC_VERSOBE=true #Можно использовать Да/Ложь/Нет/Истина
export GITSYNC_TEMP=./temp/sync
gitsync s
--------------------------------------------------------------



./sync1.sh
--------------------------------------------------------------
ОТЛАДКА - Устанавливаю общие параметры
ИНФОРМАЦИЯ - Начало выполнение команды <sync>
ОТЛАДКА - ПутьКХранилищу = ./ut11/
ОТЛАДКА - КаталогРабочейКопии = /home/dimao/1C/1c-storage/git/
ОТЛАДКА - Установлена авторизация в хранилище пользователь <Администратор>, пароль <>
ИНФОРМАЦИЯ - Начата синхронизация с git
КРИТИЧНАЯОШИБКА - {Модуль /usr/share/oscript/lib/gitsync/oscript_modules/v8runner/src/v8runner.os / Ошибка в строке: 1307 / Ошибка определения версии платформы. Файл </opt/1C/v8.3/x86_64/1cv8> не существует}
--------------------------------------------------------------

**Comment by khorevaa** [comment]
@doleynikov А платформа то установлена?

Дай лог команд...
`ls /opt/1C/v8.3/x86_64/`
`ls /opt/1C/v8.3/`

**Comment by doleynikov** [comment]
Установлено 2 версии платформы (ну так исторически сложилось) 

```
#ls -al /opt/1C/v8.3/x86_64/
итого 352
drwxr-xr-x 5 root    root    204800 авг 29 11:04 .
drwxr-xr-x 3 root    root      4096 янв 30  2018 ..
drwxr-xr-x 9 root    root     69632 апр  3 17:04 8.3.10.2561
drwxr-xr-x 7 root    root     69632 апр  3 17:04 8.3.10.2753
drwxr-xr-x 2 usr1cv8 grp1cv8   4096 апр  3 16:59 conf

```
Как заставить выбирать нужную?

**Comment by khorevaa** [comment]
@doleynikov  Либа v8runner так не умеет...  Надо модифицировать код gitsync... или  поиск в v8runner.

Простой вариант пробросить параметр  - путь к платформе в приложении, установить его перед выполнение синхрониазции.

**Comment by khorevaa** [comment]
@doleynikov Вообще в папке должна быть одна платформа.. )

**Comment by doleynikov** [comment]
Извините за дилетантский вопрос: Что значит "пробросить параметр - путь к платформе в приложении, установить его перед выполнение синхрониазции." - значит самому в коде gitsync сделать этот параметр? мне нужна только одна платформа из двух установленных, чтобы поиграться с git. Но установка штатной переменной export GITSYNC_V8VERSION=8.3.7 ничего не дает. КАк система ищет установленную платформу?

**Comment by nixel2007** [comment]
Для линукса ожидается наличие единственной версии в каталоге opt, т.к. так работает установка 1с из пакетов (в один и тот же каталог).
Под ваши нужды нужно допиливать сам гитсинк. Например, где-нибудь вот тут https://github.com/oscript-library/gitsync/blob/develop/src/core/%D0%9A%D0%BB%D0%B0%D1%81%D1%81%D1%8B/%D0%9C%D0%B5%D0%BD%D0%B5%D0%B4%D0%B6%D0%B5%D1%80%D0%A1%D0%B8%D0%BD%D1%85%D1%80%D0%BE%D0%BD%D0%B8%D0%B7%D0%B0%D1%86%D0%B8%D0%B8.os#L1091 в классе УправлениеКонфигуратором установить точный путь к нужной платформе.

**Comment by EvilBeaver** [comment]
Надо ввести переменную среды для линукса, т.к. в нем количество мест, где может быть желаемая платформа универсально определить невозможно.

**Comment by khorevaa** [comment]
Допилю проброс указания адреса платформы

**Comment by doleynikov** [comment]
Я снес onescript (удалил каталог) и переустановил его и gitsync. переустановил WINE и MONO 5.2
Создаю репозиторий заново.


/home/dimao/1C/1c-storage/git/$ git init  
Инициализирован пустой репозиторий Git в /home/dimao/1C/1c-storage/git/.git/
/home/dimao/1C/1c-storage/git/$ gitsync init /home/dimao/1C/1c-storage/ut11 /home/dimao/1C/1c-storage/git
GitSync v2.4.3
ИНФОРМАЦИЯ - На ветке master

Начальный коммит

нечего коммитить (создайте/скопируйте файлы, затем запустите «git add», чтобы отслеживать их)

wine: Call from 0x7b84bda7 to unimplemented function ndis.sys.NdisRegisterProtocol, aborting
wine: Unimplemented function ndis.sys.NdisRegisterProtocol called at address 0x7b84bda7 (thread 001f), starting debugger...
���� ������ 1CD �����
	���� = Z:\home\dimao\1C\1c-storage\ut11\1cv8ddb.1CD
	����� ���� = 8.3.8.0
	Locale = ru_RU
	����� = ���쪮 �⥭��
	������⢮ ⠡��� = 10
�믮���� �ᯮ�� ⠡���� � 䠩�.
	������ = USERS
	���� = Z:/tmp/nsxzncav.r2c.tmp\USERS.xml
/home/dimao/1C/1c-storage/git/$ gitsync sync /home/dimao/1C/1c-storage/ut11 /home/dimao/1C/1c-storage/git/
GitSync v2.4.3
ИНФОРМАЦИЯ - Начинаю синхронизацию хранилища 1С и репозитария GIT
ИНФОРМАЦИЯ - Получение изменений с удаленного узла (pull)
ОШИБКА - Получен ненулевой код возврата 255. Выполнение скрипта остановлено!
КРИТИЧНАЯОШИБКА - {Модуль /usr/share/oscript/lib/gitrunner/src/ГитРепозиторий.os / Ошибка в строке: 840 / error: could not lock config file .git/config: Нет такого файла или каталога}

 Где ожидается этот .git/config ?

**Comment by doleynikov** [comment]
Где ожидается этот .git/config ?

Извиняюсь. Ошибочно закрыл

**Comment by khorevaa** [comment]
@doleynikov Наверное где-то здесь  `/home/dimao/1C/1c-storage/git`

**Comment by khorevaa** [comment]
@doleynikov Сделал доработку для возможности указания исполяемого файла 1С. #151

**Comment by khorevaa** [comment]
@doleynikov https://github.com/oscript-library/gitsync/releases/tag/3.0.0-beta2

**Comment by doleynikov** [comment]
Извиняюсь за задержку.
Вот:
~/1C/1c-storage$ java -version
openjdk version "9-Debian"
OpenJDK Runtime Environment (build 9-Debian+0-9b181-4bpo91)
OpenJDK 64-Bit Server VM (build 9-Debian+0-9b181-4bpo91, mixed mode)

~/1C/1c-storage$ gitsync sync --storage-user Администратор ./ut11/ ./git/
ИНФОРМАЦИЯ - Начало выполнение команды <sync>
ИНФОРМАЦИЯ - Начата синхронизация с git
ОШИБКА - openjdk version "1.8.0_181"
OpenJDK Runtime Environment (build 1.8.0_181-8u181-b13-1~deb9u1-b13)
OpenJDK 64-Bit Server VM (build 25.181-b13, mixed mode)
КРИТИЧНАЯОШИБКА - {Модуль /usr/share/oscript/lib/gitsync/src/core/Классы/МенеджерСинхронизации.os / Ошибка в строке: 1250 / Чтение файла версий, у элемента Version нет текста}

Нужно установить JAVA_HOME ?

**Comment by nixel2007** [comment]
Нет, в файле VERSION нужно поставить требуемую версию, с которой начинается синхронизация. Если нужна полная синхронизация, то выставить туда ноль.

**Comment by doleynikov** [comment]
Вроде что-то синхронизировало, сейчас буду смотреть. НО все равно пишет:
ОШИБКА - openjdk version "1.8.0_181"
OpenJDK Runtime Environment (build 1.8.0_181-8u181-b13-1~deb9u1-b13)
OpenJDK 64-Bit Server VM (build 25.181-b13, mixed mode)

**Comment by nixel2007** [comment]
@khorevaa откуда там вызов джавы?

**Comment by doleynikov** [comment]
а вот не знаю откуда он лезет. Вроде в требованиях небыло упоминаний

**Comment by doleynikov** [comment]
gitsync sync --storage-user Администратор ./ut11/ ./git/ut11/
ИНФОРМАЦИЯ - Начало выполнение команды <sync>
ИНФОРМАЦИЯ - Начата синхронизация с git
ОШИБКА - openjdk version "1.8.0_181"
OpenJDK Runtime Environment (build 1.8.0_181-8u181-b13-1~deb9u1-b13)
OpenJDK 64-Bit Server VM (build 25.181-b13, mixed mode)
ИНФОРМАЦИЯ - Номер синхронизированной версии: 0
ИНФОРМАЦИЯ - Номер последней версии в хранилище: 1
ИНФОРМАЦИЯ - Получаем исходники для версии 1, 07.09.2018 11:00:17
ОШИБКА - openjdk version "1.8.0_181"
OpenJDK Runtime Environment (build 1.8.0_181-8u181-b13-1~deb9u1-b13)
OpenJDK 64-Bit Server VM (build 25.181-b13, mixed mode)
ОШИБКА - openjdk version "1.8.0_181"
OpenJDK Runtime Environment (build 1.8.0_181-8u181-b13-1~deb9u1-b13)
OpenJDK 64-Bit Server VM (build 25.181-b13, mixed mode)
ИНФОРМАЦИЯ - Завершена синхронизации с git
ИНФОРМАЦИЯ - Завершено выполнение команды <sync>

**Comment by khorevaa** [comment]
Видимо утилита ring

**Comment by nixel2007** [comment]
@khorevaa что-то новое. а зачем она там используется? если по делу, то надо тогда задокументировать

**Comment by khorevaa** [comment]
Надо понять когда это стало. Т.к. на 11 версии такого нет

**Comment by EvilBeaver** [comment]
О, божечки... гитсинк уже сам себя пишет, джаву ему подавай, и никто из мейнтейнеров не в курсе %)

**Comment by khorevaa** [comment]
Дополнено
