### ISSUE TITLE
Масса якобы изменяющихся объектов Template.xml gitsync-3.0.0-beta2

### ISSUE THREAD

**Issue by Bezeus** [oscript-library/gitsync#157]
Дано:
1.  Конфигурация на обычных формах.
2. Платформа 8.3.10.2561
3. gitsync-3.0.0-beta2

Делаю: gitsync --v8-path "C:\Program Files (x86)\1cv8\8.3.10.2561\bin\1cv8.exe" s --storage-user GitterAdmin --storage-pwd Секрет tcp://%АдресХранилищаКонфигурации1С% %ЛокальныйКаталогРепо%

В результате помимо действительно изменившихся файлов, в большом количестве присутствуют якобы изменившиеся файлы Template.xml

gitsync из ветки master таких проблем не порождает. Из-за этого, к моему огорчению, пришлось откатиться на 2.4.3

**Comment by khorevaa** [comment]
@Bezeus вложи  скриншоты файлов.. на второй версии повторяется?

**Comment by Bezeus** [comment]
На второй версии всё шикарно и великолепно. Сегодня/завтра разверну снова бетку третьей версии и сделаю скрины, чтобы было нагляднее.

**Comment by khorevaa** [comment]
@Bezeus Странно просто! Принципиально что 2, что 3 версия для выгрузки то используют один механизм (он же единственный 1С-ный) выгрузки. Проверьте версию платформы при выгрузке обоими версиями. Данный файл - может в старых версиях платформы всегда выгружаться как измененный или если это xml и при выгрузки поменялась версия платформы 1С выгружает изменения в xml файлы.

**Comment by khorevaa** [comment]
@Bezeus Дадите скрины?

**Comment by Bezeus** [comment]
> @Bezeus Дадите скрины?

Уезжал. Сейчас систему поставил с нуля. Заливаю всё заново. Ставлю бету 3 и проверю повторимость проблемы. Если будут проблемы - прикреплю скрины. Если всё ок, то спишем это на мои кривые руки.

**Comment by Bezeus** [comment]
Резюмирую. Руки у меня кривые. Всё отлично работает. Закройте, плиз, этот мой позор
