### ISSUE TITLE
При синхронизации открывает 1с в пользовательком режиме и выдает запрос

### ISSUE THREAD

**Issue by ivtroitskiy** [oscript-library/gitsync#158]
![default](https://user-images.githubusercontent.com/13430286/47288721-bb009b00-d610-11e8-8f1c-6619dda9d31f.png)

Как это убрать?
Платформа 8.3.10.2561
gitsync 3.0.0-beta2

**Comment by khorevaa** [comment]
Это настройка 1с. Надо разрешить запускать обработки

**Comment by nixel2007** [comment]
может вынести конвертацию json в отдельный необязательный плагин? и так куча окон прыгает, хотелось бы минимизировать это добро...

**Comment by khorevaa** [comment]
Это чтение хранилища... Не получится v8storage так работает...

**Comment by nixel2007** [comment]
Не, ну в v8storage тоже можно передать флаг. Обработка конвертации - явно твоя, а не платформенная :)

**Comment by khorevaa** [comment]
Ну mxl  я читать из оскрипта  не умею... А без этого хоть совой об пень, что пнем об сову.... все равно сове п..д..ц

**Comment by nixel2007** [comment]
Погоди, я несколько про другое. Конвертация мхл в джсон штука безусловно полезная (там хотя бы текст внутри). Но с точки зрения обычного экспорта исходников в гит - это дополнительная функциональность. Как переименовывание обычных форм в bsl

**Comment by nixel2007** [comment]
То есть это обязанность не в8сторадж, а скорее самого гитсинка

**Comment by ivtroitskiy** [comment]
Подскажите, пожалуйста, где установить эту настройку? Если я правильно понимаю, то обработка запускается во автоматически созданной пустой базе. Как я там могу настройку установить?

**Comment by khorevaa** [comment]
За данную функцию отвечает параметр DisableUnsafeActionProtection в файле conf.cfg, который позволяет отключить механизм защиты от опасных действий для всех пользователей определенных информационных баз, строки соединения которых удовлетворяют маскам указанным в параметре DisableUnsafeActionProtection.
В данном параметр можно указать несколько масок разделяемых символом «;», например:
DisableUnsafeActionProtection=test_.*;stage_.*; --- это пример сюда надо вставить свою строчку или *.*

**Comment by khorevaa** [comment]
@nixel2007 Вся проблема в том, v8storage  - использует эту обработку для получения таблиц авторов и истории версий, после получения отчета по хранилищу платформенными средствами. Вот собственно и где лежит проблема! В принципе эта история нужна только для гитсинка - ее можно перенести в гитсинк. Вообще была мысль сделать просто в гитсинке команду `check` для проверки готовности системы к работе

**Comment by nixel2007** [comment]
@khorevaa ааа... Теперь понял, спасибо.

**Comment by ivtroitskiy** [comment]
@khorevaa Спасибо! Помогло!

**Comment by khorevaa** [comment]
Закрываю, если помогло!
