### ISSUE TITLE
Добавить тесты (юнит или bdd) на базовую синхронизацию

### ISSUE THREAD

**Issue by artbear** [oscript-library/gitsync#16]
Сейчас нет тестов на базовую синхронизацию
+ 'gitsync ПутьКХранилищу URLРепозитория ЛокальныйКаталогГит ...`
+ или Метод `Синхронизировать` ([`метод в gitsync.os`](https://github.com/oscript-library/gitsync/blob/master/src/gitsync.os#L161))

Из-за этого мы пропустили баг #15

**Comment by nixel2007** [comment]
Только надо не забыть, что пушить можно не только на гитхаб, но и в репо, созданный в соседней папке.

Я на это нарвался в тестах для гитраннера - никто кроме меня не может пушить в мой репозиторий, что логично. Т.е. тесты могут пройти только под моей учеткой. пришлось переписать.
https://github.com/nixel2007/gitrunner/pull/5/commits/4f496ec131fe89d83ff3db793badf74d18ea328e

**Comment by EvilBeaver** [comment]
@nixel2007 все еще актуально? Или тесты появились какие-то?

**Comment by nixel2007** [comment]
@EvilBeaver дык в коммите как раз переписанные тесты. А про тесты гитсинка не знаю, читать надо :)

**Comment by artbear** [comment]
>все еще актуально? Или тесты появились какие-то?

@EvilBeaver @nixel2007 вы что вообще?

**Comment by artbear** [comment]
>все еще актуально? Или тесты появились какие-то?

@EvilBeaver @nixel2007 Из-за опечатки фраза выше звучит неверно :)
Правильно читать так "вы про что вообще?" :)

**Comment by khorevaa** [comment]
@artbear  Предлагаю закрыть реализовано в 3.0
