### ISSUE TITLE
Некорректно работает инкрементная выгрузка

### ISSUE THREAD

**Issue by pavlyk** [oscript-library/gitsync#163]
При выполнении команды
gitsync export %DEPOTPATH% .\src\cf -check-authors -stop-if-empty-comment -increment -useVendorUnload --storage-user Администратор --storage-pwd 123
Обновляется только файл AUTHORS версия меняется на последнюю версию хранилища но сами файлы конфигурации не появляются
Если убрать increment то всё работает

**Comment by nixel2007** [comment]
Какая точная версия гитсинка?

**Comment by nixel2007** [comment]
Да и authors не должен обновляться. Может version?

**Comment by pavlyk** [comment]
GitSync v2.4.3
Да извиняюсь не authors , а version

**Comment by pavlyk** [comment]
Посмотрите, возможно проблема вот в чём
МенеджерСинхронизации.os
Процедура РазобратьФайлКонфигурацииШтатнымиСредствами

Переопределяется каталог выгрузки
КаталогВыгрузки = ?(ТолькоИзменения, ВыходнойКаталог, КаталогПлоскойВыгрузки);

Но дальше в вызове процедуры искользуется всё равно КаталогПлоскойВыгрузки
ВыгрузитьМодулиКонфигурацииОбновлениеИзХранилища(ПутьКХранилищу, НомерВерсии, ПараметрыДоступаКХранилищу, КаталогПлоскойВыгрузки, Формат);

Но если изменить, начинает падать ошибка
В каталоге <"+КаталогПлоскойВыгрузки+"> не должно быть файлов

И ещё один момент , вот тут
https://wonderland.v8.1c.ru/blog/inkrementalnaya-vygruzka-konfiguratsii-v-xml/
написано что нужно ещё добавить ключ "update" к "DumpConfigToFiles"
"update это новый ключ, который позволяет обновить выгрузку, то есть выгрузить только те файлы, версии которых отличается от версий в каталоге выгрузки."

**Comment by nixel2007** [comment]
Попробуйте gitsync 3.0. Насколько я помню, там решена эта проблема
