### ISSUE TITLE
поддержка хранилищ расширений

### ISSUE THREAD

**Issue by allustin** [oscript-library/gitsync#169]
Я конечно считаю что нужно использовать Vanessa Runner и нативную выгрузку   - но может добавим такую функциональность: через плагины например

@khorevaa  - что скажешь ?

**Comment by khorevaa** [comment]
@allustin  Я за.. мне надо т.к. Vanessa Runner не использую... Там сначала надо v8storage допилить. 
Да и в 3.0 в стабильную выпустить

**Comment by artbear** [comment]
>Да и 3.0 в стабильную выпустить

Мы и планируем выпустить релиз 3.0 как стабильный в рамках доработок.

>Там сначала надо v8storage допилить.
@khorevaa А что нужно допилить? чего не хватает?

**Comment by artbear** [comment]
Мое видение результата
- добавить поддержку хранилищ расширений
  - с тестами/фичами
- выпустить релиз 3.0 гитсинка
- задокументировать набор плагинов, которые проверены на наших серверах и у наших клиентах с учетом опыта @khorevaa 
  - возможно, нужно здесь сделать некую сборку с правильными зависимостями и т.п.
- сделать необходимые доработки в других пакетах

**Comment by khorevaa** [comment]
В общем прототип находится в PR #172: 
* надо создавать в темповой базе расширение - доступно только загрузкой из cfe
* v8runner - не умеет загружать cfe - надо допилить. Сейчас сделано временно для проверки
* сейчас создано временное расширение `temp.cfe` - и прописан жесткий путь. Надо исправить
* надо прокинуть в апи плагинов (подписки) имя расширения там где это необходимо
* сделать метод получения `ИмяРасширения` для `МенеджераСинхронизации` - для вызова из плагинов 
@ZhdanovR @allustin

**Comment by ZhdanovR** [comment]
* Надо создавать в темповой базе расширение - доступно только загрузкой из cfe. Сейчас создано временное расширение `temp.cfe` - и прописан жесткий путь. Надо исправить - я исправил

**Comment by khorevaa** [comment]
Все задачи сделаны!
