### ISSUE TITLE
Выпуск gitsync 3.0

### ISSUE THREAD

**Issue by ZhdanovR** [oscript-library/gitsync#170]
Версия Gitsync 3.0 уже опробована многими. Пора выпускать в продуктив.
@khorevaa Предлагаю в этом ишузе собрать чеклист минимальных доработок.
Общими усилиями выпустим.

**Comment by ZhdanovR** [comment]
@nixel2007 Вроде бы посмотрел ишузы, но не нашел ничего похожего

**Comment by nixel2007** [comment]
Перепутал. Есть чек лист, по сборке в exe.

**Comment by artbear** [comment]
закрываю, т.к. дубль https://github.com/oscript-library/gitsync/issues/164
