### ISSUE TITLE
Формат опций v3 --storage-user Admin --storage-pwd=Secret

### ISSUE THREAD

**Issue by malikov-pro** [oscript-library/gitsync#177]
Один через пробел или без оного, второй через "=", думаю имеет смысл привести к одному формату, так же указать допустимость использования кавычек.

**Comment by khorevaa** [comment]
Программно поддерживается 2 варианта - это реализовано в библиотеке `cli`. [Синтаксис опций](https://github.com/khorevaa/cli#%D0%BF%D1%80%D0%B8%D0%BC%D0%B5%D1%80-%D1%81%D0%B8%D0%BD%D1%82%D0%B0%D0%BA%D1%81%D0%B8%D1%81%D0%B0-%D0%BE%D0%BF%D1%86%D0%B8%D0%B9)
