### ISSUE TITLE
Использование лицензий 1С при запуске

### ISSUE THREAD

**Issue by malikov-pro** [oscript-library/gitsync#178]
КРИТИЧНАЯОШИБКА - {Модуль C:\git\OneScript\lib\gitsync\oscript_modules\v8runner\src\v8runner.os / Ошибка в строке: 1291 / Не найдена лицензия. Не обнаружен ключ защиты программы или полученная программная лицензия!
}

Контекст:
1. Запускаю на ПК разработчика на ней лицензий нет.
2. Подключаюсь к тестовому серверу по tcp://, на тестовом сервере лицензии есть

**Comment by khorevaa** [comment]
@malikov-pro при синхронизации используется локальная временная база.  Соответственно - если у вас нет лицензии на ПК или доступной сетевой то будет так ругаться

**Comment by malikov-pro** [comment]
А возможно ли использовать серверную базу в качестве временной?

**Comment by khorevaa** [comment]
Сейчас нет. Но немного допилив можно

**Comment by malikov-pro** [comment]
Понятно, будем запускать на самом тестовом сервере.

**Comment by malikov-pro** [comment]
Требование было обозначено в #46
