### ISSUE TITLE
Соединение основной конфигурации с хранилищем расширений конфигураций невозможно

### ISSUE THREAD

**Issue by malikov-pro** [oscript-library/gitsync#179]
Пытаюсь запустить gitsync init подключаюсь по TCP к хранилищу расширения.

ОШИБКА - Получен ненулевой код возврата 1. Выполнение скрипта остановлено!
ОШИБКА - Не удалось сформировать файл авторов
КРИТИЧНАЯОШИБКА - {Модуль C:\git\OneScript\lib\gitsync\oscript_modules\v8runner\src\v8runner.os / Ошибка в строке: 1291 / Соединение основной конфигурации с хранилищем расширений конфигураций невозможно
}

**Comment by nixel2007** [comment]
Какая версия gitsync?
Поддержка хранилища расширения появилась только в 3.0.0-rc1

**Comment by malikov-pro** [comment]
Тестирую как раз 3.0.0-rc1.

**Comment by nixel2007** [comment]
@khorevaa

**Comment by khorevaa** [comment]
Для работы с хранилищем расширения надо передать '-е ИмяРасширения' подробнее смотрите 'gitsync init --help'

**Comment by malikov-pro** [comment]
В документации описания не нашел, в том что написано в --help непонятно зачем этот флаг нужен.
Указал имя которое в самом расширении на данный момент.

Если подскажите как формировать доку (с MD знаком) и дадите вводные, то думаю смогу помочь с документированием.

**Comment by khorevaa** [comment]
Данный флаг нужен для 1С - это имя расширения с которым оно работает и признак отделения конфигурации расширения от основной конфигурации

Есть файл README.MD туда можно все вносить

**Comment by malikov-pro** [comment]
Тогда какие требования по заполнению этого флага?
Имя расширения может изменяться со временем.

**Comment by nixel2007** [comment]
Если изменится имя расширения, то и строку запуска гитсинка надо будет поменять

**Comment by malikov-pro** [comment]
При данном подходе при изменении имени расширения будет "ломаться" выгрузка.
Если '-е' должно равняться имени расширения, тогда почему его не взять из хранилища, в хранилище же только одно расширение может храниться.

**Comment by khorevaa** [comment]
@malikov-pro ИмяРасширения - это требование 1С. да и в базе может быть несколько расширений, конфигуратор должен же понимать к каким идет работа.
Их хранилища не взять потому как для подключения уже надо имя. (см. ответ выше)
Если есть идеи как это реализовать и ты готов закодить и показать прототип. Жду PR

Ну особый требований нет к оформлению справки нет. Дописывай, что надо в разделы подходящие по смыслу

**Comment by nixel2007** [comment]
Этот флаг передается командной строке запуска конфигуратора, т.е. сам конфигуратор при подключении к хранилищу требует передачи имени расширения.

**Comment by malikov-pro** [comment]
При выгрузке используется чистая база, соответственно в ней создается расширение "Расширение1", после оно подключается к хранилищу (путь, логин, пароль), после чего мы можем получить имя расширения. Пока логически не понимаю для чего требуется указывать имя и что будет если указать "Расширение1" в место того что находится в реквизите "Имя".

**Comment by khorevaa** [comment]
@malikov-pro  Вообще до тех пор пока у тебя в базе - одно расширение никак проблем не будет. 
Как только несколько сразу проблема. и второе ИмяРасширения - служит идентификатором, что идет работа с хранилищем расширения.

**Comment by malikov-pro** [comment]
@khorevaa Немного не понял, как при выгрузке из хранилища мы можем получить в одной базе более одного расширения (база промежуточная на сколько понимаю чистая)?
В базе у меня более одного расширения, но одно расширение подключается к одному хранилищу.

**Comment by khorevaa** [comment]
@malikov-pro Все правильно понял. Когда у тебя промежуточная база (временная) - она чистая. Как только начинаешь указывать конкретную базу для синхронизации сразу возникает указанная проблема. 

Опять повторю сейчас ИМЯ - влияет только на включение режима в конфигураторе  т.е. можно указать любое имя!!

**Comment by malikov-pro** [comment]
"Как только начинаешь указывать конкретную базу для синхронизации" - а этот функционал уже появился?
"влияет только на включение режима в конфигураторе" - это понял.
Если указывается промежуточная база, то от запихивания в нее нескольких расширений больше проблем, чем преимуществ, соответственно зачищаем список расширений и подключаем из хранилища указанного в параметрах запуска.

**Comment by khorevaa** [comment]
@malikov-pro функционал под указание конкретной базы, в планах - как только мне понадобиться я напилю. А так напилить может любой и прислать PR. Кстати там всего то 10 строк кода надо написать )

**Comment by malikov-pro** [comment]
@khorevaa Я пока не силен в onescript (не разбирался с экосистемой), акцент про несколько расширений в промежуточной базе. Лучше свои усилия направлю на тестирование и документирование. Хорошо получается проверять "грабли" и описывать путь с их обходом доступным языком.
"там всего то 10 строк кода надо написать )" - буду рад увидеть их  в RC-2.
