### ISSUE TITLE
Отсутствие предустановленых плагинов

### ISSUE THREAD

**Issue by malikov-pro** [oscript-library/gitsync#180]
Устанавливал из c:\git\OneScript\bin: 

opm install -f gitsync-3.0.0-rc.1.ospx

gitsync plugins init
ИНФОРМАЦИЯ - Начата инициализация предустановленных плагинов
ИНФОРМАЦИЯ - Устанавливаю пакет gitsync-plugins
ИНФОРМАЦИЯ - Установка завершена
ИНФОРМАЦИЯ - Устанавливаю зависимость: <strings> из каталога локальных зависимостей
ПРЕДУПРЕЖДЕНИЕ - Нестандартное имя узла Задачи
ИНФОРМАЦИЯ - <strings> уже установлен. Пропускаем.
ИНФОРМАЦИЯ - Инициализация предустановленных плагинов завершена

gitsync plugins list
Каталог плагинов: <C:\Users\malikov.a.a\AppData\Local\gitsync\plugins>
Список плагинов:

Заметил на том что нет инкремента по выгрузке (последующие выгрузки работаю так же долго как и первая).

**Comment by khorevaa** [comment]
Да все верно показывает по умолчанию только включенные плагины. Смотрите справку по команде 'gitsync p ls --help'

**Comment by malikov-pro** [comment]
Решил за счет включения плагина 'gitsync plugins enable increment'.

Для проверки установки
gitsync plugins install sync-remote
КРИТИЧНАЯОШИБКА - {Модуль C:\git\OneScript\lib\gitsync\oscript_modules\opm\src\core\Классы\МенеджерПолученияПакетов.os / Ошибка в строке: 18 / Ошибка установки пакета sync-remote: Пакет не найден}

Вопрос откуда брать обновления и куда сохранять чтобы инсталлер плагинов их видел.

**Comment by khorevaa** [comment]
`gitsync p ls -a` -  показ уже установленных плагинов

плагин - это пакет ospx - пример вот здесь https://github.com/khorevaa/gitsync-plugins
 и https://github.com/khorevaa/gitsync-shared-authors

Установка через `gitsync p i <путь к файлу opsx>`

**Comment by malikov-pro** [comment]
Более менее понятно, в opm для локальных файлов ключ -f используется.

**Comment by khorevaa** [comment]
@malikov-pro да тут установка только файлов к хабу пакетов как opm не подключается..
