### ISSUE TITLE
ОШИБКА - Получен ненулевой код возврата 128. Выполнение скрипта остановлено!

### ISSUE THREAD

**Issue by malikov-pro** [oscript-library/gitsync#181]
Данную ошибку выдает даже если работа скрипта проходит.
Запускал gitsync init, сначала "код возврата 128", после в 1С вопрос по разрешению открытия.

ОШИБКА - Получен ненулевой код возврата 128. Выполнение скрипта остановлено!
ИНФОРМАЦИЯ - Инициализация завершена

Желательно в лог добавить текущую дату, поможет с таймингами в дальнейшем разбираться.

**Comment by nixel2007** [comment]
У вас вероятно включена защита от опасных действий и/или не установлен rimg

**Comment by malikov-pro** [comment]
Вы правы, включена защита от опасных действий И не установлен ring.
С ring понятно, с "защитой" менее, база то запускается temp, при первом запуске точно будет стоять этот флаг.

**Comment by nixel2007** [comment]
Защита от опасных действий может быть глобально отключена для базы/всех баз через файл conf

**Comment by malikov-pro** [comment]
Добавить в conf.cfg параметр DisableUnsafeActionProtection
"conf.cfg - файл conf.cfg определяет расположение каталога общих конфигурационных файлов. Файл расположен в каталоге bin\conf каталога конкретной версии "1С:Предприятия» и представляет собой текстовый документ в кодировке UTF-8."

**Comment by roman1379** [comment]
Всем привет. 
Аналогичная ошибка при выполнении gitsync sync ....
ОШИБКА - Получен ненулевой код возврата 1. Выполнение скрипта остановлено!
КРИТИЧНАЯОШИБКА - {Модуль C:\Program Files (x86)\OneScript\lib\gitsync\oscript_modules\v8runner\src\v8runner.os / Ошибка в строке: 1291 / Каталог D:\git\temp\4llpp4wf.lac.tmp не пуст.}
Все версии последние, 1с - 8.3.15.1565 
добавил в conf.cfg параметр DisableUnsafeActionProtection=.*
ring поставил, правда от 13 платформы, для 15 нет почему то.
Не помогло. Какие ещё варианты?

**Comment by roman1379** [comment]
вопрос снят, может кому понадобиться, проблема была в версии 1с 8.3.15.1565 с более старой 8.3.13.1809, все работает и ring не нужен.
