### ISSUE TITLE
Отключение от промежуточной базы во время sync

### ISSUE THREAD

**Issue by malikov-pro** [oscript-library/gitsync#184]
Запускаю
gitsync sync
ИНФОРМАЦИЯ - Начало выполнение команды <sync>
ИНФОРМАЦИЯ - Начата синхронизация с git
ИНФОРМАЦИЯ - Номер синхронизированной версии: 0
ИНФОРМАЦИЯ - Номер последней версии в хранилище: 39
ИНФОРМАЦИЯ - Получаем исходники для версии 1, 18.03.2019 10:57:48
ИНФОРМАЦИЯ - Определяю тип возможной выгрузки конфигурации в файлы
ИНФОРМАЦИЯ - Тип выгрузки конфигурации в файлы: ПОЛНАЯ ВЫГРУЗКА
ИНФОРМАЦИЯ - Получаем исходники для версии 2, 18.03.2019 11:09:40
ИНФОРМАЦИЯ - Определяю тип возможной выгрузки конфигурации в файлы
ИНФОРМАЦИЯ - Тип выгрузки конфигурации в файлы: ИНКРЕМЕНТАЛЬНАЯ ВЫГРУЗКА
ОШИБКА - Получен ненулевой код возврата 1. Выполнение скрипта остановлено!
КРИТИЧНАЯОШИБКА - {Модуль C:\git\OneScript\lib\gitsync\oscript_modules\v8runner\src\v8runner.os / Ошибка в строке: 1291 / Не обнаружено свободной лицензии!
}

Проблема с лицензией плавающая, т.к. захожу в файловую базу, норм, после sync нормально работает.

Акцент на том что происходит отключение при выгрузке. 
Возможно ли реализовать без отключения (база одна, то что будет еще выгрузка так же)?

**Comment by khorevaa** [comment]
Сейчас работает так 
При запуске создается временная база и все версии выгружаются через нее. 
Т.е. одна база на 1 запуск.

С такой ошибкой сталкивался у себя - проблема в том, что 1С не всегда находит лицензию.
Лечил указание сервера с лицензиями в nethasp.ini
