### ISSUE TITLE
Имена расширений из файла

### ISSUE THREAD

**Issue by ZhdanovR** [oscript-library/gitsync#186]
На текущий момент имена расширений нужно передавать параметром --extension.
Думаю стоит научить:
- читать какой то служебный файл с именами расширений (допустим их там будет несколько) и по нему гитсинк должен отработать выгрузку.
- возможно, в этом файле должно указываться критичность выгрузки, т.е. падать сборки при ошибке или продолжать дальше и проигнорировать.

## Критерий успешности

Команда
```
 gitsync sync <...> --extNameConf extName.json 
```
Выгрузит все расширения по необходимым путям

**Comment by khorevaa** [comment]
Для этого есть команда all

**Comment by khorevaa** [comment]
@ZhdanovR  /ping

**Comment by ZhdanovR** [comment]
да . Это оно. спасибо!
