### ISSUE TITLE
При использовании gitsync 3 для платформы ниже 8.3.13 для хранилища расширений возникает ошибка

### ISSUE THREAD

**Issue by Begemoth2** [oscript-library/gitsync#189]
При использовании gitsync 3 для платформы ниже 8.3.13 для хранилища расширений возникает ошибка "Для работы с этим расширением конфигурации необходима версия платформы не меньше, чем 8.3.13".

Причина ошибки в том, что в модуле https://github.com/oscript-library/gitsync/blame/release/3.0.0/src/core/%D0%9A%D0%BB%D0%B0%D1%81%D1%81%D1%8B/internal/bindata/%D0%9A%D0%BB%D0%B0%D1%81%D1%81%D1%8B/tempExtension_Gitsync.os в функции ДвоичныеДанные() жетско зашито шаблонно расширение совместимое только с 8.3.13.

В результате в \AppData\Local\Temp\.Gitsync\tempExtension.cfe распаковывается это шаблонное расширение, а потом не может открыться платформой ниже 8.3.13

Подскажите способ исправления или обхода проблемы.

**Comment by khorevaa** [comment]
@Begemoth2  Даже и не знаю. Думаю выложить сюда расширение самого низкой версии и я  его пропишу в файлах.
Вообще можно создать на каждую версию Платформы свое шаблонное расширение

**Comment by Begemoth2** [comment]
@khorevaa Достаточно использовать расширение, созданное в старой версии платформы, в этом случае оно будет открываться во всех более новых версиях без ошибок. Приложил шаблонное расширение сделанное в 8.3.10 (проверил, оно открывается в 8.3.12 и 8.3.13)
[tempExtension.zip](https://github.com/oscript-library/gitsync/files/3003398/tempExtension.zip)

**Comment by khorevaa** [comment]
@Begemoth2 Сделал! В RC2 войдет. Сейчас изменения можно взять из ветки releases/3.0.0

**Comment by Begemoth2** [comment]
@khorevaa Подскажите, а где можно прочитать про то, как в версии 3 из исходников собирать exe шник?
Дело в том, что у нас сейчас везде используется прошлая версия 2, а я так понимаю одновременно 2 и 3 в виде скриптов использовать не получиться

**Comment by nixel2007** [comment]
Вы можете установить гитсинк3 в другой каталог и руками создать новый батник. Тогда будут параллельно работать и двушка и трёшка

**Comment by khorevaa** [comment]
@Begemoth2 Из исходников собирается командой 'opm run make'

**Comment by Begemoth2** [comment]
@nixel2007 @khorevaa Как при сборке exe-шника, таки при непосредственном запуске скрипта через oscript одна и та-же ошибка:

{Модуль C:\Users\vdykov\AppData\Local\Temp\wailbfqd.ohm.tmp\gitsync\oscript_modules\cli\src\core\Классы\internal\types\Классы\ТипДатаВремя.os / Ошибка в строке: 3 / Библиотека не найдена datetime}
{Модуль C:\Users\vdykov\Downloads\gitsync-release-3.0.0\gitsync-release-3.0.0\tasks\make.os / Ошибка в строке: 246 / {Модуль C:\Users\vdykov\AppData\Local\Temp\wailbfqd.ohm.tmp\gitsync\oscript_modules\cli\src\core\Классы\internal\types\Классы\ТипДатаВремя.os / Ошибка в строке: 3 / Библиотека не найдена datetime}
}

**Comment by nixel2007** [comment]
В манифест ошибка. Установите эту библиотеку глобально

**Comment by khorevaa** [comment]
@nixel2007 Да вроде в cli эта либа прописана в зависимости

**Comment by nixel2007** [comment]
@Khorevaa транзитивные зависимости? Ой фу :)

**Comment by khorevaa** [comment]
@nixel2007 Провел исследование `opm i -l` не ставит зависимость `datetime` в от либы `cli`

**Comment by Begemoth2** [comment]
@khorevaa @nixel2007 Подскажите, а что делать "простым смертным" ? Ждать, пока исправиться манифест или есть какой-то простой способ для нас?

**Comment by khorevaa** [comment]
@Begemoth2  сделать `opm install datetime` и должно начать работать

**Comment by Begemoth2** [comment]
@khorevaa Все заработало, расширения разбираются, спасибо!
