### ISSUE TITLE
Адресат вызова создал исключение, ошибка в строке 485

### ISSUE THREAD

**Issue by Lopner** [oscript-library/gitsync#190]
Выгружал файлики в git хранилище, первый раз из 1С базы. Указал чтоб выгружалась последняя версия. 
Проинициализировал хранилище по инструкции (все норм, проблем не было).
Начал выгружать, 

После строчки : раскладываем модули по папкам, согласно иерархии метаданных - выпало исключение:

...gitsync/src/core/классы/МенеджерСинхронизации.os / ошибка в строке 485 / Внешнее исключение {system.reflection.TargetInvocationException} Адресат вызова создал исключения.

Файлики выкачались, но пришлось их руками закоммитить. Подскажите куда копать.

Аналогично выгружал gitsync-ом соседнюю базу, все было норм

**Comment by Lopner** [comment]
У данной базы версия хранилища 8.2.14.0 - и при работе с ним, такая вот ошибка вылезает.
А базы с хранилищем версии 8.3.8.0 нормально выгружаются

**Comment by khorevaa** [comment]
@Lopner  Напишите версию gitsync ( и включенные плагины для версии 3.0.0)

**Comment by Lopner** [comment]
@khorevaa 
gitsync 2.4.3
(Сорян, чет тупанул😁)

установил 3.0.0-rc.1
gitsync plugins ls - показывпет пустой список плагинов. Какие необходимо установить и где их взять?😇

На компе интернета нет, (вроде на компе с инетом они автоматом подтягивались)

**Comment by khorevaa** [comment]
Ошибка возникает для какой версии? 
Если для 2.4.3. - одно дело, для 3.0.0  - другое.

**Comment by Lopner** [comment]
Ошибка возникает для версии 2.4.3

**Comment by khorevaa** [comment]
Переползай на версию 3.0.0-rc.1

**Comment by Lopner** [comment]
Разобрался, спасибо!!! :)

**Comment by EvilBeaver** [comment]
system.reflection.TargetInvocationException - это ошибка движка. Дайте пожалуйста пример строки кода, на которой такое возникает. Такое исключение движок не должен отдавать наверх. Мне бы понять - в каком это месте возникает.

**Comment by khorevaa** [comment]
@EvilBeaver  так же тут все есть 
gitsync/src/core/классы/МенеджерСинхронизации.os / ошибка в строке 485 / Внешнее исключение {system.reflection.TargetInvocationException} Адресат вызова создал исключени

**Comment by EvilBeaver** [comment]
> @EvilBeaver так же тут все есть
gitsync/src/core/классы/МенеджерСинхронизации.os / ошибка в строке 485

Ох, ну вот неклиентоориентированные вы, караул просто. Хорошо, я уточню свою просьбу:

Пожалуйста, приложите максимальные усилия к тому, чтобы мне помочь - ибо именно я буду фиксить ошибку, вы же не собираетесь. Поэтому, можно, конечно, отсылаьть меня к конкретным строчкам гитсинка, чтобы я полез, посмотрел. А можно скинуть сюда сразу фрагмент кода 1С, который падает и я уже полезу в движок, а не сначала в гитсинк.

А еще лучше - написать ПАДАЮЩИЙ ТЕСТ, который послать пулреквестом в движок (тесты же на языке 1С, ничего нового) - и я этот падающий тест исправлю.

Но нет, вы вежливо кидаете мне строку кода с посылом - вот же *блять долбоеб* написана тебе строчка. 

Выделенное курсивом не произносится, но это мое дело - так воспринимать или не воспринимать, в меру своей обидчивости. Но клиентоориентированности (читай, душевности, эмпатии) - прямо-таки не хватает нам всем (
