### ISSUE TITLE
Версия хранилища несов местима с данной версией программы.

### ISSUE THREAD

**Issue by Lopner** [oscript-library/gitsync#191]
Пытаюсь выкачать файлики из хранилища расширений

Инициализирую:
gitsync init -u******* -p=***** //mysrv/ERP_test/ C:/Repos/Git_ERPTEST/config
ОШИБКА - Получен ненулевой код возврата 1. Выполнение скрипта остановлено!
ОШИБКА - Не удалось сформировать файл авторов
КРИТИЧНАЯОШИБКА - {Модуль C:\Program Files (x86)\OneScript\lib\gitsync\oscript_m
odules\v8runner\src\v8runner.os / Ошибка в строке: 1291 / Версия хранилища несов
местима с данной версией программы.
}
в #189 что то похоже вроде писали, а вроде и нет. Подскажите что сделать?

**Comment by Lopner** [comment]
Соответвенно стоит gitsync 3.0.0-rc.1

Скачал, как советовали в #189 ветку release, собрал пакет gitsync-3.0.0-rc.ospx
Устанавливаю его поверх
opm i - f c:\tmp\gitsync-3.0.0-rc.1.ospx

Выпала ошибка после строчки 
- Регистрация приложения: gitsync
Ошибка - файл приложения  ...\gitsync.os не существует

При установке ветка в OneScript/lib/gitsync удаляется.

Что делать, не пойму :(

Ох эти хранилища расширений

**Comment by Lopner** [comment]
И еще подскажите про инкрементную выгрузку. Она в гитсинк 3.0.0 есть? Никак не получаетсч найти :(

**Comment by malikov-pro** [comment]
@Lopner инкрементальная выгрузка работает через плагин
Список https://github.com/khorevaa/gitsync-plugins
Установленные 
gitsync plugins list -a
Активация инкремента 
gitsync plugins enable increment

Для работы с хранилищем расширения нужен ключ --extension
Для установки сначала желательно поставить opm install gitsync, а после поверх накатывать v3, после установки нужно установить пакет по работе с датой (на отсутствие при первом запуске ругнется)

**Comment by Lopner** [comment]
@malikov-pro Огромное спасибо за подробную инструкцию.

Такой еще организационный вопрос. Как технически реализовать синхронизацию хранилища 1С и git, в режиме реального времени? Вы делали что то подобное?

(Я настроил планировщиком windows запуск скрипта раз в сутки, но хотелось бы найти более универсальное решение)

**Comment by malikov-pro** [comment]
@Lopner Еще не реализовывал.
Этапы:
1. установить глобальные настройки разрешающие открытие файлов в 1С
2. активировать плагин sync-remote, как он работает нужно уточнить. (пробовал в bat после gitsync git push не сработало)
3. запустить в шедулере раз в 5 мин.

В git есть web хуки, которые уведомляют потребителей о изменениях в репо, в хранилище 1С не встречал, возможно @allustin может подсказать как они разворачивают автоматику.

**Comment by nixel2007** [comment]
@Lopner на текущий момент применяется два решения:
* старый проверенный запуск раз в пять/десять/пятнадцать минут. зачем ждать сутки, если гитсинк без изменений в хранилище работает быстро?
* экспериментальный прокси на http хранилище от @asosnoviy https://github.com/asosnoviy/commitHook

**Comment by nixel2007** [comment]
можно еще следить за каталогом хранилища, но после 8.3.8 там появляется много ложных срабатываний. Например, захват объекта тоже трогает файл базы данных хранилища. В целом не страшно, но обычно хватает запуска раз в 5 минут.

**Comment by malikov-pro** [comment]
@nixel2007 это работает только для HTTP публикации, и под прокси нужен nix c nginx, в общем решаемо.
А на чем реализуется служба, которая эти запросы обрабатывает?

**Comment by nixel2007** [comment]
@malikov-pro если вы про второй вариант, то мы наверное не так друг друга поняли. вы поднимаете обычное хттп хранилище через nginx/apache. перед ним ставите commitHook, который представляет из себя nginx, выступающий как reverse proxy на реальный http адрес хранилища + через curl отправляет запрос на веб-хук, например, дженкинса, который уже запускает гитсинк.

**Comment by malikov-pro** [comment]
@nixel2007 в https://github.com/asosnoviy/commitHook не отслеживается имя хранилища, соответственно непонятно на какую базу применять gisync.
С jenkins не работал, теперь связка понятна. В любом случае нужно отслеживать очередь чтобы в параллель не запустить gisync на одно хранилище.

**Comment by nixel2007** [comment]
@malikov-pro а вам и не нужно имя хранилища. у вас есть сборка на дженкинсе, у которой есть настройки гитсинка и адрес для веб-хука. вы дергаете конкретный веб-хук соответственно.

**Comment by malikov-pro** [comment]
@nixel2007 За одним прокси может быть несколько хранилищ, соответственно и хуки разные, решается за счет анализа url.

**Comment by nixel2007** [comment]
> В любом случае нужно отслеживать очередь чтобы в параллель не запустить gistync на одно хранилище.

это тоже решается в дженкинсе. отключением конкретного выполнения сборок.

**Comment by asosnoviy** [comment]
> @nixel2007 За одним прокси может быть несколько хранилищ, соответственно и хуки разные, решается за счет анализа url.

Вроде не сложно делается =) И сейчас я бы предложил попробовать прокси на node.

**Comment by Lopner** [comment]
Установил не без труда плагины, обновил gitsync до крайнего релиза. Хранилища расширений разбирает на файлики при версии платформы большей 8.3.10

Регламенты настроил на каждые 15 минут. (Синхронизирую порядка 10 баз, причем планируется увеличение количества баз) Через неделю тестов сервак подвис. В чем причина пока разбираюсь, но смотрю в сторону commitHook, правда от чего оттолкнуться пока хз.
