### ISSUE TITLE
Плагин check-authors не работает на 3.0.0-RC2

### ISSUE THREAD

**Issue by nixel2007** [oscript-library/gitsync#193]
```
16:33:09 ИНФОРМАЦИЯ - Номер синхронизированной версии: 6331
16:33:09 ИНФОРМАЦИЯ - Номер последней версии в хранилище: 6331
16:33:09 ОТЛАДКА - [oscript.lib.delegate] - Создаем Делегат. Имя метода ПередНачаломЦиклаОбработкиВерсий, Тип объекта Плагин_УстановкиЛимитов
16:33:09 ОТЛАДКА - [oscript.lib.delegate] - 		Параметр при создании %2
16:33:09 ОТЛАДКА - [oscript.lib.delegate] - Делегат.Исполнить ПередНачаломЦиклаОбработкиВерсий
16:33:09 ОТЛАДКА - [oscript.lib.delegate] - Делегат.Исполнить. Имя метода ПередНачаломЦиклаОбработкиВерсий, Тип объекта Плагин_УстановкиЛимитов
16:33:09 ОТЛАДКА - [oscript.lib.delegate] - Делегат.Исполнить Кол-во параметров 
16:33:09 ОТЛАДКА - [oscript.lib.delegate] - Создаем Делегат. Имя метода ПередНачаломЦиклаОбработкиВерсий, Тип объекта Плагин_ПроверкиАвторов
16:33:09 ОТЛАДКА - [oscript.lib.delegate] - 		Параметр при создании %2
16:33:09 ОТЛАДКА - [oscript.lib.delegate] - Делегат.Исполнить ПередНачаломЦиклаОбработкиВерсий
16:33:09 ОТЛАДКА - [oscript.lib.delegate] - Делегат.Исполнить. Имя метода ПередНачаломЦиклаОбработкиВерсий, Тип объекта Плагин_ПроверкиАвторов
16:33:09 ОТЛАДКА - [oscript.lib.delegate] - Делегат.Исполнить Кол-во параметров 
16:33:09 КРИТИЧНАЯОШИБКА - {Модуль /home/user/.local/share/gitsync/plugins/gitsync-plugins/src/Классы/check-authors.os / Ошибка в строке: 86 / Метод объекта не обнаружен ({/home/user/.local/share/ovm/dev/lib/gitsync/src/core/Классы/МенеджерСинхронизации.os}::ПрочитатьФайлАвторовГитВТаблицуПользователей)}
```

/cc @igostv

**Comment by khorevaa** [comment]
@nixel2007 После установки надо инициализировать встроенные плагины `gitsync p init`

**Comment by nixel2007** [comment]
RC2 был поставлен поверх RC1, в котором первичная инициализация плагинов уже выполнялась.

Вывод gitsync plugins list -a (прости за скриншот):

![image](https://user-images.githubusercontent.com/1132840/55938184-752da280-5c43-11e9-8e40-73644eb70ec5.png)

После выполнения init и активации плагина все заработало.

Явно не хватает какой-то проверки перед первым gitsync plugins enable. Чтобы команда ругалась, если init ни разу не вызывался. Либо вызывать его автоматом при первом enable.

P.S. Честно, ридми не читал, помню, что плагины надо включать, но вот что их еще надо инициализировать не знал/не вспомнил. Кажется, что первый старт можно немного упростить, добавив либо доп информацию прям в вывод команды enable, либо расширив ее ответственность.

**Comment by nixel2007** [comment]
Вывод plugins list **после** init:

![image](https://user-images.githubusercontent.com/1132840/55938471-203e5c00-5c44-11e9-9082-4f437e2d55c2.png)

Видно, что поменялась версия плагина sync-remote, например.

**Comment by nixel2007** [comment]
Изначальный ишуз можно закрыть, спасибо!
Над докой/доработкой сообщений можно поговорить отдельно.
