### ISSUE TITLE
Обрывается инкрементальная синхронизация - "попытка удаления *.tmp закончилась неудачей, по причине..

### ISSUE THREAD

**Issue by Lopner** [oscript-library/gitsync#194]
Два вопроса. 
1 - почему у меня такие вопросики в логе?
Версия gitsync 3.0.0-rc.2, плагины установил и проинициализировал
2 - одну из баз не выгружает по такой причине (не может удалить файлик .tmp)
Как по мне, не может, ну и ладно, что тут поделать, пускай дальше работает)))

Лог:

C:\Windows\system32>gitsync s -udeploy -p=******* //H_zup C:/Git_ZUP/config -increment
ИНФОРМАЦИЯ - Начало выполнение команды <sync>
ИНФОРМАЦИЯ - Начата синхронизация с git
ИНФОРМАЦИЯ - Использую tool1CD для работы с хранилищем
???? ?????? 1CD ?????
        ???? = \\H_zup\1cv8ddb.1CD
        ????? ???? = 8.3.8.0
        Locale = ru_RU
        ????? = ???? ????
        ??????? ???? = 10
?????? ???? ????? ? ??.
        ?????? = VERSIONS
        ???? = C:\Users\ChackNoris\AppData\Local\Temp\4atvvlpv.g3j.tmp\VERSIONS.xml

???? ?????? 1CD ?????
        ???? = \\H_zup\1cv8ddb.1CD
        ????? ???? = 8.3.8.0
        Locale = ru_RU
        ????? = ???? ????
        ??????? ???? = 10
?????? ???? ????? ? ??.
        ?????? = USERS
        ???? = C:\Users\ChackNoris\AppData\Local\Temp\riivw0b2.wuv.tmp\USERS.xml
ИНФОРМАЦИЯ - Номер синхронизированной версии: 174
ИНФОРМАЦИЯ - Номер последней версии в хранилище: 180
КРИТИЧНАЯОШИБКА - Нашли следующую версию <175> от автора <Петрушка>, а коммент
арий не задан!
ИНФОРМАЦИЯ - Получаем исходники для версии 175, 11.04.2019 14:02:36
???? ?????? 1CD ?????
        ???? = \\H_zup\1cv8ddb.1CD
        ????? ???? = 8.3.8.0
        Locale = ru_RU
        ????? = ???? ????
        ??????? ???? = 10
???????? ??????? ?????? ???????.
        ???? = C:\Users\ChackNoris\AppData\Local\Temp\ka5ewnv4.cs1.tmp\v175.cf
ИНФОРМАЦИЯ - Определяю тип возможной выгрузки конфигурации в файлы
ИНФОРМАЦИЯ - Тип выгрузки конфигурации в файлы: ИНКРЕМЕНТАЛЬНАЯ ВЫГРУЗКА
КРИТИЧНАЯОШИБКА - {Модуль C:\Users\ChackNoris\AppData\Local\gitsync\plugins\gitsync
-plugins\src\Классы\internal\v8unpack\Классы\РаспаковкаФорм.os / Ошибка в строке
: 46 / Внешнее исключение (System.Reflection.TargetInvocationException): Адресат
 вызова создал исключение.}
ПРЕДУПРЕЖДЕНИЕ - Попытка удаления C:\Users\ChackNoris\AppData\Local\Temp\sicykqfr.o
vw.tmp закончилась неудачей, по причине {Модуль C:\Program Files (x86)\OneScript
\lib\gitsync\oscript_modules\tempfiles\ВременныеФайлы.os / Ошибка в строке: 74 /
 Внешнее исключение (System.IO.IOException): Процесс не может получить доступ к
файлу "Form.bin", так как этот файл используется другим процессом.}

**Comment by Lopner** [comment]
Сегодня повторилась ошибка, но с другой базой, которая успешно выгружалась 2 дня. Опять не может удалить файлик .tmp и из-за этого валиться. 

Как то ну очень долго *.cf выгружается(30-40 минут), в некоторых базах, а потом еще и тип выгрузуи - Полная выгрузка, для этих долго думающих баз. Тоесть еще минут 20. Хотя изменения вносились только что. 

Небольшие базы отрабатывают быстро.

**Comment by khorevaa** [comment]
Отключи плагин tool1cd. Будет быстрее

**Comment by Lopner** [comment]
@khorevaa а не подскажите что делать то с исключением?
...
ПРЕДУПРЕЖДЕНИЕ - Попытка удаления C:\Users\ChackNoris\AppData\Local\Temp\sicykqfr.o
vw.tmp закончилась неудачей, по причине {Модуль C:\Program Files (x86)\OneScript
\lib\gitsync\oscript_modules\tempfiles\ВременныеФайлы.os / Ошибка в строке: 74 /
Внешнее исключение (System.IO.IOException): **Процесс не может получить доступ к
файлу "Form.bin", так как этот файл используется другим процессом**.}
...

Файл не удаляется, и далее выгрузка прекращается

**Comment by khorevaa** [comment]
Вообще надо смотреть почему файл остается заблокированным..  Есть подозрение, что не освобождается процессом в плагине unPackForm -попробуйте его отключить

**Comment by Lopner** [comment]
@khorevaa по всей видимости вы попали в точку. Отключил два плагина по вашей рекомендации. Выгружаться стало быстрее и запара с файлом *.tmp ушла. Спасибо!

**Comment by khorevaa** [comment]
Лечение методом удаления..

**Comment by astrizhachuk** [comment]
Проблема не в том, что процесс валится на невозможности удалить файл, а в том, что он валится на создании объекта ЧтениеФайла8(ФайлРаспаковки), а сообщение о невозможности удалить файл происходит во время отката с удалением временных файлов. При этом, судя по тому, что показывает ProcessMonitor, файл перед передачей его в конструктор ЧтениеФайла8 не заблокирован никакими процессами (для эксперимента, можете поставить точку останова и удалить файл). После вызова ЧтениеФайла8 файл блокируется уже в dll, валится эксепшн и файл остается заблокированным.

https://github.com/dmpas/oscript-v8unpack/issues/10
