### ISSUE TITLE
ошибка gitsync init  код ошибки 9009

### ISSUE THREAD

**Issue by ivnazarenko** [oscript-library/gitsync#196]
Господа, подскажите, пожалуйста, как решить проблему:
выполняю команду gitsync init и получаю следующее
![Screenshot_14](https://user-images.githubusercontent.com/49858856/56596969-365ffb00-65fa-11e9-832c-813425d65e80.png)

уже и opm переустанавливал и саму библиотеку, так ничего и не помогло. По веткам полазил, так и не нашел как конкретно решена была такая проблема.
Подскажите куда копать.

**Comment by nixel2007** [comment]
Дайте вывод git --version в консоли

**Comment by ivnazarenko** [comment]
![Screenshot_15](https://user-images.githubusercontent.com/49858856/56603632-c311b580-6608-11e9-9f5c-46184e848e59.png)

**Comment by nixel2007** [comment]
Не то. Читаем ещё раз моё сообщение :)

**Comment by ivnazarenko** [comment]
это про это?
![Screenshot_16](https://user-images.githubusercontent.com/49858856/56605972-f1de5a80-660d-11e9-93a5-491804f3a5b6.png)

**Comment by nixel2007** [comment]
Да, но вы запускаете его из гит баша. а что в cmd?

**Comment by ivnazarenko** [comment]
через cmd у меня такая команда не выполняется. Как по-другому посмотреть я не знаю, к сожалению
переустановил Git и теперь картина следующая

**Comment by nixel2007** [comment]
> через cmd у меня такая команда не выполняется.

в этом и проблема. Вы гитсинк выполняете в cmd, для работы гитсинка ему нужен git в PATH, а там у вас его нет. Ошибка в знаках вопросика именно об этом и говорит. Переустановите git с добавлением его в PATH для CMD, а не только в гит баше.

**Comment by ivnazarenko** [comment]
вы спец, спасибо большое, все получилось.
