### ISSUE TITLE
"Странные" изменения

### ISSUE THREAD

**Issue by abirambul** [oscript-library/gitsync#2]
В конфигурацию добавлен внешний источник данных "Орион".
При каждой выгрузке в git возникают странные изменения для данного объекта, меняется только идентификатор (каждый раз новый). 
Изменений в конфигураторе по данному объекту не вносились.
![default](https://cloud.githubusercontent.com/assets/19974980/18902106/3f7d06f8-8559-11e6-99ec-ebe1eb55bf4e.png)
Как исключить выгрузку таких "странных" изменений?

**Comment by allustin** [comment]
это насколько я помню - проблема платформы: они для объектов перегенрируют GUID. например для ocx файлов. И постоянно исправляют - когда мы им на bugplatform такую ситуацию подаем.

попробуйте проверить с 8.3.9.последней - есть ли там ошибка. Тогда придется подавать реквест на bugplatform чтобы исправили.

//cc @pumbaEO

**Comment by pumbaEO** [comment]
До 8.3.7 они вообще внешние источники не выгружали, так что хоть так и то хорошо. 
Надо добавлять в unidiff1c еще правило.

**Comment by Khorevaa** [comment]
А где этот unidiff1c ?? Готовый?

**Comment by abirambul** [comment]
@allustin Проверял на 8.3.9. Результат не изменился.

А насколько правильно будет, если я через pre-commit буду отменять изменения по таким файлам? 
`git diff --cached --numstat` получить список файлов измененных
`git diff --cached -- ПутьКФайлу`
`git reset HEAD -- ПутьКФайлу`
`git checkout -- ПутьКФайлу`

**Comment by allustin** [comment]
@Khorevaa  https://github.com/pumbaEO/undiff1c
