### ISSUE TITLE
gitsync: Обрабатывать только одну версию хранилища 1С за один запуск, а не все новые версии из хранилища 1С

### ISSUE THREAD

**Issue by artbear** [oscript-library/gitsync#20]
Исходная задача из другого репо https://github.com/EvilBeaver/oscript-library/issues/19

**Comment by ret-Phoenix** [comment]
Вполне может подойти: https://github.com/oscript-library/gitsync/pull/24

gitsync export c:\store\ -minversion 4 -maxversion 7
gitsync export c:\store\ -minversion 3
gitsync export c:\store\ -maxversion 5

В планах добавить параметр -limit, в котором будет указываться сколько версий с последней выгруженной нужно обрабатывать.
т.е. будет как-то так:
gitsync export c:\store\ -limit 1
где:
CurVersion = 5
MaxVersion = CurVersion + limit (5+1=6)

**Comment by artbear** [comment]
Да, согласен, лимит из #24 поможет.

Нужно документировать подобное поведение.
