### ISSUE TITLE
Ошибка gitsync при распаковке

### ISSUE THREAD

**Issue by SBelousov1985** [oscript-library/gitsync#203]
При запуске gitsync выводится следующее сообщение:
GitSync v2.4.2
ИНФОРМАЦИЯ - Начинаю выгрузку исходников
ИНФОРМАЦИЯ - Начало синхронизации с git
???? ?????? 1CD ?????
	???? = C:\1C_Development\maincr\1cv8ddb.1CD
	????? ???? = 8.2.14.0
	Locale = ru_RU
	????? = ???? ????
	??????? ???? = 10
?????? ???? ????? ? ??.
	?????? = USERS
	???? = C:\Users\svc-1C-server\AppData\Local\Temp\tvsxwrow.0ne.tmp\USERS.xml
?????? ???? ????? ? ??.
	?????? = VERSIONS
	???? = C:\Users\svc-1C-server\AppData\Local\Temp\tvsxwrow.0ne.tmp\VERSIONS.xml
ИНФОРМАЦИЯ - Номер синхронизированной версии: 5062
ИНФОРМАЦИЯ - Номер последней версии в хранилище: 5120
ИНФОРМАЦИЯ - Получаем исходники для версии 5063, 28.06.2019 0:00:04
???? ?????? 1CD ?????
	???? = C:\1C_Development\maincr\1cv8ddb.1CD
	????? ???? = 8.2.14.0
	Locale = ru_RU
	????? = ???? ????
	??????? ???? = 10
???????? ??????? ?????? ???????.
	???? = C:\Users\svc-1C-server\AppData\Local\Temp\r1a0cij5.unu.tmp\v5063.cf
ИНФОРМАЦИЯ - Раскладываем модули по папкам согласно иерархии метаданных
КРИТИЧНАЯОШИБКА - {Модуль C:\Program Files (x86)\OneScript\lib\gitsync\src\core\Классы\МенеджерСинхронизации.os / Ошибка в строке: 483 / Внешнее исключение (System.Reflection.TargetInvocationException): Exception has been thrown by the target of an invocation.}

Хранилище конфигурации на 1С 8.2
Версия OneScript (opm version) 0.14.4 (Дистрибутив 1.1.1)
Список библиотек OneScript:
1bdd@1.10.0
1commands@1.3.5
asserts@1.3.0
cmdline@1.0.0
fluent@0.3.1
fs@1.0.0
gitrunner@1.6.0
gitsync@2.4.2
json@1.0.1
logos@1.3.0
notify@0.2.0
opm
strings@0.4.1
tempfiles@0.2.2
tool1cd@0.6
v8runner@1.1.3
v8unpack@1.0.3
Версия ОС: WinSrv 2008 R2
Началось после переустановки OneSrcipt. Переустановить пришлось из-за неработоспособности новой версии gitsync 3.0 - требует обязательного указания логина и пароля хранилища, что на текущий момент затрудняет переход

**Comment by nixel2007** [comment]
По последнему пункту - включите в гитсинке 3.0 плагин Tool1cd. Тогда подключение к хранилищу будет по-старому, без пароля

**Comment by SBelousov1985** [comment]
ОК. Попробую. В старой версии использовали еще такой параметр:
-process-fatform-modules (переименование модулей обычных форм в Module.bsl )
В новой версии этот параметр не воспринимается. Каким образом его использовать?

**Comment by SBelousov1985** [comment]
С плагинами какая-то проблема. Их нет, и не устанавливаются. Вот такая последовательность действий без результата:

_C:\Windows\system32>gitsync plugins enable Tool1cd
Нашли не установленный плагин: Tool1cd

C:\Windows\system32>gitsync plugins list
Каталог плагинов: <C:\Users\sa-belousov\AppData\Local\gitsync\plugins>
Список плагинов:

C:\Windows\system32>gitsync plugins install -f C:\Distr\2.4.2\tool1cd-0.6.ospx
ИНФОРМАЦИЯ - Устанавливаю пакет tool1cd
ИНФОРМАЦИЯ - Установка завершена
ИНФОРМАЦИЯ - Устанавливаю зависимость: tempfiles
ИНФОРМАЦИЯ - tempfiles уже установлен. Пропускаем.
ИНФОРМАЦИЯ - Устанавливаю зависимость: logos
ИНФОРМАЦИЯ - logos уже установлен. Пропускаем.
ИНФОРМАЦИЯ - Устанавливаю зависимость: 1commands
ИНФОРМАЦИЯ - 1commands уже установлен. Пропускаем.

C:\Windows\system32>gitsync plugins enable Tool1cd
Нашли не установленный плагин: Tool1cd

C:\Windows\system32>gitsync plugins list
Каталог плагинов: <C:\Users\sa-belousov\AppData\Local\gitsync\plugins>
Список плагинов:_

**Comment by asosnoviy** [comment]
```
gitsync p init
gitsync p list -a
gitsync plugins enable tool1CD
gitsync plugins enable tool1CD
gitsync p list
```

**Comment by asosnoviy** [comment]
Не уверен, но кажется process-fatform-modules переехало в плагин `unpackForm`

**Comment by SBelousov1985** [comment]
C:\Windows\system32>gitsync p init
ИНФОРМАЦИЯ - Начата инициализация предустановленных плагинов
ИНФОРМАЦИЯ - Устанавливаю пакет gitsync-plugins
ИНФОРМАЦИЯ - Установка завершена
ИНФОРМАЦИЯ - Устанавливаю зависимость: <strings> из каталога локальных зависимос
тей
ИНФОРМАЦИЯ - <strings> уже установлен. Пропускаем.
ИНФОРМАЦИЯ - Инициализация предустановленных плагинов завершена

C:\Windows\system32>gitsync p list -a
{Модуль C:\Program Files (x86)\OneScript\lib\gitsync\src\core\Классы\internal\Кл
ассы\ПодключениеПлагиновКаталога.os / Ошибка в строке: 73 / Внешнее исключение (
System.Collections.Generic.KeyNotFoundException): The given key was not present
in the dictionary.}

C:\Windows\system32>gitsync p list
{Модуль C:\Program Files (x86)\OneScript\lib\gitsync\src\core\Классы\internal\Кл
ассы\ПодключениеПлагиновКаталога.os / Ошибка в строке: 73 / Внешнее исключение (
System.Collections.Generic.KeyNotFoundException): The given key was not present
in the dictionary.}

**Comment by SBelousov1985** [comment]
Пробовал все переустановить сейчас даже команде **gitsync p init** не выполняется
Падает на строке:
ПодключитьСценарий(ФайлКласса.ПолноеИмя, Идентификатор);
Передаваемые параметры:
ФайлКласса.ПолноеИмя: C:\Users\sa-belousov\AppData\Local\gitsync\plugins\tool1cd\table-reader.os
Идентификатор: ЧтениеТаб1лицФайловойБазыДанных
Подскажите, что делаю не так?

**Comment by SBelousov1985** [comment]
Разобрался. Пришлось удалить еще содержимое C:\Users\sa-belousov\AppData\Local\gitsync\
Прошу сообщить, что теперь делать вместо ключа process-fatform-modules?

**Comment by khorevaa** [comment]
@SBelousov1985  Включить плагин `unpackForm` 

и выполнить команду `gitsync s --help`, будет справка и действовать согласно ей

**Comment by SBelousov1985** [comment]
Спасибо, разобрался
