### ISSUE TITLE
удаляется .gitignore

### ISSUE THREAD

**Issue by a-sitnikov** [oscript-library/gitsync#207]
**Описание ошибки**
после выполнения команды sync удаляется файл .gitignore

Версия: 3.0.0 релиз
каталог создан командой gitsync init, внешних репозиториев нет

**Comment by nixel2007** [comment]
В каталоге выгрузки остаются только файлы конфигурации, VERSION и AUTHORS.

Для быстрого решения рекомендую перенести выгрузку в подкаталог, например, в srx

**Comment by Defm** [comment]
Зааппрувлю
Сие есть плохо, потому что .gitignore, .gitattributes и .hooks
Каталог .Git же не удаляется?

**Comment by asosnoviy** [comment]
Обход, не хранить исходники в корне проекта,  а складывать например в ./src

**Comment by EvilBeaver** [comment]
@asosnoviy это даже не обход, а правильное применение. gitsync должен натравливаться на конкретный каталог с сорцами 1С.

**Comment by EvilBeaver** [comment]
> Зааппрувлю
> Сие есть плохо, потому что .gitignore, .gitattributes и .hooks
> Каталог .Git же не удаляется?

Я предположу, что правильным фиксом будет выдача исключения, если gitsync обнаружил, что его запустили в каталоге, где лежит .git

**Comment by Allineer** [comment]
@khorevaa При установке версии 3.4.1 из релизов на гитхабе, этого исправления нет...
