### ISSUE TITLE
 Не найдена лицензия. Не обнаружен ключ защиты программы или полученная программная лицензия

### ISSUE THREAD

**Issue by Lopner** [oscript-library/gitsync#208]
**Описание ошибки**
Создал новую пустую базу с двумя справочниками и новым хранилищем
Версия платформы 8.3.10.2639
gitsync --version 3.0.0

Пишет про отсутствие лицензии.
Что с этим делать?

ИНФОРМАЦИЯ - Начало выполнение команды <sync>
ИНФОРМАЦИЯ - Начата синхронизация с git
ОШИБКА - Получен ненулевой код возврата 1. Выполнение скрипта остановлено!
КРИТИЧНАЯОШИБКА - {Модуль C:\Program Files (x86)\OneScript\lib\gitsync\oscript_m
odules\v8runner\src\v8runner.os / Ошибка в строке: 1291 / Не найдена лицензия. Н
е обнаружен ключ защиты программы или полученная программная лицензия!
}

**Comment by nixel2007** [comment]
Установить лицензионный ключ?

**Comment by EvilBeaver** [comment]
Да ну, ты что! Это точно не при чем

**Comment by Lopner** [comment]
:(

**Comment by nixel2007** [comment]
А теперь серьезно. Какую базу создали? серверную или файловую?

**Comment by Lopner** [comment]
Серверную, 1C + MS SQL - все на одном компе
Где эти лицензии посмотреть можно?

**Comment by nixel2007** [comment]
Они должны торчать либо аппаратными ключами где-то в сети, либо лежать в виде lic файлов в programdata. но суть не в этом - гитсинк для работы создает временную файловую базу. соответственно для его работы на машине должна быть возможность создать и запустить именно файловую базу. в случае сервера 1с, лицензии по умолчанию раздаются только на серверные базы.

**Comment by Bespalov-AV** [comment]
Та же ошибка. Только лицензии сетевые у нас раздаются 1С с другого сервера. Пробую на тестовом сервере. Получается чтобы заработало нужно обязательно локальную лицензию на платформу?

**Comment by EvilBeaver** [comment]
По идее, если раздача лицензий настроена - должен хватать и сетевую

**Comment by Lopner** [comment]
@nixel2007 Да действительно, как-то даже не заметил что не могу развернуть файловую базу...  А может ли gitsync теоретически создавать серверную базу? Не подскажите модуль, в котором создание базы происходит?

**Comment by Lopner** [comment]
По идее можно допилить вариант с разворачиванием серверной базы?

я так предполагаю что в 
src\core\Классы\МенеджерСинхронизации.os
`Функция ПолучитьУправлениеКонфигуратором() `

как раз идет инициализация файловой версии временной БД. 

То есть, теоретически, можно предусмотреть вариант создания временной базы в серверном варианте.

Есть какие-то подводные камни у такого варианта?

**Comment by leemuar** [comment]
> 
> 
> По идее можно допилить вариант с разворачиванием серверной базы?
> 
> я так предполагаю что в
> src\core\Классы\МенеджерСинхронизации.os
> `Функция ПолучитьУправлениеКонфигуратором() `
> 
> как раз идет инициализация файловой версии временной БД.
> 
> То есть, теоретически, можно предусмотреть вариант создания временной базы в серверном варианте.
> 
> Есть какие-то подводные камни у такого варианта?

А ключ   `-C, --ibconnection, --ib-connection``` - это не то что вам нужно?

**Comment by Lopner** [comment]
@leemuar На сколько я понял нет, команды `gitsync init` или `gitsync sync` работают с хранилищем 1С, а файловая база разворачивается по умолчанию для выгрузки конфигурации в виде файликов.

Может  конечно я методологически что-то неправильно понимаю, но примеров или описания с этими параметрами не нашел. 
Как я понимаю должна разворачиваться тестовая база в SQL, и там нужны: 
-имя сервера SQL, 
-имя БД(sql), 
-пользователь БД(sql), 
-пароль этого пользователя, 
-имя кластера сервера, 
-имя информационный базы в кластере 1С, 
-возможно тип СУБД.

**Comment by Lopner** [comment]
@nixel2007  Не подскажите как правильно переустановить пакет? Скачал исходники v8runner, немного поменял скрипт, чтоб временная база создавалась на MSSQL, далее собираю пакет 

`opm build -m C:\tmp\v8runner\packagedef -o C:\tmp\myupdate`
потом новый полученный пакет устанавливаю
`opm install -f C:\tmp\myupdate\v8runner-1.3.0.ospx`


в результате отрабатывает старый алгоритм (команду gitsync запускаю с --verbose, и даже дополнительных логов, которые я добавил не выводятся в консоль)

Такое ощущение что моя версия не устанавливается
пробовал и так
`opm update -f C:\tmp\myupdate\v8runner-1.3.0.ospx`

и в packagedef задавать новую версию 1.4.0
но результат такойже

сам кусочек кода, который разворачивает базу в серверном варианте, протестировал отдельно, все получилось.

**Comment by nixel2007** [comment]
@Lopner у гитсинка все его зависимости упакованы вместе с ним, он игнорирует библиотеки, установленные в систему. Посмотрите каталог oscript_modules, зависимости лежат там. Вы можете перейти в каталог гитсинка и установить нужный пакет из собранного архива, указав дополнительно флаг -l. Это установит пакет "локально", в каталог oscript_modules

**Comment by Lopner** [comment]
В принципе получилось что хотел, создаю временную SQL базу. И gitsync отлично работает.
Правда пока захардкодено это все дело. 
Не нашел как можно проверить существование базы в SQL, методы для удаления, и так же создание и удаление на сервере 1С. (файловую проверяют просто - файлик есть -> ОК, и удалить ее так же просто)

И как получить информацию о лицензиях 1С... (Конечно можно попробовать создать пустую базу в файловом варианте и получить исключение и его обработать, но это как-то кривовато)

**Comment by SMakarovRS** [comment]
> В принципе получилось что хотел, создаю временную SQL базу. И gitsync отлично работает. Правда пока захардкодено это все дело. Не нашел как можно проверить существование базы в SQL, методы для удаления, и так же проверка наличия и удаление на сервере 1С. (файловую проверяют просто - файлик есть -> ОК, и удалить ее так же просто)
> 
> И как получить информацию о лицензиях 1С... (Конечно можно попробовать создать пустую базу в файловом варианте и получить исключение и его обработать, но это как-то кривовато)

есть пример кода? не хочется время тратить.

**Comment by nixel2007** [comment]
Вроде с тех пор в гитсинке плявился параметр для указания сервисной базы
