### ISSUE TITLE
ГитРепозиторий.os / Ошибка в строке: 868

### ISSUE THREAD

**Issue by Lopner** [oscript-library/gitsync#210]
**Описание ошибки**
МенеджерСинхронизации.os
Функция ПолучитьГитРепозиторий(Знач КаталогРабочейКопии) Экспорт

падает на строчке
ГитРепозиторий.УстановитьНастройку("core.quotepath", "false", РежимУстановкиНастроекGit.Локально);

как будто этот метод не выполняется (ставлю лог в начале метода, но ничего не выводится)

...
ИНФОРМАЦИЯ - Определяю тип возможной выгрузки конфигурации в файлы
ИНФОРМАЦИЯ - Тип выгрузки конфигурации в файлы: ПОЛНАЯ ВЫГРУЗКА
ОШИБКА - Получен ненулевой код возврата 1. Выполнение скрипта остановлено!
ОШИБКА - Получен ненулевой код возврата 1. Выполнение скрипта остановлено!
ОШИБКА - Получен ненулевой код возврата 1. Выполнение скрипта остановлено!
КРИТИЧНАЯОШИБКА - {Модуль C:\Program Files (x86)\OneScript\lib\gitsync\oscript_m
odules\gitrunner\src\ГитРепозиторий.os / Ошибка в строке: 868 / "C:/Repos/GIT/1C
_DB/DB1" ?? ????? ???????? ??? ?????
????????, ??????? ?????? ??? ?????? ????.}

**Окружение:**
 - Версия операционной системы: [Windows 7]
 - Редакция 1С платформы [8.3.10.2639]
 - Версия Gitsync [3.0.0]
 - Версия OScript [0.15.3]

**Дополнительный контекст**
Работало все нормально, 
захотел выгрузить конкретную версию хранилища, для ускорения процесса синхронизации новой базы с большой историей. Использовал флаги --minversion 150 --limit 1,
(при этом текущая версия была 140), ничего не произошло. 
Попробовал файлик версий закомитить отдельно с версией 149, а потом запустить gitsync, но теперь все вываливается с ошибкой...

Что это может быть? как это поборотоь

**Comment by Lopner** [comment]
какой-то замкнутый круг
- обновил git до последней версии
- переустановил OneScript и все пакеты
- создал тестовое хранилище с тремя изменениями, оно успешно разбирается
- (в рабочем хранилище никто не работает, это копия), накатил новую копию хранилища для синхронизации
- файлы выгружается но почему то не могут закоммититься
- попробовал заново проинициализировать gitsync init, инициализация проходит нормально, но не помогает, та же ошибка вылитает
- выполняю все под админом
что за напасть такая

**Comment by EvilBeaver** [comment]
Надо бы выяснить что скрывается под знаками вопросов в тексте ошибки

**Comment by Lopner** [comment]
@EvilBeaver знать бы еще как эти вопросики преобразовать. Что то с кодировкой...

Почему-то команды git не могут быть выполнены. 
Очень странная хрень :(

**Comment by khorevaa** [comment]
Перед выполнением переключите  кодировку на utf-8 
`chcp 65001`

**Comment by Lopner** [comment]
@khorevaa Вот такое сообщение выпадает 
ОШИБКА - Получен ненулевой код возврата 1. Выполнение скрипта остановлено!
КРИТИЧНАЯОШИБКА - {Модуль C:\Program Files (x86)\OneScript\lib\gitsync\oscript_m
odules\gitrunner\src\ГитРепозиторий.os / Ошибка в строке: 868 / 'C:/Repos/GIT/1C
_DB/DB1' is not recognized as an internal or external command,
operable program or batch file.}

Я так понял, что то связано с переменными среды, по всей видимости не понимает команду git, когда она выполняется в контексте gitsync. Все это как-то странно, потому что тестовое хранилище как разбиралось, так и разбирается

Переустановил еще раз git c такими параметрами
![Git settings](https://user-images.githubusercontent.com/23383979/65135938-77283880-da0f-11e9-932a-d53016cc6a48.png)
Но никакого результата пока  не получил

**Comment by Lopner** [comment]
Хотя судя по логу, попадает почему то путь, а наверно должна попадать команда git

> ИНФОРМАЦИЯ - ПолучитьПутьКГит()
> ИНФОРМАЦИЯ - ПолучитьРабочийКаталог()
> ИНФОРМАЦИЯ - УстановитьКодировкуВывода
> ИНФОРМАЦИЯ - Команда C:/Repos/GIT/1C_DB/DB1
> ИНФОРМАЦИЯ - Параметр команды add
> ИНФОРМАЦИЯ - Сообщение команды
> ИНФОРМАЦИЯ - Параметр команды -A
> ИНФОРМАЦИЯ - Сообщение команды
> ИНФОРМАЦИЯ - Параметр команды .
> ИНФОРМАЦИЯ - Сообщение команды
> ИНФОРМАЦИЯ - Рабочий каталог команды C:/Repos/GIT/1C_DB/DB1
> ИНФОРМАЦИЯ - ВЫВОД КОМАНДЫ 'C:/Repos/GIT/1C_DB/DB1' is not recognized as
>  an internal or external command,

**Comment by Lopner** [comment]
А вот пример лога успешной работы тестового хранилища с тремя коммитами в 1С

> ИНФОРМАЦИЯ - Тип выгрузки конфигурации в файлы: ПОЛНАЯ ВЫГРУЗКА
> ИНФОРМАЦИЯ - ПолучитьПутьКГит()
> ИНФОРМАЦИЯ - ПолучитьРабочийКаталог()
> ИНФОРМАЦИЯ - УстановитьКодировкуВывода
> ИНФОРМАЦИЯ - Команда git
> ИНФОРМАЦИЯ - Параметр команды config
> ИНФОРМАЦИЯ - Сообщение команды
> ИНФОРМАЦИЯ - Параметр команды --local
> ИНФОРМАЦИЯ - Сообщение команды
> ИНФОРМАЦИЯ - Параметр команды core.quotepath
> ИНФОРМАЦИЯ - Сообщение команды
> ИНФОРМАЦИЯ - Параметр команды false
> ИНФОРМАЦИЯ - Сообщение команды
> ИНФОРМАЦИЯ - Рабочий каталог команды D:\Repos\GIT\1C_DB\mytestbase_1c

**Comment by Lopner** [comment]
Кажется я пробил эту стену)) 

Прописал жестко в

> ГитРепозиторий.os
```
Процедура УстановитьПутьКГит(Знач Путь) Экспорт
    ПутьКГит = "git";
КонецПроцедуры
```
И пошло, поехало. 

Походу нарушается область видимости переменной "Путь"  и при инициализации не всегда попадает туда параметр "git".

**Comment by khorevaa** [comment]
Попробуй воспользоваться  опцией
`--git-path` - путь к исполняемому файлу git
					.
