### ISSUE TITLE
gitsync и расширение конфигурации

### ISSUE THREAD

**Issue by roman1379** [oscript-library/gitsync#211]
**Описание ошибки**
gitsync init проходит успешно, выгружаются пользователи в файл AUTHORS
запускаю gitsync sync <хранилище конфы 1с> <локальный каталог исходников внутри локальной копии git-репозитория>

ОШИБКА - 17.09.2019 7:27:45 <ok> База данных 1CD открыта
        Файл = d:\Hran_BUH_NKO\1cv8ddb.1CD
        Версия базы = 8.3.8.0 (по факту режим совместимости 8.3.12)
        Locale = ru_RU
        Режим = Только чтение
        Количество таблиц = 10
17.09.2019 7:27:45 <error> Неизвестная версия хранилища
        Версия хранилища = 6400000000000000
17.09.2019 7:27:45 <error> Не удалось сохранить конфигурацию хранилища.
        Файл = D:\git\temp\rahbeazk.3ir.tmp\v1.cf

КРИТИЧНАЯОШИБКА - {Модуль C:\Users\user\AppData\Local\gitsync\plugins\gitsync-plugins\src\Классы\internal\tool1cd\Классы\ЧтениеХранилищаКонфигурации.os / Ошибка в строке: 49 / Tool_1CD вернул код возврата 1}

Используется расширение конфигурации которое подключено к хранилищу 1С
До запуска приложения 1С не доходит.

**Окружение:**
 - Версия операционной системы:  windows Server 2016
 - Редакция 1С платформы  8.3.13.1809
 - Версия Gitsync 3.0.0
 - Версия tool1cd 0.6
 - Версия OScript  1.1.1

**Дополнительный контекст**

Типовая БУХ НКО используется расширение конфигурации где ведется разработка с подключение к хранилищу конфы.  Выключен режим защиты от опасных действий.

**Comment by nixel2007** [comment]
Для работы хранилища расширений нужно передать дополнительный флаг. Плюс я не уверен, что плагин tool1cd умеет работать с хранилищами расширений, возможно его придётся отключить.

/cc @Khorevaa

**Comment by roman1379** [comment]
какой флаг, где его передавать?

**Comment by khorevaa** [comment]
`gitsync s --help`

**Comment by roman1379** [comment]
Про отправку в справку спасибо, знал что она есть... а как конкретно обойти ошибку не знаете, не подскажете? Или в гугл теперь отправите? ) Сам то работали с расширениями конфигурации применительно с Gitsync?

**Comment by khorevaa** [comment]
@roman1379  отключите плагин tool1CD для хранилища расширения. 
П.с. с хранилищами для расширений работаем, в том числе и тестировали на временных и настоящих

**Comment by roman1379** [comment]
Отключил, теперь 
ИНФОРМАЦИЯ - Начало выполнение команды <sync>
ИНФОРМАЦИЯ - Начата синхронизация с git
ОШИБКА - Получен ненулевой код возврата 1. Выполнение скрипта остановлено!
КРИТИЧНАЯОШИБКА - {Модуль C:\Program Files (x86)\OneScript\lib\gitsync\oscript_modules\v8runner\src\v8runner.os / Ошибка в строке: 1291 / Соединение основной конфигурации с хранилищем расширений конфигураций невозможно}

**Comment by khorevaa** [comment]
@roman1379  Дайте строку запуска gitsync. И вы все же флаг `-e` передали?

**Comment by roman1379** [comment]
Теперь указал опцию -e, сразу не понял т.к. говорили про флаг, а это вроде не флаг ) Спасибо все получилось! )

**Comment by nixel2007** [comment]
Рад, что все получилось :)

**Comment by hrom-code** [comment]
с параметром "-e "МоёРасширение" " получилось
а с "--extension "МоёРасширение" " и "env.GITSYNC_STORAGE_EXTENSION = 'МоёРасширение'"  не получилось
