### ISSUE TITLE
Обрезается часть сообщения коммита, если сообщение версии содержит URL

### ISSUE THREAD

**Issue by leemuar** [oscript-library/gitsync#212]
**Описание ошибки**
допустим в хранилище конфигурации есть версия, текст сообщения которой равен:
> http://mycompany.jira.com/issue/IFF-809
> Исправлена загрузка изображений формата PNG

когда я выгружаю эту версию в git с использованием gitsync.exe 
тогда текст коммита в гит равен

> http:Исправлена загрузка изображений формата PNG

обрезается весь текст после двойных слешей (//) до конца строки и сами слеши

**Ожидаемое поведение если бы ошибки не было**
Текст коммита выгружается "как есть", полностью

**Окружение:**
 - Версия операционной системы: Win10
 - Редакция 1С платформы 8.3.11.2867
 - Версия Gitsync: 3.0.0 standalone exe

**Comment by nixel2007** [comment]
Обсуждалось уже)
Это поведение платформы, из командного режима изменить нельзя. При необходимости используй плагин тул1сд

**Comment by khorevaa** [comment]
Да это проблема формирования отчета по версиям программным способом в платформе - всегда отрезаются комментарии (// ...). Если хранилище не http, тогда можно использовать tool1CD плагин для получение истории и версий

**Comment by leemuar** [comment]
ок, тогда предлагаю хотя бы в README эту особенность описать

**Comment by EvilBeaver** [comment]
@leemuar что мешает это сделать?

**Comment by leemuar** [comment]
Неактуально. в 8.3.17 появился флаг, позволяющий это поведение отключать, гитсинк его поддерживает. Считаю проблему решенной
