### ISSUE TITLE
Использование библиотеки 1commands

### ISSUE THREAD

**Issue by artbear** [oscript-library/gitsync#22]
+ Заменить использование встроенного класса КомандныйФайл на более актуальную версию из https://github.com/artbear/1commands
+ Проверить использование методов запуска процессов без командных файлов
  + Если есть, заменить соответствующий код, вставив использование класса `Команда`

+ `1commands` прописать в зависимости `gitsync` (packadef) для автозагрузки через `opm install`

**Comment by nixel2007** [comment]
Зачем сабмодулем? либо это библиотека с нормальным апи, которая встравивается без проблем, либо не надо этого вообще. :)

**Comment by artbear** [comment]
Конечно, это библиотека.

Тут вопрос по процессу разработки:
скачать исходники гитсинка будет недостаточно для запуска, т.к. не будет исходников 1commands 

Вопрос - как получить исходники?

Или мы делаем эту библиотеку входящей в стандартную библиотеку и она будет обязательно прилетать с релизом 1скрипт?

**Comment by nixel2007** [comment]
> Вопрос - как получить исходники?

добавить в packagedef.
после скачки выполнить `opm install`

Добро пожаловать в мир нод.жс. любой мало-мальски небольшой проект надо сконфигурить перед первым запуском.

**Comment by artbear** [comment]
Согласен, так и сделаю.

Другие комментарии есть? ИМХО замена полезная.

Я лично подзадолбался копипастить код по запуску процессов в каждом проекте :) вот и родился этото пакет.

**Comment by EvilBeaver** [comment]
Да, и гитсинк из стандартной поставки выпилить. Ибо оетвсе авно без opm app не работает

**Comment by artbear** [comment]
В рамках этой задачи я избавился от старого файла КомандныйФайл и перешел на 1commands
