### ISSUE TITLE
Не получается выгрузить хранилище

### ISSUE THREAD

**Issue by mors1eska** [oscript-library/gitsync#228]
**Описание ошибки**
При выгрузке хранилище командой sync возникает ошибка **** stack smashing detected ***: ./a.out terminated*

![image](https://user-images.githubusercontent.com/34914654/72495177-00713f80-3837-11ea-8301-6ad63b323f57.png)

При этом аварийно завершается процесс гита

Пробовал и с использованием tool1CD и без
Выгрузка конфигурации в файлы из конфигуратора проходит без ошибок (конфигурация идентична хранилищу)
Если их сравнить по размеру - очень похоже получается
![image](https://user-images.githubusercontent.com/34914654/72496462-b7bb8580-383a-11ea-8bc5-87d9b4a68d80.png)

**Окружение:**
 - Версия операционной системы: win server 2012
 - Редакция 1С платформы: 8.3.13.1644
 - Версия Gitsync 3.0.0
 - Версия OScript 1.2.0.92

**Дополнительный контекст**
Конфигурация не типовая, сильно измененная, много обычных форм

**Comment by nixel2007** [comment]
Гуглеж подсказывает, что это защитный механизм, встраиваемый gcc. С учётом места возникновения исключения и отсутствия прочих с-компонентов можно предположить, что проблема в гите. Попробуйте обновить гит на машине.

**Comment by mors1eska** [comment]
Спасибо за ответ, но, к сожалению, гит только вчера установил свежий.
Попробую выгрузить файлы конфигурации в папку с гитом без гитсинк, проверю будет ли падение в этом случае

**Comment by nixel2007** [comment]
Попробуйте включить отладочные логи, чтобы понять, на какой конкретно команде падает.

```
set LOGOS_CONFIG=logger.rootLogger=DEBUG
```

**Comment by mors1eska** [comment]
Последние логи какие-то такие
![image](https://user-images.githubusercontent.com/34914654/72508237-628d6d00-3856-11ea-86d1-69636f4a5ec2.png)

Они показательны?

**Comment by nixel2007** [comment]
да, видно конкретную команду, где происходит падение - `git add -A .`

Попробуйте ее же выполнить из консоли после выгрузки файлов конфигуратором.

**Comment by mors1eska** [comment]
Буду пробовать
Как думаете, может из-за этого валится гит?
![image](https://user-images.githubusercontent.com/34914654/72598860-b1ec9f80-3921-11ea-926e-bc5ed7ce161a.png)

**Comment by mors1eska** [comment]
Что-то странное происходит
1. выгрузил конфигурацию в файлы
2. пытаюсь добавить в индекс (git add -A) получаю ошибку "Illegal instruction"
Причем ни один из git add не срабатывает

![image](https://user-images.githubusercontent.com/34914654/72600324-769fa000-3924-11ea-91c6-0bce386771d2.png)

**Comment by mors1eska** [comment]
Причем сделал тоже самое руками, только с сильно меньшей конфигурацией (там где ошибка файлов примерно на 4гб)
и все работает

![image](https://user-images.githubusercontent.com/34914654/72601157-f11cef80-3925-11ea-9b8e-9c6cd3a123d4.png)

**Comment by nixel2007** [comment]
> git add -A

точку в конце забыли.

**Comment by nixel2007** [comment]
ну а вообще гит явно в консоли пишет, что репозиторий заблокирован от изменений. либо в параллельном процессе кто-то что-то туда пишет, либо какая-то операция рухнула, и надо вручную удалить index_lock

**Comment by asosnoviy** [comment]
А черепашка не установлена случайно?

**Comment by asosnoviy** [comment]
В телеграмме сегодня выяснили, что git 2.25.0 не работает. 
И надо понизить до 2.23

https://t.me/oscript_library/17432

**Comment by mors1eska** [comment]
> > git add -A
> 
> точку в конце забыли.

а с точкой совсем что-то не то пишет, кажется все же нужно без точки.
я нашел на чем падает

![image](https://user-images.githubusercontent.com/34914654/72622618-a6ff3280-3954-11ea-8dc8-e7f802fb9d43.png)

G:\git_fr\config\DataProcessors\ДокументооборотСКонтролирующимиОрганами\Forms\РегистрСведений_ХранилищеЭлектронныхПредставленийРегламентированныхОтчетов_ФормаСписка\Ext

Может путь какой-то слишком длинный для гита?



> ну а вообще гит явно в консоли пишет, что репозиторий заблокирован от изменений. либо в параллельном процессе кто-то что-то туда пишет, либо какая-то операция рухнула, и надо вручную удалить index_lock

кажется, после того как гит ломается, он не завершает какой-то процесс, файл приходится вручную удалять после этого

**Comment by mors1eska** [comment]
> В телеграмме сегодня выяснили, что git 2.25.0 не работает.
> И надо понизить до 2.23
> 
> https://t.me/oscript_library/17432

Спасибо, буду пробовать

**Comment by mors1eska** [comment]
> В телеграмме сегодня выяснили, что git 2.25.0 не работает.
> И надо понизить до 2.23
> 
> https://t.me/oscript_library/17432

на 2.23 все сработало без танцев, спасибо.
