### ISSUE TITLE
Не подключается плагин unpackForm

### ISSUE THREAD

**Issue by mors1eska** [oscript-library/gitsync#230]
**Описание ошибки**
Не получается инициализировать плагин unpackForm (несколько других удалось подключить без проблем)

![image](https://user-images.githubusercontent.com/34914654/72682453-3edc5800-3ade-11ea-898b-5e3a6669f493.png)

**Окружение:**
 - Версия Gitsync 3.0.0

**Comment by nixel2007** [comment]
У вас опечатка в имени плагина

**Comment by mors1eska** [comment]
> У вас опечатка в имени плагина

увидел, спасибо!
запутало сообщение что плагин найден, но он не установлен
