### ISSUE TITLE
Установка в Docker

### ISSUE THREAD

**Issue by Shining-Phoenix** [oscript-library/gitsync#231]
Образ на основе ubuntu:18.04.
Установил gitsync.

Выполнил:
root@a71a31a1b979:/home# gitsync plugins init
ИНФОРМАЦИЯ - Начата инициализация предустановленных плагинов
ИНФОРМАЦИЯ - Инициализация предустановленных плагинов завершена
root@a71a31a1b979:/home# gitsync plugins list -a
Каталог плагинов: </root/.local/share/gitsync/plugins>
Список плагинов:
root@a71a31a1b979:/home#

Т.е. плагинов нет.
Как их установить?

Пробовал выполнить на всякий случай:
root@a71a31a1b979:/home# gitsync -v plugins enable limit
ОТЛАДКА - [oscript.app.gitsync] - Устанавливаю общие параметры
Нашли не установленный плагин: limit
КРИТИЧНАЯОШИБКА - {Модуль /usr/share/oscript/lib/gitsync/src/core/Классы/internal/files/Модули/РаботаСФайлами.os / Ошибка в строке: 28 / Внешнее исключение (System.TypeInitializationException): The type initializer for 'Newtonsoft.Json.JsonWriter' threw an exception.}
root@a71a31a1b979:/home#

На самом деле нет.

Нужна помощь куда копать.

**Comment by nixel2007** [comment]
Для начала у вас не полная установка mono. Нужно установить ещё библиотеки по работе с json
libmono-system-runtime-serialization4.0-cil

**Comment by Shining-Phoenix** [comment]
По моему уже стоит
root@955ca6ee02a9:/tmp# apt install libmono-system-runtime-serialization4.0-cil
Reading package lists... Done
Building dependency tree
Reading state information... Done
libmono-system-runtime-serialization4.0-cil is already the newest version (6.8.0.96-0xamarin4+ubuntu1804b1).
libmono-system-runtime-serialization4.0-cil set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 6 not upgraded.

**Comment by nixel2007** [comment]
Хм, действительно, говорит, что уже есть.

Вообще насколько я понимаю в гитсинк 3.1 есть какие-то проблемы с инициализацией плагинов.
Приглашаю @Khorevaa и @artbear

**Comment by Shining-Phoenix** [comment]
Устанавливал mono 4.8.1.
apt install libmono-system-runtime-serialization4.0-cil
Reading package lists... Done
Building dependency tree
Reading state information... Done
libmono-system-runtime-serialization4.0-cil is already the newest version (4.6.2.7+dfsg-1ubuntu1).
libmono-system-runtime-serialization4.0-cil set to manually installed.

Версия библиотеки ниже.

root@87a9c24ab188:/tmp# gitsync -v plugins init
ОТЛАДКА - [oscript.app.gitsync] - Устанавливаю общие параметры
ИНФОРМАЦИЯ - Начата инициализация предустановленных плагинов
ОТЛАДКА - [oscript.app.gitsync] - Каталог поиска предустановленных плагинов: </usr/share/oscript/lib/gitsync/embedded_plugins>
ОТЛАДКА - [oscript.app.gitsync] - Количество пакетов плагинов к установке: <0>
ИНФОРМАЦИЯ - Инициализация предустановленных плагинов завершена

**Comment by Shining-Phoenix** [comment]
На всякий случай - содержимое папки GitSync:
root@87a9c24ab188:/usr/share/oscript/lib/gitsync# dir
docs  lib.config  opm-metadata.xml  oscript_modules  readme.md  src  templates

**Comment by khorevaa** [comment]
@nixel2007 Я догадался в чем трабла с версией 3.1.0 - ее видимо @artbear собрал без указания манифеста `build_packagedef` - что привело к отсутствию встроенных плагинов в пакете.

@Shining-Phoenix Возьми плагины [отсюда](https://github.com/khorevaa/gitsync-plugins/releases) и установи их через команду `gitsync p i <фвйл_плагинов>`

**Comment by nixel2007** [comment]
Тогда надо срочно ре-релизить 3.1.1

**Comment by Shining-Phoenix** [comment]
Спасибо за помощь. Нормуль.
