### ISSUE TITLE
Не выгружаются изменения на платформе 8.3.15

### ISSUE THREAD

**Issue by Wadus16** [oscript-library/gitsync#236]
**Описание ошибки**
После перехода на платформу 8.3.15 в репозитории не видно изменений, меняется только файлы ConfigDumpInfo.xml и VERSION

**Окружение:**
 - Версия операционной системы: windows 10
 - Редакция 1С платформы 8.3.15.1565
 - Версия Gitsync 2.4.3
 - Версия OScript 1.2.0.92

**Дополнительный контекст**

Конфигурация нетиповая  UT, при первой выгрузке все файлы выгружаются корректно, при повторной выгрузке не может правильно выгрузить отличия, точнее как я уже говорил обновляет только файлы ConfigDumpInfo.xml и VERSION. На 8.3.14 все работает корректно. 

Может сталкивались с таким?

**Comment by nixel2007** [comment]
Сталкивались. Переезжайте на гитсинк 3 :)
