### ISSUE TITLE
Docker - 8.3.16.1063 -  v8runner.os / Ошибка в строке: 1291

### ISSUE THREAD

**Issue by Shining-Phoenix** [oscript-library/gitsync#237]
Добрый день!

**Ошибка:**
КРИТИЧНАЯОШИБКА - {Модуль /usr/share/oscript/lib/gitsync/oscript_modules/v8runner/src/v8runner.os / Ошибка в строке: 1291 / Каталог /tmp/cgsz6k38.2v0.tmp не пуст.

Вроде все стоит, но не уверен.
Где туплю - хз.
Может на другой площадке такие темы поднимать или здесь нормально?

**Исходные данные:**

**1.** 

root@2e5fded9c7bf:/# java -version
openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment (build 11.0.6+10-post-Ubuntu-1ubuntu118.04.1)
OpenJDK 64-Bit Server VM (build 11.0.6+10-post-Ubuntu-1ubuntu118.04.1, mixed mode, sharing)

**2.**

root@2e5fded9c7bf:/# ring -version
awk: line 2: function gensub never defined
0.17.0-1

Возможно встал не так. Брал из license-tools
sh /tmp/license-tools/1ce-installer-cli --verbose full install --ignore-signature-warnings 

**3. Содержимое conf.cfg**

SystemLanguage=System
DisableUnsafeActionProtection=.*

**4.**

root@2e5fded9c7bf:/# opm list
Пакеты в системном каталоге библиотек </usr/share/oscript/lib>:
cmdline@1.0.0
opm
tempfiles@0.2.2
asserts@0.4.0
gitsync@3.1.0
json@1.0.1
v8runner@1.1.3
notify@0.2.0
fluent@0.3.1
1commands@1.3.2
oscript-config@0.1.0
strings@0.4.1
logos@1.0.2
fs@0.5.0
root@2e5fded9c7bf:/#  

**5.**

root@2e5fded9c7bf:/# gitsync plugins list
Каталог плагинов: </root/.local/share/gitsync/plugins>
Список плагинов:
 [on] [1.0.5] - increment - Плагин добавляет возможность инкрементальной выгрузки в конфигурации
 [on] [1.0.5] - limit - Плагин добавляет возможность ограничения на минимальный, максимальный номер версии хранилища, а так же на лимит на количество выгружаемых версий за один запуск
 [on] [1.0.5] - sync-remote - Плагин добавляет функциональность синхронизации с удаленным репозиторием git

**6. Лог:**

root@2e5fded9c7bf:/# gitsync -v sync --storage-user User --storage-pwd Secret tcp://192.168.56.1/GitSync /GitSync
ОТЛАДКА - [oscript.app.gitsync] - Устанавливаю общие параметры
ИНФОРМАЦИЯ - Начало выполнение команды <sync>
ОТЛАДКА - [oscript.app.gitsync] - ПутьКХранилищу = tcp://192.168.56.1/GitSync
ОТЛАДКА - [oscript.app.gitsync] - КаталогРабочейКопии = /GitSync
ОТЛАДКА - [o.l.g.p.sync-remote] - Установлена отправка изменений <Нет>
ОТЛАДКА - [o.l.g.p.sync-remote] - Установлено получение изменений <Нет>
ОТЛАДКА - [o.l.g.p.sync-remote] - Установлено количество коммитов <0> после, которых осуществляется отправка
ОТЛАДКА - [o.l.g.p.sync-remote] - Установлен флаг оправки меток в значение <Нет> выгрузки версий
ОТЛАДКА - [oscript.lib.gitsync] - Установлена авторизация в хранилище пользователь <User>, пароль <Secret>
ИНФОРМАЦИЯ - Начата синхронизация с git
ОТЛАДКА - [oscript.lib.gitsync] - Используется платформа 1С версии <8.3>
ОТЛАДКА - [oscript.lib.gitsync] - Предыдущая версия из хранилища 1С: <1>
ОТЛАДКА - [oscript.lib.gitsync] - Получение таблицы версий средствами 1С.Предприятие
ОТЛАДКА - [oscript.lib.v8runner] - КлючСоединенияСБазой /F"/tmp/z1t1ozws.g8z.tmp/v8r_TempDB"
ОТЛАДКА - [oscript.lib.v8runner] - ИмяПользователя <>
ОТЛАДКА - [oscript.lib.v8runner] - Проверяю равенство КлючСоединенияСБазой() = КлючВременногоКонтекста() и Не ВременнаяБазаСуществует()
ОТЛАДКА - [oscript.lib.v8runner] - КлючСоединенияСБазой() /F"/tmp/z1t1ozws.g8z.tmp/v8r_TempDB"
ОТЛАДКА - [oscript.lib.v8runner] - КлючВременногоКонтекста() /F"/tmp/z1t1ozws.g8z.tmp/v8r_TempDB"
ОТЛАДКА - [oscript.lib.v8runner] - ВременнаяБазаСуществует() Нет
ОТЛАДКА - [oscript.lib.v8runner] - Равенство выполняется.
ОТЛАДКА - [oscript.lib.v8runner] - Создаю временную базу. Путь /tmp/z1t1ozws.g8z.tmp/v8r_TempDB
ОТЛАДКА - [oscript.lib.v8runner] - Создаю файловую базу /tmp/z1t1ozws.g8z.tmp/v8r_TempDB
ОТЛАДКА - [oscript.lib.v8runner] - "/opt/1C/v8.3/x86_64/1cv8" CREATEINFOBASE File="/tmp/z1t1ozws.g8z.tmp/v8r_TempDB" /Out "/tmp/z1t1ozws.g8z.tmp/mzpvuery.2en.txt" /LRU /VLRU
ОТЛАДКА - [oscript.lib.v8runner] - Получен код возврата 0
ОТЛАДКА - [oscript.lib.v8runner] - Это внешний файл информации: Нет
ОТЛАДКА - [oscript.lib.v8runner] - Очищать файл информации: Да
ОТЛАДКА - [oscript.lib.v8runner] - Удаляю файл информации 1С
ОТЛАДКА - [oscript.lib.v8runner] - файл информации:
Создание информационной базы ("File=/tmp/z1t1ozws.g8z.tmp/v8r_TempDB;Locale = "ru_RU";") успешно завершено

ОТЛАДКА - [oscript.lib.v8runner] - "/opt/1C/v8.3/x86_64/1cv8" DESIGNER /F"/tmp/z1t1ozws.g8z.tmp/v8r_TempDB" /Out "/tmp/z1t1ozws.g8z.tmp/mzpvuery.2en.txt" /WA+ /LRU /VLRU /DisableStartupMessages /DisableStartupDialogs /ConfigurationRepositoryN "User" /ConfigurationRepositoryF "tcp://192.168.56.1/GitSync" /ConfigurationRepositoryReport "/tmp/kdb5gjo3.d72.mxl" -NBegin 1
ОТЛАДКА - [oscript.lib.v8runner] - Получен код возврата 0
ОТЛАДКА - [oscript.lib.v8runner] - Это внешний файл информации: Нет
ОТЛАДКА - [oscript.lib.v8runner] - Очищать файл информации: Да
ОТЛАДКА - [oscript.lib.v8runner] - Удаляю файл информации 1С
ОТЛАДКА - [oscript.lib.v8runner] - файл информации:

ОТЛАДКА - [oscript.lib.v8runner] - Код возврата равен 0
ОТЛАДКА - [oscript.lib.gitsync] - Добавили строку в таблицу версий:
 Номер версии: 1
 Автор:        Администратор
 ГУИД_Автора:  Администратор
 Дата:         23.02.2020 11:32:26
 Комментарий:  Создание хранилища конфигурации

ОТЛАДКА - [oscript.lib.gitsync] - Добавили строку в таблицу версий:
 Номер версии: 2
 Автор:        Администратор
 ГУИД_Автора:  Администратор
 Дата:         23.02.2020 11:33:11
 Комментарий:  Тест 1

ОТЛАДКА - [oscript.lib.gitsync] - Добавили строку в таблицу версий:
 Номер версии: 3
 Автор:        Администратор
 ГУИД_Автора:  Администратор
 Дата:         23.02.2020 11:33:43
 Комментарий:  Тест 2

ОТЛАДКА - [oscript.lib.gitsync] - Добавили строку в таблицу версий:
 Номер версии: 4
 Автор:        Администратор
 ГУИД_Автора:  Администратор
 Дата:         23.02.2020 11:34:03
 Комментарий:  Тест 3

ОТЛАДКА - [oscript.lib.gitsync] - Добавили строку в таблицу версий:
 Номер версии: 5
 Автор:        Администратор
 ГУИД_Автора:  Администратор
 Дата:         24.02.2020 18:58:53
 Комментарий:  Тест 4

ИНФОРМАЦИЯ - Номер синхронизированной версии: 1
ИНФОРМАЦИЯ - Номер последней версии в хранилище: 5
ИНФОРМАЦИЯ - Получаем исходники для версии 2, 26.02.2020 11:27:20
ОТЛАДКА - [oscript.lib.v8runner] - КлючСоединенияСБазой /F"/tmp/z1t1ozws.g8z.tmp/v8r_TempDB"
ОТЛАДКА - [oscript.lib.v8runner] - ИмяПользователя <>
ОТЛАДКА - [oscript.lib.v8runner] - Проверяю равенство КлючСоединенияСБазой() = КлючВременногоКонтекста() и Не ВременнаяБазаСуществует()
ОТЛАДКА - [oscript.lib.v8runner] - КлючСоединенияСБазой() /F"/tmp/z1t1ozws.g8z.tmp/v8r_TempDB"
ОТЛАДКА - [oscript.lib.v8runner] - КлючВременногоКонтекста() /F"/tmp/z1t1ozws.g8z.tmp/v8r_TempDB"
ОТЛАДКА - [oscript.lib.v8runner] - ВременнаяБазаСуществует() Да
ОТЛАДКА - [oscript.lib.v8runner] - Равенство не выполняется.
ОТЛАДКА - [oscript.lib.v8runner] - "/opt/1C/v8.3/x86_64/1cv8" DESIGNER /F"/tmp/z1t1ozws.g8z.tmp/v8r_TempDB" /Out "/tmp/z1t1ozws.g8z.tmp/mzpvuery.2en.txt" /WA+ /LRU /VLRU /DisableStartupMessages /DisableStartupDialogs /ConfigurationRepositoryN "User" /ConfigurationRepositoryF "tcp://192.168.56.1/GitSync" /ConfigurationRepositoryUpdateCfg -v 2 -force
ОТЛАДКА - [oscript.lib.v8runner] - Получен код возврата 0
ОТЛАДКА - [oscript.lib.v8runner] - Это внешний файл информации: Нет
ОТЛАДКА - [oscript.lib.v8runner] - Очищать файл информации: Да
ОТЛАДКА - [oscript.lib.v8runner] - Удаляю файл информации 1С
ОТЛАДКА - [oscript.lib.v8runner] - файл информации:
Обновление конфигурации из хранилища успешно завершено

ОТЛАДКА - [oscript.lib.v8runner] - Код возврата равен 0
ОТЛАДКА - [oscript.lib.gitsync] - Каталог выгрузки </tmp/k7u40mvs.744.tmp> для версии <2>
ИНФОРМАЦИЯ - Определяю тип возможной выгрузки конфигурации в файлы
ОТЛАДКА - [o.l.g.p.increment] - Проверяю существование файла <ConfigDumpInfo.xml> в каталоге </GitSync>, файл <существует>
ОТЛАДКА - [o.l.g.p.increment] - Проверяю возможность обновления выгрузки для файла </GitSync/ConfigDumpInfo.xml>
ОТЛАДКА - [oscript.lib.v8runner] - КлючСоединенияСБазой /F"/tmp/z1t1ozws.g8z.tmp/v8r_TempDB"
ОТЛАДКА - [oscript.lib.v8runner] - ИмяПользователя <>
ОТЛАДКА - [oscript.lib.v8runner] - Проверяю равенство КлючСоединенияСБазой() = КлючВременногоКонтекста() и Не ВременнаяБазаСуществует()
ОТЛАДКА - [oscript.lib.v8runner] - КлючСоединенияСБазой() /F"/tmp/z1t1ozws.g8z.tmp/v8r_TempDB"
ОТЛАДКА - [oscript.lib.v8runner] - КлючВременногоКонтекста() /F"/tmp/z1t1ozws.g8z.tmp/v8r_TempDB"
ОТЛАДКА - [oscript.lib.v8runner] - ВременнаяБазаСуществует() Да
ОТЛАДКА - [oscript.lib.v8runner] - Равенство не выполняется.
ОТЛАДКА - [oscript.lib.v8runner] - "/opt/1C/v8.3/x86_64/1cv8" DESIGNER /F"/tmp/z1t1ozws.g8z.tmp/v8r_TempDB" /Out "/tmp/z1t1ozws.g8z.tmp/mzpvuery.2en.txt" /WA+ /LRU /VLRU /DisableStartupMessages /DisableStartupDialogs /DumpConfigToFiles "/tmp/k7u40mvs.744.tmp" -getChanges "/tmp/00ui5i9f.8wl.tmp" -configDumpInfoForChanges "/GitSync/ConfigDumpInfo.xml"
ОТЛАДКА - [oscript.lib.v8runner] - Получен код возврата 0
ОТЛАДКА - [oscript.lib.v8runner] - Это внешний файл информации: Нет
ОТЛАДКА - [oscript.lib.v8runner] - Очищать файл информации: Да
ОТЛАДКА - [oscript.lib.v8runner] - Удаляю файл информации 1С
ОТЛАДКА - [oscript.lib.v8runner] - файл информации:

ОТЛАДКА - [oscript.lib.v8runner] - Код возврата равен 0
ОТЛАДКА - [o.l.g.p.increment] - Строка проверки на возможность выгрузки конфигурации: <FULLDUMP> = <NEW:DOCU>
ОТЛАДКА - [o.l.g.p.increment] - Инкрементальная выгрузка конфигурации - ВОЗМОЖНА
ИНФОРМАЦИЯ - Тип выгрузки конфигурации в файлы: ИНКРЕМЕНТАЛЬНАЯ ВЫГРУЗКА
ОТЛАДКА - [oscript.lib.v8runner] - КлючСоединенияСБазой /F"/tmp/z1t1ozws.g8z.tmp/v8r_TempDB"
ОТЛАДКА - [oscript.lib.v8runner] - ИмяПользователя <>
ОТЛАДКА - [oscript.lib.v8runner] - Проверяю равенство КлючСоединенияСБазой() = КлючВременногоКонтекста() и Не ВременнаяБазаСуществует()
ОТЛАДКА - [oscript.lib.v8runner] - КлючСоединенияСБазой() /F"/tmp/z1t1ozws.g8z.tmp/v8r_TempDB"
ОТЛАДКА - [oscript.lib.v8runner] - КлючВременногоКонтекста() /F"/tmp/z1t1ozws.g8z.tmp/v8r_TempDB"
ОТЛАДКА - [oscript.lib.v8runner] - ВременнаяБазаСуществует() Да
ОТЛАДКА - [oscript.lib.v8runner] - Равенство не выполняется.
ОТЛАДКА - [oscript.lib.v8runner] - "/opt/1C/v8.3/x86_64/1cv8" DESIGNER /F"/tmp/z1t1ozws.g8z.tmp/v8r_TempDB" /Out "/tmp/z1t1ozws.g8z.tmp/mzpvuery.2en.txt" /WA+ /LRU /VLRU /DisableStartupMessages /DisableStartupDialogs /DumpConfigToFiles "/tmp/k7u40mvs.744.tmp" -update -configDumpInfoForChanges "/GitSync/ConfigDumpInfo.xml"
ОТЛАДКА - [oscript.lib.v8runner] - Получен код возврата 1
ОТЛАДКА - [oscript.lib.v8runner] - Это внешний файл информации: Нет
ОТЛАДКА - [oscript.lib.v8runner] - Очищать файл информации: Да
ОТЛАДКА - [oscript.lib.v8runner] - Удаляю файл информации 1С
ОТЛАДКА - [oscript.lib.v8runner] - файл информации:
Каталог /tmp/k7u40mvs.744.tmp не пуст.

_ОШИБКА - Получен ненулевой код возврата 1. Выполнение скрипта остановлено!
ОТЛАДКА - [oscript.lib.gitsync] - Откатываем файл VERSION после ошибки
ОТЛАДКА - [oscript.lib.gitsync] - ПутьКФайлуВерсий = </GitSync/VERSION>
КРИТИЧНАЯОШИБКА - {Модуль /usr/share/oscript/lib/gitsync/oscript_modules/v8runner/src/v8runner.os / Ошибка в строке: 1291 / Каталог /tmp/k7u40mvs.744.tmp не пуст._

**Comment by nixel2007** [comment]
Для начала попробуйте обновить гитсинк до последней версии :)

**Comment by Shining-Phoenix** [comment]
То что opm тянет - то и ставится)
# GitSync   
   && opm install gitsync \
   && gitsync plugins init \
   && gitsync plugins enable limit \
   && gitsync plugins enable increment \
   && gitsync plugins enable sync-remote \

**Comment by nixel2007** [comment]
Оу, пардон. был уверен, что вышла 3.1.1

> gitsync -v sync --storage-user User --storage-pwd Secret tcp://192.168.56.1/GitSync /GitSync

конфигурация лежит в корне файловой системы или все же в подкаталоге /GitSync? Если второе, то у последнего аргумента не хватает точки перед слешом

**Comment by Shining-Phoenix** [comment]
С каталогами все нормально. 
gitsync -v init --storage-user User --storage-pwd Secret tcp://192.168.56.1/GitSync /GitSync
отрабатывает корректно.

**Comment by nixel2007** [comment]
Что находится в каталоге `/tmp/k7u40mvs.744.tmp`?

Выполняется ли в терминале команда `"/opt/1C/v8.3/x86_64/1cv8" DESIGNER /F"/tmp/z1t1ozws.g8z.tmp/v8r_TempDB" /Out "/tmp/z1t1ozws.g8z.tmp/mzpvuery.2en.txt" /WA+ /LRU /VLRU /DisableStartupMessages /DisableStartupDialogs /DumpConfigToFiles "/tmp/k7u40mvs.744.tmp" -update -configDumpInfoForChanges "/GitSync/ConfigDumpInfo.xml"` ?

**Comment by Shining-Phoenix** [comment]
)))
**1.**

Папка понятна другая

КРИТИЧНАЯОШИБКА - {Модуль /usr/share/oscript/lib/gitsync/oscript_modules/v8runner/src/v8runner.os / Ошибка в строке: 1291 / Каталог /tmp/ycnqu8dy.sjv.tmp не пуст.
}
root@c6006eb4f923:/# dir /tmp/ycnqu8dy.sjv.tmp
dir: cannot access '/tmp/ycnqu8dy.sjv.tmp': No such file or directory

**2.**
Команда выполняется

**Comment by Shining-Phoenix** [comment]
Отключить
gitsync plugins disable increment

После этого выгрузка прошла нормально

**Comment by nixel2007** [comment]
Можете попробовать установить и переинициализировать набор гитсинк плагинов 1.1.1?

https://github.com/khorevaa/gitsync-plugins/releases/tag/1.1.1

**Comment by Shining-Phoenix** [comment]
Ставил поверх - не помогло.
Как правильно устанавливать?

root@c33b5181159a:/# opm install -f /opt/1C/v8.3/x86_64/conf/gitsync-plugins-1.1.1.ospx
ИНФОРМАЦИЯ - Устанавливаю пакет gitsync-plugins
ИНФОРМАЦИЯ - Установка завершена
ИНФОРМАЦИЯ - Устанавливаю зависимость: <strings> из каталога локальных зависимостей
ИНФОРМАЦИЯ - <strings> уже установлен. Пропускаем.
root@c33b5181159a:/# gitsync plugins init
ИНФОРМАЦИЯ - Начата инициализация предустановленных плагинов
ИНФОРМАЦИЯ - Устанавливаю пакет gitsync-plugins
ИНФОРМАЦИЯ - Установка завершена
ИНФОРМАЦИЯ - Устанавливаю зависимость: <strings> из каталога локальных зависимостей
ИНФОРМАЦИЯ - <strings> уже установлен. Пропускаем.
ИНФОРМАЦИЯ - Инициализация предустановленных плагинов завершена
root@c33b5181159a:/# gitsync plugins enable limit
Включен плагин: limit
root@c33b5181159a:/# gitsync plugins enable increment
Включен плагин: increment
root@c33b5181159a:/# gitsync plugins enable sync-remote
Включен плагин: sync-remote
Каталог плагинов: </root/.local/share/gitsync/plugins>
Список плагинов:
 [on] [**1.0.5**] - increment - Плагин добавляет возможность инкрементальной выгрузки в конфигурации
 [on] [1.0.5] - limit - Плагин добавляет возможность ограничения на минимальный, максимальный номер версии хранилища, а так же на лимит на количество выгружаемых версий за один запуск
 [on] [1.0.5] - sync-remote - Плагин добавляет функциональность синхронизации с удаленным репозиторием git

**Comment by nixel2007** [comment]
Он ставится не через опм, а через сам гитсинк, насколько я помню... @Khorevaa?

**Comment by khorevaa** [comment]
@Shining-Phoenix надо ставить через `gitsync p install <путькфайлу>`

**Comment by Shining-Phoenix** [comment]
Пичалька(

root@f4f335f57630:/# gitsync p install /opt/1C/v8.3/x86_64/conf/gitsync-plugins-1.1.1.ospx
КРИТИЧНАЯОШИБКА - {Модуль /usr/share/oscript/lib/gitsync/oscript_modules/opm/src/core/Классы/МенеджерПолученияПакетов.os / Ошибка в строке: 18 / Ошибка установки пакета /opt/1C/v8.3/x86_64/conf/gitsync-plugins-1.1.1.ospx: Пакет не найден}

root@f4f335f57630:/# dir /opt/1C/v8.3/x86_64/conf
conf.cfg  gitsync-plugins-1.1.1.ospx  nethasp.ini

**Comment by nixel2007** [comment]
`gitsync p install -f <путькфайлу>`

**Comment by Shining-Phoenix** [comment]
Встали но не встали)))
root@fc7014346d94:/# gitsync p install -f /opt/1C/v8.3/x86_64/conf/gitsync-plugins-1.1.1.ospx
ИНФОРМАЦИЯ - Устанавливаю пакет gitsync-plugins
ИНФОРМАЦИЯ - Установка завершена
ИНФОРМАЦИЯ - Устанавливаю зависимость: <strings> из каталога локальных зависимостей
ИНФОРМАЦИЯ - <strings> уже установлен. Пропускаем.
root@fc7014346d94:/# gitsync plugins init
ИНФОРМАЦИЯ - Начата инициализация предустановленных плагинов
ИНФОРМАЦИЯ - Устанавливаю пакет gitsync-plugins
ИНФОРМАЦИЯ - Установка завершена
ИНФОРМАЦИЯ - Устанавливаю зависимость: <strings> из каталога локальных зависимостей
ИНФОРМАЦИЯ - <strings> уже установлен. Пропускаем.
ИНФОРМАЦИЯ - Инициализация предустановленных плагинов завершена

root@fc7014346d94:/# gitsync plugins enable limit
Включен плагин: limit
root@fc7014346d94:/# gitsync plugins enable increment
Включен плагин: increment
root@fc7014346d94:/# gitsync plugins enable sync-remote
Включен плагин: sync-remote
root@fc7014346d94:/# gitsync plugins list
Каталог плагинов: </root/.local/share/gitsync/plugins>
Список плагинов:
 [on] [1.0.5] - increment - Плагин добавляет возможность инкрементальной выгрузки в конфигурации
 [on] [1.0.5] - limit - Плагин добавляет возможность ограничения на минимальный, максимальный номер версии хранилища, а так же на лимит на количество выгружаемых версий за один запуск

**Comment by Shining-Phoenix** [comment]
Кстати, развернул эту кухню под виндой - результат тот же "v8runner.os / Ошибка в строке: 1291"

**Comment by nixel2007** [comment]
По плагинам - попробуйте очистить каталог плагинов в гитсинке перед установкой

**Comment by Shining-Phoenix** [comment]
Пробовал на винде.
Очистил AppData\Local\gitsync
Не помогло

C:\WINDOWS\system32>gitsync p install -f D:\Docker1c\Docker\Ubuntu\GitSync\conf\gitsync-plugins-1.1.1.ospx
ИНФОРМАЦИЯ - Устанавливаю пакет gitsync-plugins
ИНФОРМАЦИЯ - Установка завершена
ИНФОРМАЦИЯ - Устанавливаю зависимость: <strings> из каталога локальных зависимостей
ИНФОРМАЦИЯ - <strings> уже установлен. Пропускаем.

C:\WINDOWS\system32>gitsync plugins init
ИНФОРМАЦИЯ - Начата инициализация предустановленных плагинов
ИНФОРМАЦИЯ - Устанавливаю пакет gitsync-plugins
ИНФОРМАЦИЯ - Установка завершена
ИНФОРМАЦИЯ - Устанавливаю зависимость: <strings> из каталога локальных зависимостей
ИНФОРМАЦИЯ - <strings> уже установлен. Пропускаем.
ИНФОРМАЦИЯ - Инициализация предустановленных плагинов завершена

C:\WINDOWS\system32>gitsync plugins enable limit
Включен плагин: limit

C:\WINDOWS\system32>gitsync plugins enable increment
Включен плагин: increment

C:\WINDOWS\system32>gitsync plugins enable sync-remote
Включен плагин: sync-remote

C:\WINDOWS\system32>gitsync plugins list
Каталог плагинов: <C:\Users\Loci\AppData\Local\gitsync\plugins>
Список плагинов:
 [on] [1.0.5] - increment - Плагин добавляет возможность инкрементальной выгрузки в конфигурации
 [on] [1.0.5] - limit - Плагин добавляет возможность ограничения на минимальный, максимальный номер версии хранилища, а так же на лимит на количество выгружаемых версий за один запуск
 [on] [1.0.5] - sync-remote - Плагин добавляет функциональность синхронизации с удаленным репозиторием git

**Comment by nixel2007** [comment]
@khorevaa что за магия?)

**Comment by khorevaa** [comment]
@Shining-Phoenix  инит повторно делать не надо!!!!

**Comment by Shining-Phoenix** [comment]
Пробовал на винде.
Спасибо. Плагины встали.

Ошибка осталась)))

**Comment by nixel2007** [comment]
можете попробовать выключить плагин increment?

**Comment by Shining-Phoenix** [comment]
> Отключил
> gitsync plugins disable increment
> 
> После этого выгрузка прошла нормально

Без него нормально. Ладно, на след. неделе попробую поотлаживать. Отпишусь.

**Comment by nixel2007** [comment]
Гитсинк можно запустить в режиме отладки в vscode, например. И действительно полагать отладчиком

**Comment by Shining-Phoenix** [comment]
Модуль increment.os.
Функция Функция ПроверитьВозможностьОбновленияФайловВыгрузки(Конфигуратор, Знач КаталогВыгрузки, Знач ПутьКФайлуВерсийДляСравнения = "")

В моем случае выполняется команда 
ОТЛАДКА - [oscript.lib.v8runner] - "C:\Program Files (x86)\1Cv8\8.3.16.1148\bin\1cv8.exe" DESIGNER /F"C:\Users\Loci\AppData\Local\Temp\3xludbbd.axr.tmp\v8r_TempDB" /Out "C:\Users\Loci\AppData\Local\Temp\3xludbbd.axr.tmp\xjwdwucn.piz.txt" /WA+ /LRU /VLRU /DisableStartupMessages /DisableStartupDialogs /DumpConfigToFiles "C:\Users\Loci\AppData\Local\Temp\li1guk0n.bzp.tmp" -getChanges "C:\Users\Loci\AppData\Local\Temp\dvftflld.mmx.tmp" -configDumpInfoForChanges "C:\WorkSpace\Programs\OneScript\lib\gitsync\Temp\ConfigDumpInfo.xml"

В каталоге "C:\Users\Loci\AppData\Local\Temp\li1guk0n.bzp.tmp" появляется файл "ConfigDumpInfo.xml" и потом едет попытка выгрузки конфы в этот же каталог, но там мешает этот файл.

**Comment by nixel2007** [comment]
Это странно, так как сама платформа при выгрузке смотрит на наличие файла ConfigDumpInfo.xml для высчитывания разности для инкрементальной выгрузки. Т.е. этот файл должен быть в этом каталоге.

Возможно проблема в том, что в этом же каталоге помимо этого файла должна быть вся остальная конфигурация.

**Comment by Shining-Phoenix** [comment]
Особо не разбирался с этим механизмом. Удалил это файл из папки.
Дальше выгрузка прошла нормально.
В папке появился(кроме всего прочего) файл ConfigDumpInfo.xml.

**Comment by nixel2007** [comment]
Осталось разобраться почему он там появляется или остаётся после предыдущей выгрузки

**Comment by Shining-Phoenix** [comment]
Он появляется в момент проверки ПроверитьВозможностьОбновленияФайловВыгрузки.
Нам то нужен файл дифа для проверки возможности.

А ConfigDumpInfo паровозом прилетаем, возможно на более ранних платформах поведение было другое.   

Спасибо.

В общем надо допилить чуток (@khorevaa).

**Comment by khorevaa** [comment]
@Shining-Phoenix А что пилить? :)

**Comment by Shining-Phoenix** [comment]
@khorevaa 
Модуль increment.os
Функция ПроверитьВозможностьОбновленияФайловВыгрузки

Варианты:
1. Перед выходом из функции удалять из "КаталогВыгрузки" файл ConfigDumpInfo.xml(при наличии)
2. Очищать перед выходом из функции "КаталогВыгрузки"
3. Для определения возможности обновления файла выгрузки вместо "КаталогВыгрузки"использовать другой временный каталог

**Comment by khorevaa** [comment]
@Shining-Phoenix Может и сделаешь PR? А я релиз оперативно ) А то я сейчас кодю ssh-клиента для режима агента конфигуратора

**Comment by Shining-Phoenix** [comment]
@khorevaa 

Так не хотелось)))
Ок.

**Comment by Shining-Phoenix** [comment]
@khorevaa 
Готово - https://github.com/khorevaa/gitsync-plugins/pull/38.

Если что не так - звиняйте))) - первый раз делал.

**Comment by Shining-Phoenix** [comment]
Всем спасибо. Закрываю.

**Comment by mors1eska** [comment]
@Shining-Phoenix а как получить исправления? Не нашел в релизах

**Comment by Shining-Phoenix** [comment]
@mors1eska  
Для начала попробовать установить https://github.com/khorevaa/gitsync-plugins/releases/tag/1.1.1 (gitsync p install -f <путькфайлу>) - эти изменения вроде в нем. После этого init заново не надо делать.

**Comment by mors1eska** [comment]
> @mors1eska
> Для начала попробовать установить https://github.com/khorevaa/gitsync-plugins/releases/tag/1.1.1 (gitsync p install -f <путькфайлу>) - эти изменения вроде в нем. После этого init заново не надо делать.

спасибо! Но что-то не получается

![image](https://user-images.githubusercontent.com/34914654/78459460-dacf3600-76c1-11ea-9d5d-c769a5eb7c58.png)

**Comment by Shining-Phoenix** [comment]
@mors1eska Пути надо экранировать.

**Comment by mors1eska** [comment]
> @mors1eska Пути надо экранировать.
Большое спасибо! Все получилось
