### ISSUE TITLE
А как обновить плагины?

### ISSUE THREAD

**Issue by mors1eska** [oscript-library/gitsync#240]
**Описание ошибки**
Не получается обновить плагины, т.к. не знаю как это делать.

**Сценарий воспроизведения**
делаю вот так
Файл gitsync-plugins-1.1.0.ospx в OneScript \ lib \ gitsync \ embedded_plugins и заново инициализирую плагины

Потом проверю лист плагинов
![image](https://user-images.githubusercontent.com/34914654/78454918-d2680280-76a3-11ea-918e-ca7450a95f73.png)

**Ожидаемое поведение если бы ошибки не было**
ну что они обновились =)

**Окружение:**
 - Версия операционной системы: [например Ubuntu 18.04]
 - Редакция 1С платформы [например 8.3.12.1542]
 - Версия Gitsync 3.1
 - Версия OScript 1.0.3

**Comment by Shining-Phoenix** [comment]
@mors1eska 
Надо наверное закрыть issue. Ты же уже обновился.

**Comment by mors1eska** [comment]
Да, спасибо за напоминание
