### ISSUE TITLE
Ошибка в строке: 1583 / Не задан путь к платформе 1С

### ISSUE THREAD

**Issue by Bespalov-AV** [oscript-library/gitsync#245]
При выполнении команды получаю ошибку:

```
PS C:\Git_Converter\trade> gitsync clone --storage-user BespalovAV --storage-pwd 123456 \\192.168.0.28\1C_Storage http://gitlab.tg-alterra.ru/1c/trade.git
ОШИБКА - Не удалось сформировать файл авторов
КРИТИЧНАЯОШИБКА - {Модуль C:\Program Files (x86)\OneScript\lib\gitsync\oscript_modules\v8runner\src\v8runner.os / Ошибка в строке: 1583 / Не задан путь к платформе 1С}
```
Не понимаю, где и как задать путь к платформе. Выполняю команды через консоль.

Пробовал задать переменные без результатно:
```
SET GITSYNC_V8VERSION="8.3.17.1549"
SET GITSYNC_V8_PATH="C:\Program Files\1cv8\8.3.17.1549\bin\1cv8.exe"
```
Платформа лежит по пути: C:\Program Files\1cv8\8.3.17.1549

**Окружение:**
Windows10
1С:Предприятие 8.3 (8.3.17.1549)
OScript 1.4
v8runner 1.0.5
gitsync 3.0.0

Подскажите, как сделать нужные настройки?

**Comment by nixel2007** [comment]
На последней версии гитсинка воспроизводится?

**Comment by Bespalov-AV** [comment]
Да воспроизводится:
` gitsync clone --storage-user git --storage-pwd 123 \\192.168.0.28\1C_Storage http://gitlab.tg-alterra.ru/1c/trade.git
ОШИБКА - Не удалось сформировать файл авторов
КРИТИЧНАЯОШИБКА - {Модуль C:\Program Files (x86)\OneScript\lib\gitsync\oscript_modules\v8runner\src\v8runner.os / Ошибка в строке: 1743 / Не задан путь к платформе 1`

Вот модули
`Пакет                     | Версия  | Имена серверов
----------------------------------------------------------------------------------
json                      | 1.1.1   | ОсновнойСерверПакетов, ЗапаснойСерверПакетов
vanessa-automation        | 1.2.026 | ОсновнойСерверПакетов
vanessa-runner            | 1.7.0   | ОсновнойСерверПакетов, ЗапаснойСерверПакетов
cli                       | 0.9.10  | ОсновнойСерверПакетов, ЗапаснойСерверПакетов
notify                    | 0.2.0   | ОсновнойСерверПакетов, ЗапаснойСерверПакетов
tempfiles                 | 0.2.2   | ОсновнойСерверПакетов, ЗапаснойСерверПакетов
1bdd                      | 1.10.0  | ОсновнойСерверПакетов, ЗапаснойСерверПакетов
delegate                  | 0.2.0   | ОсновнойСерверПакетов, ЗапаснойСерверПакетов
v8find                    | 0.1.2   | ОсновнойСерверПакетов, ЗапаснойСерверПакетов
logos                     | 1.2.0   | ОсновнойСерверПакетов, ЗапаснойСерверПакетов
ParserFileV8i             | 0.0.5   | ОсновнойСерверПакетов, ЗапаснойСерверПакетов
datetime                  | 0.1.0   | ОсновнойСерверПакетов, ЗапаснойСерверПакетов
vanessa-automation-single | 1.2.026 | ОсновнойСерверПакетов
strings                   | 0.4.1   | ОсновнойСерверПакетов, ЗапаснойСерверПакетов
fs                        | 0.5.0   | ОсновнойСерверПакетов, ЗапаснойСерверПакетов
fluent                    | 0.4.0   | ОсновнойСерверПакетов, ЗапаснойСерверПакетов
packman                   | 0.6     | ОсновнойСерверПакетов, ЗапаснойСерверПакетов
v8storage                 | 0.9.2   | ОсновнойСерверПакетов, ЗапаснойСерверПакетов
tool1cd                   | 0.6     | ОсновнойСерверПакетов, ЗапаснойСерверПакетов
asserts                   | 0.4.0   | ОсновнойСерверПакетов, ЗапаснойСерверПакетов
opm                       | 0.15.3  | ОсновнойСерверПакетов, ЗапаснойСерверПакетов
v8runner                  | 1.7.0   | ОсновнойСерверПакетов, ЗапаснойСерверПакетов
gitsync                   | 3.2.0   | ОсновнойСерверПакетов, ЗапаснойСерверПакетов
semver                    | 0.5.2   | ОсновнойСерверПакетов, ЗапаснойСерверПакетов
add                       | 6.0.0   | ОсновнойСерверПакетов, ЗапаснойСерверПакетов
gitrunner                 | 1.6.1   | ОсновнойСерверПакетов, ЗапаснойСерверПакетов
cmdline                   | 1.0.0   | ОсновнойСерверПакетов, ЗапаснойСерверПакетов
reflector                 | 0.5.1   | ОсновнойСерверПакетов, ЗапаснойСерверПакетов
v8unpack                  | 1.0.4   | ОсновнойСерверПакетов, ЗапаснойСерверПакетов
1commands                 | 1.5.0   | ОсновнойСерверПакетов, ЗапаснойСерверПакетов`

Я попробовал разобраться и не понимаю, как путь к платформе прокидывается в v8runner? По моему никак.

Пока из положения вышел - просто прописал в исходниках путь:
`Функция ПутьКПлатформе1С(Знач Путь = "") Экспорт
	
	Если Путь = "" Тогда
		мПутьКПлатформе1С= "C:\Program Files\1cv8\8.3.17.1549\bin\1cv8.exe";
		Возврат мПутьКПлатформе1С;
	Иначе
		ФайлПлатформы = Новый Файл(Путь);
		Если Не ФайлПлатформы.Существует() Тогда
			ВызватьИсключение "Нельзя установить несуществующий путь к платформе: " + ФайлПлатформы.ПолноеИмя;
		КонецЕсли;

		ТекЗначение = мПутьКПлатформе1С;
		мПутьКПлатформе1С = Путь;
		Возврат ТекЗначение;
	КонецЕсли;

КонецФункции`

**Comment by khorevaa** [comment]
ВЫполни команды с режимом отладки и выложи лог. `gitsync.exe -v clone ....`

**Comment by Bespalov-AV** [comment]
Я запускал отдельными командами в консоли.
Кода оформил целостный батник, то переменные заработали.

Закрываю обращение.
