### ISSUE TITLE
ПарсерОтчетаХранилища "Значение индекса выходит за пределы диапазона"

### ISSUE THREAD

**Issue by mors1eska** [oscript-library/gitsync#246]
**Описание ошибки**
Когда хочу выгрузить в гит изменения хранилища, получаю ошибку
![image](https://user-images.githubusercontent.com/34914654/93713499-086f4500-fb65-11ea-9d53-031650565e8a.png)

Ошибка стала воспроизводиться сама собой (ранее не воспроизводилась)

**Сценарий воспроизведения**
Команда обычная
cmd("gitsync sync --push --storage-user ${hranuser} --storage-pwd=${hranpwd} ${REPO} ${REPO_git}")

**Окружение:**
 - Редакция 1С платформы 8.3.13.1644
 - Версия Gitsync 3.0.1
 - Версия OScript [например 1.4.0.177]

**Comment by nixel2007** [comment]
Обновите гитсинк, эта ошибка уже исправлена

**Comment by nixel2007** [comment]
У вас в логах видно, что используется 8.3.17, а не 8.3.13
