### ISSUE TITLE
Происходит выход из скрипта после gitsync sync

### ISSUE THREAD

**Issue by Bespalov-AV** [oscript-library/gitsync#247]
Выполняю следующий скрит из bat файла.
```
gitsync sync ...
cd conf
git push
```
но после команды gitsync sync происходит выход из скрипта т.е. не выполняется git push.

Это нормальное поведение? Как правильно организовать работу чтобы, после синхронизации выполнялся git push?

bat файл будет запускаться ежедневно по шедуллеру.

**Comment by abirambul** [comment]
В bat нужно 
```cmd
call gitsync sync
```

**Comment by Bespalov-AV** [comment]
Спасибо!
