### ISSUE TITLE
Проблема с реквизитом УФ Планировщик

### ISSUE THREAD

**Issue by lazarevg** [oscript-library/gitsync#249]
**Ежедневно выгружаются изменения по реквизиту формы Планировщик**
При первой за день выгрузке в git выгружаются изменения по реквизиту УФ Планировщик.
Меняется это место:

```xml

<Attribute name="Планировщик" id="46">
	...
	<Settings xmlns:pl="http://v8.1c.ru/8.3/data/planner" xsi:type="pl:Planner">
		...
		<pl:period>
			<pl:begin>2020-11-23T00:00:00</pl:begin>
			<pl:end>2020-11-23T23:59:59</pl:end>
		</pl:period>
		...
	</Settings>
</Attribute>
```

Так понимаю 1С при выгрузке в файлы подставляет текущую дату. Можно как-то это обойти?

**Окружение:**
 - Версия операционной системы: Windows Server 2008 R2
 - Редакция 1С платформы: 8.3.15.1656
 - Версия Gitsync: 3.1.0
 - Версия OScript: 1.4.0.177

**Comment by nixel2007** [comment]
Это надо писать на v8/обновляться на последнюю версию платформы. Сама платформа постоянно меняет реквизиты планировщика.

**Comment by EvilBeaver** [comment]
Можно написать прекоммит хук, но это будет именно кастомный обход бага платформы. Готового решения нет

**Comment by lazarevg** [comment]
> Можно написать прекоммит хук, но это будет именно кастомный обход бага платформы. Готового решения нет

Понятно что бага (или фича) платформы. Собственно с целью поиска обходного пути сюда и написал.
А где можно подробнее узнать про "прекоммит хук"? Или примеры посмотреть?

**Comment by EvilBeaver** [comment]
https://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks

https://www.hostinger.ru/rukovodstva/kak-ispolzovat-git-hooks/

https://hub.oscript.io/packages/search?text=precommit

**Comment by EvilBeaver** [comment]
Еще актуально?

**Comment by lazarevg** [comment]
Реже, но прилетает изменение формы. Ишью можно закрыть.
