### ISSUE TITLE
Несколько вопросов по работе gitsync

### ISSUE THREAD

**Issue by linuxbuh** [oscript-library/gitsync#258]
Подскажите как решаются вопросы в gitsync:
1)	Привязка кода к задаче
2)	Создание веток 
3)	Хранение кода расширений, внешних обработок, внешних отчетов
4)	Возможность разрабатывать без блокировки объектов базы
5)	Хранения нескольких вариантов кода у разработчика

**Comment by nixel2007** [comment]
1. Никак, это задача гит-сервера. Если вы будете писать комментарии в хранилище по формату, в котором работает ваш гит-сервер, то задачи будут линковаться.
2. Никак.
3. Расширения хранить можно (если они лежат в хранилище). Отчёты и обработки - нет. Для этого есть инструменты типа precommit4onec, precommit1c и vanessa-runner
4. Гитсинк про синхронизацию хранилища, а не про разработку.
5. Это тоже не задача гит-синка. Можете иметь несколько веток в гите, можете иметь несколько выгрузок в разные каталоги, на ваш вкус.
