### ISSUE TITLE
Обновить readme.md

### ISSUE THREAD

**Issue by GladilovDmitry** [oscript-library/gitsync#260]
Как я понял, фактически проект перезалит из ветки участника, активно перепилившего его. Но к сожалению документация не обновлена, начиная с первых фраз [файла](https://github.com/oscript-library/gitsync/blob/master/readme.md)
> "Возможно данный проект примут как следующую версию в gitsync
> Проект является форком проекта gitsync см. https://github.com/oscript-library/gitsync и результатом глубокого рефакторинга начального проекта"

 и так далее, включая например ссылки на репозиторий того автора, а не на oscript-library.

Необходимо обновить всю документацию, убрав описания вида "это форк проекта" и изменить все ссылки.

**Comment by EvilBeaver** [comment]
Тут немного не такая организация. oscript-libray это не первичное хранилище, а наоборот - набор форков от разных авторов. Проекты разрабатываются у авторов, публикуются авторами в хаб. Библиотека oscript-library это комьюнити-форки для удобства поиска и регулировки прав доступа на публикацию в хабе.

поэтому - более свежий код именно у автора, а не в форке внутри library. Ссылки валидны на репозиторий автора.
