### ISSUE TITLE
Метод объекта не обнаружен (ДобавитьКоманду)

### ISSUE THREAD

**Issue by slaxxals** [oscript-library/gitsync#27]
После установки OScript 1.0.15.260, выполнение команды
gitsync с параметрами init или export приводит к ошибке:

ОШИБКА - {Модуль C:\Program Files (x86)\OneScript\lib\gitsync\src\core\Классы\МенеджерСинхронизации.os / Ошибка в строке: 830 / Метод объекта не обнаружен (ДобавитьКоманду)}

Ошибка появлялась везде, где вызывался метод ДобавитьКоманду у объекта КомандныйФайл.

Проблема была решена локально удалением файла OneScript\lib\gitsync\src\core\Классы\КоммандныйФайл.os
(спасибо @asosnoviy)

**Comment by nixel2007** [comment]
Проблема больше относится к opm - он не почистил за собой классы, отсутствующие в новой версии библиотеки.

**Comment by asosnoviy** [comment]
Проверил, действительно в gitsync-0.5 и 1.1 идет свой КомандныйФайл.os,  а в 1.2 его уже нет и используется 1commands. При установке opm его не удаляет.

**Comment by asosnoviy** [comment]
Есть предложение на время положить КомандныйФайл.os из 1commands в src gitsync'а

**Comment by nixel2007** [comment]
Боюсь, будет ошибка инициализации классов. 
Можешь проверить?

**Comment by asosnoviy** [comment]
Проверил. С копией КомандныйФайл.os из 1commands работает нормально.

**Comment by nixel2007** [comment]
Пулл-реквест с оттестированной версией? :) 
Выпущу апдейт (только вероятно уже утром)

**Comment by asosnoviy** [comment]
а тесты не падают...

**Comment by asosnoviy** [comment]
Нашел способ изящнее. 
Прописать ```#Использовать 1commands``` в gytsync.os тогда 1commands заинитится до файла из core

**Comment by artbear** [comment]
> `#Использовать 1commands`

И это правильно.

**Comment by nixel2007** [comment]
Где ~пруффы~ пулл-реквесты, Билли?

**Comment by artbear** [comment]
Возврат к старой версии КомандныйФайл считаю некорректным

**Comment by nixel2007** [comment]
Да импорт нужен, импорт. Не у компа, не могу собрать)
