### ISSUE TITLE
Ошибка выполнения команды gitsync init на платформе 8.2

### ISSUE THREAD

**Issue by dentaky** [oscript-library/gitsync#276]
**Описание ошибки**
При попытке инициализировать репо в каталоге src на платформе 8.2 создается пустой файл authors, а должен создаваться с заполненными авторами хранилища.

**Сценарий воспроизведения**
Шаги по воспроизведению:
1. Открыть 'cmd'
2. Нажать 'gitsync --v8version 8.2.19.130 init --storage-user user --storage-pwd pwd tcp://address C:\hran'
3. Выполнить команду.
4. В каталоге создадутся пустые файлы authors и version.

**Ожидаемое поведение если бы ошибки не было**
'Файл авторов должен быть заполнен данными из хранилища'

**Скриншоты**
![image](https://user-images.githubusercontent.com/87470211/131812727-3a8eaf9b-90c0-466e-a28b-e6d49bfad2ab.png)

**Окружение:**
 - Версия операционной системы: Windows 10.
 - Редакция 1С платформы 8.2.19.130
 - Версия Gitsync 3.4.0
 - Версия OScript 1.6.0.213

Плагин tool1CD включен. По идее с помощью него должна конфигурация выгружаться в виде исходных файлов.

**Comment by nixel2007** [comment]
При обращении к хранилищу через tcp плагин tool1cd не используется. он умеет работать только по прямому доступу к хранилишу.

**Comment by dentaky** [comment]
Про плагин зря написал, это я уже sync пытаюсь сделать и к текущей проблеме не относится. 
Проблема всё равно актуальна для команды init, по tcp не работает на 8.2. корректно создание файла authors.

**Comment by asosnoviy** [comment]
Для 8.2 используйте плагин и файловый доступ. 8.2 не поддерживает иерархическую выгрузку и половину пакетных ключей.

**Comment by dentaky** [comment]
> Для 8.2 используйте плагин и файловый доступ. 8.2 не поддерживает иерархическую выгрузку и половину пакетных ключей.

Да, так и делаю. Т.е. на 8.2. про стандартную выгрузку можно забыть.
