### ISSUE TITLE
Лишние CRLF

### ISSUE THREAD

**Issue by nagdevops2** [oscript-library/gitsync#283]
**Добавляет лишний перевод строки**
Выгружает файлы из хранилища в таком виде:
![image](https://user-images.githubusercontent.com/82443902/134208168-c4a10f5a-6983-449f-8638-df51839b2869.png)

Оригинал в конфигураторе:
![image](https://user-images.githubusercontent.com/82443902/134208318-67d697d0-f17c-4153-af6e-7eb9e15c794d.png)

**Окружение:**
 - Версия операционной системы: Windows Server 2019std
 - Редакция 1С платформы [например 8.3.18.1334]
 - Версия Gitsync [например 3.4.0]
 - Версия OScript [например 1.5.0.178]

**Дополнительный контекст**

Конфигурация УТ10 дописанная

**Comment by nagdevops2** [comment]
в конфигурации git пробовал менять параметр core.autocrlf , пока не помогло

**Comment by nixel2007** [comment]
Попробуйте скопировать модуль из конфигуратора в текстовый редактор. Скорее всего конфы строк побиты прямо в конфигурации. гитсинк сам по себе ничего не делает с файлами, ему их выгружает конфигуратор

**Comment by nagdevops2** [comment]
Последовательность действий:
В пустой каталог сделал init:
gitsync init -u user -p password tcp://1c-server:1742/Configuration_Store_Trade e:\temp\1

Конфигурация git:
$ git config -l
diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
http.sslbackend=openssl
http.sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
core.autocrlf=false
core.fscache=true
core.symlinks=false
pull.rebase=false
credential.helper=manager-core
credential.https://dev.azure.com.usehttppath=true
init.defaultbranch=master
gui.recentrepo=E:/add-tests/vanessa-behavoir
gui.recentrepo=E:/add-tests/vanessa-runner
http.sslverify=false
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true

Синхронизация:
gitsync sync -u user -p user --minversion 12282 tcp://1c-server:1742/Configuration_Store_Trade e:\temp\1

Результат тот же.

**Comment by nixel2007** [comment]
А если текст, вставленный в редактор, повторно скопировать и перенести в Конфигуратор - следующая выгрузка будет с лишними переносами или поправится?

**Comment by nagdevops2** [comment]
> А если текст, вставленный в редактор, повторно скопировать и перенести в Конфигуратор - следующая выгрузка будет с лишними переносами или поправится?

Это пример с прод базы, но попробую на копии.

**Comment by nagdevops2** [comment]
> А если текст, вставленный в редактор, повторно скопировать и перенести в Конфигуратор - следующая выгрузка будет с лишними переносами или поправится?

Да, поправилось.

**Comment by nixel2007** [comment]
Значит, текст побит в самой конфигурации :)

**Comment by nagdevops2** [comment]
Выходит так, спасибо за помощь.

**Comment by AdapterBatareev** [comment]
не совсем так. Описанная выше проблема остается при использовании плагина unpack form. В конфигураторе вручную поменял разделители на CRLF, по после unpack кое где остается CR. 
Из за этого sonar не может правильно определить blame по файлу

>>в конфигурации git пробовал менять параметр core.autocrlf , пока не помогло
git меняет LF на CRLF, CR менять на CRLF git не будет. Это наследие старых платформ 1С, а не проблема git
