### ISSUE TITLE
Ошибка при определении авторов по файлу authors

### ISSUE THREAD

**Issue by Segate-ekb** [oscript-library/gitsync#285]
**Описание ошибки**
В случае если имя пользователя хранилища оканчивается пробелом его определение в файле authors не происходит
![image](https://user-images.githubusercontent.com/80944823/144047008-64993ab9-aac2-469a-8523-c99057016294.png)
Выдержка из authors:
![image](https://user-images.githubusercontent.com/80944823/144047088-be384553-e51f-40b5-a9ee-0ee03648cb1c.png)

**Менеджерсинхронизации.os>ПрочитатьФайлАвторов**
![image](https://user-images.githubusercontent.com/80944823/144050740-1a4baf31-c062-4699-b7f0-bcb1dafdf09d.png)
**Менеджерсинхронизации.os>ДополнитьТаблицуВерсийИменамиАвторов**
![image](https://user-images.githubusercontent.com/80944823/144050993-447d0569-008b-485f-8589-eda48fb65727.png)

**Сценарий воспроизведения**
Шаги по воспроизведению:
1. Создать пользователя в хранилище добавить пробел в конце
2. Запустить gitsync init
3. Сделать коммит под пользователем
4. Запустить gitsync sync. Получить сообщение об ошибке 

**Ожидаемое поведение если бы ошибки не было**
Версия должна найтись корректно

**Окружение:**
 - Версия операционной системы: [Ubuntu 18.04]
 - Редакция 1С платформы [например 8.3.15.1656]
 - Версия Gitsync [3.4.0]
 - Версия OScript [Version 1.7.0.214]

**Comment by EvilBeaver** [comment]
Закрываю, т.к. влит PR
