### ISSUE TITLE
Неявное изменение пути к файлу VERSION

### ISSUE THREAD

**Issue by freewms** [oscript-library/gitsync#289]
**Описание ошибки**
Неявное изменение пути с файлом VERSION относительно пути, заданного в переменной `$GITSYNC_WORKDIR`.
```
ОТЛАДКА - [oscript.app.gitsync] - КаталогРабочейКопии = /home/gitlab-runner/builds/nUSV9aSc/0/1c/test_repo/cf
```
```
КРИТИЧНАЯОШИБКА - [oscript.app.gitsync] - {Модуль /usr/share/oscript/lib/gitsync/src/core/Классы/МенеджерСинхронизации.os / Ошибка в строке: 1436 / Файл с версией ГИТ </home/gitlab-runner/builds/nUSV9aSc/0/1c/test_repo/cf/src/VERSION> не существует}
```
```
find /home/gitlab-runner/builds/nUSV9aSc/0/1c/test_repo -iname VERSION
/home/gitlab-runner/builds/nUSV9aSc/0/1c/test_repo/cf/VERSION
```

**Сценарий воспроизведения**
Шаги по воспроизведению:
1. Поместить файл VERSION непосредственно в директорию, заданную в переменной `$GITSYNC_WORKDIR`
2. Убедится в отсутствии файла VERSION в директории `$GITSYNC_WORKDIR/src`
3. Выполнить `gitsync s`

**Ожидаемое поведение если бы ошибки не было**
Расположение файла непосредственно в `$GITSYNC_WORKDIR` не вызывало бы ошибки

**Окружение:**
 - Версия операционной системы: Debian 11.2
 - Редакция 1С платформы: 8.3.20.1710
 - Версия Gitsync 3.4.0
 - Версия OScript 1.7.0.214

**Comment by nixel2007** [comment]
Какие плагины активированы?

**Comment by asosnoviy** [comment]
https://github.com/khorevaa/gitsync-plugins/issues/53

**Comment by freewms** [comment]
> Вангую автоопределение src при активированном едт плагине

так и есть.

**Comment by asosnoviy** [comment]
@freewms  тогда надо больше вводных. Например структура проекта. Из описания ошибки, явной ошибки не вижу. При init файл version где создается?
