### ISSUE TITLE
Ссылки в коммите

### ISSUE THREAD

**Issue by megodeath** [oscript-library/gitsync#291]
При импорте версии хранилища вида: 
![image](https://user-images.githubusercontent.com/14245563/173382058-ffef5a70-2d12-473d-bc67-cadd9639436f.png)
получаем коммит с комментарием вида:
![image](https://user-images.githubusercontent.com/14245563/173382433-73ba20f3-2590-4618-ba90-92683fba1a43.png)

Ссылки http в комментариях обрезаются до названия протокола

 - Версия Gitsync 3.4.0
 - Версия OScript 1.7.0.214
 - 1с 8.3.12.1529

**Comment by abirambul** [comment]
Какую версию платформы используете?

В версии платформы 8.3.17 исправили эту ошибку https://github.com/oscript-library/gitsync/issues/162

**Comment by leemuar** [comment]
Это особенность платформы, которую нельзя было отключить до версии 8.3.17

**Comment by megodeath** [comment]
8.3.12.1529
