### ISSUE TITLE
Установка gitsync / ПодключениеПлагиновКаталога.os / Ошибка в строке: 73

### ISSUE THREAD

**Issue by cervantesramis** [oscript-library/gitsync#297]
**Описание ошибки**
После установки gitsync с помощью команды opm install gitsync c правами админа, не могу вывести справку по командам
![image](https://user-images.githubusercontent.com/46556875/185354207-501d92c3-119c-4d5d-916c-752ce609238c.png)

**Сценарий воспроизведения**
Шаги по воспроизведению:
1. В 'cmd' ввожу 'gitsync'
2. {Модуль C:\Program Files\OneScript\lib\gitsync\src\core\Классы\internal\Классы\ПодключениеПлагиновКаталога.os / Ошибка в строке: 73 / Внешнее исключение (System.Reflection.TargetInvocationException): Адресат вызова создал исключение.}

**Ожидаемое поведение если бы ошибки не было**
'Вывод справки по командам'

**Окружение:**
 - Windows server 2016
 - Платформа 8.3.19.1150 
 - Версия Gitsync 3.5.2
 - Версия OScript 1.7.0.214

**Дополнительный контекст**
Пытался устанавливать пакет вручную (3.5.1 и 3.4.1) - результат такой же.
![image](https://user-images.githubusercontent.com/46556875/185366041-a737a06a-869c-486c-9a5f-dad0dde33d1a.png)

Читал в схожих issue, что необходимо произвести маниуляции в пользовательской папке appdata \ local \ gitsync, но подобной папки у меня нет после установки.

**Comment by cervantesramis** [comment]
Решилось следующим образом:
Так как .NET стоял версии 4.8, то установил oscript версии 1.8 
Далее ещё раз запустил установку gitsync.
При вводе команды gitsync опять поймал ошибку, но другую:

> 
> {Модуль C:\Program Files\OneScript\lib\gitsync\src\core\Классы\internal\Классы\ПодключениеПлагиновКаталога.os / Ошибка в строке: 73 / Внешнее исключение (OneScript.Language.SyntaxErrorException): {Модуль D:\gitsync\plugins\gitsync-plugins\src\Классы\smartTags.os / Ошибка в строке: 261,1 / Ожидается завершение директивы препроцессора #Область}
> }

Ошибку решил добавлением #КонецОбласти в файл.

**Comment by EvilBeaver** [comment]
Ошибка с КонецОбласти была исправлена в gitsync и если его обновить, то это изменения там уже будет
