### ISSUE TITLE
Ошибка на linux при входе через ssh

### ISSUE THREAD

**Issue by ksv87** [oscript-library/gitsync#298]
**Описание ошибки**
```
ОШИБКА - Получен ненулевой код возврата 128. Выполнение скрипта остановлено!
ОШИБКА - *** Unable to initialize GTK+ or connect to the windowing system. Is DISPLAY set properly?
ОШИБКА - Не удалось сформировать файл авторов
КРИТИЧНАЯОШИБКА - {Модуль /usr/share/oscript/lib/gitsync/oscript_modules/v8runner/src/v8runner.os / Ошибка в строке: 1179 / Информации об ошибке нет}
```

**Сценарий воспроизведения**
Шаги по воспроизведению:
1. зайти на сервер linux по ssh
2. запустить команду `gitsync init --storage-user user --storage-pwd pass tcp://192.168.113.209/path /opt/gitsync/localpath`

**Ожидаемое поведение если бы ошибки не было**
Команда создаст новый репозиторий (каталог) .git в каталоге /opt/gitsync/localpath, и наполнит его служебными файлами VERSION и AUTHORS.

**Окружение:**
 - Версия операционной системы: Astra Linux 1.7.2
 - Редакция 1С платформы 8.3.21.1393
 - Версия Gitsync 3.4.0
 - Версия OScript 1.8.3.2

**Дополнительный контекст**
если зайти по rdp и в терминале выполнить туже самую команду `gitsync init --storage-user user --storage-pwd pass tcp://192.168.113.209/path /opt/gitsync/localpath` она срабатывает выдав несколько ошибок
```
ОШИБКА - Получен ненулевой код возврата 128. Выполнение скрипта остановлено!
ОШИБКА - (1cv8:17984): Gtk-WARNING **: 12:26:38.327: Theme parsing error: gtk.css:3877:13: Not using units is deprecated. Assuming 'px'.
ОШИБКА - (1cv8:18021): Gtk-WARNING **: 12:26:41.538: Theme parsing error: gtk.css:3877:13: Not using units is deprecated. Assuming 'px'.
ИНФОРМАЦИЯ - Инициализация завершена
```

**Comment by nixel2007** [comment]
Для работы 1с нужны полноценные подняты иксы. Без них никак.

**Comment by ksv87** [comment]
Если на сервере установлены GUI, можно как то в cron настроить запуск gitsync?

**Comment by nixel2007** [comment]
Можно, если поднять в той же сессии иксы :)

**Comment by ksv87** [comment]
а примера нет?

**Comment by nixel2007** [comment]
Попробуйте вызвать startx или xstart

**Comment by ksv87** [comment]
разобрался, спс
