### ISSUE TITLE
Ошибка "Получен ненулевой код возврата 1. Выполнение скрипта остановлено!"

### ISSUE THREAD

**Issue by deevil** [oscript-library/gitsync#31]
При экспорте хранилища появляется ошибка 
Получен ненулевой код возврата 1. Выполнение скрипта остановлено!

При этом в git попадает только часть конфигурации
Лог и текст самой ошибке нигде нет...

**Comment by EvilBeaver** [comment]
Приведите кусочек лога до ошибки и саму ошибку

**Comment by deevil** [comment]
Уже разобрался.
1с при выгрузке конфигурации в файлы вылетала из-за ключа.
Ключ -verbose сразу не нашел...

При этом версия перемещалась на следующую версию и версия считалась обработанной.
Это стоит обработать...

**Comment by deevil** [comment]
@artbear то что при таком сценарии скрипт завершает работу с переходом на сл. версию - это не баг?

**Comment by EvilBeaver** [comment]
Насколько я помню, там стоит обработка ошибки и если платформа упала, то этот файл откатывается назад.
