### ISSUE TITLE
Сыпет предупреждениями про лямбды при запуске

### ISSUE THREAD

**Issue by EvilBeaver** [oscript-library/gitsync#311]
**Описание ошибки**

При запуске gitcync --help пишет какие-то предупреждения про лямбды и про то, что перестанет работать в будущей версии

**Сценарий воспроизведения**

```
gitsync --help
```

**Ожидаемое поведение если бы ошибки не было**

Выводит полезную справку и не пугает человека, который хочет справку. Скорее всего, этот человек новичок, он хочет документацию, а ему в лицо кидают матерные слова про лямбды. Он понимает, что это приложение сырое, опенсорс говно и ничего не работает. Расстраивается и уходит клепать печатные формы вместо постижения девопса.

**Скриншоты**

![image](https://github.com/oscript-library/gitsync/assets/2657561/37473ba1-8ae1-41d8-bfdc-22a47db51b78)

**Окружение:**

любое

**Дополнительный контекст**

Кажется, это виновата библиотека fluent

**Comment by AnanyevAl** [comment]
При даунгрейде fluent до версии 0.4.0 предупреждения пропадают.
