### ISSUE TITLE
Ошибка выгрузки из хранилища

### ISSUE THREAD

**Issue by EuLeEr** [oscript-library/gitsync#314]
**Описание ошибки**
что конкретно происходит
gitsync init --storage-user Администратор --storage-pwd "" F:\Base1C\Hran\test1 F:\1CGitProject\scr
ОШИБКА - Получен ненулевой код возврата 128. Сообщение: `fatal: not a git repository (or any of the parent directories): .git
`
ОШИБКА - Получен ненулевой код возврата 1. Выполнение скрипта остановлено!
ОШИБКА - Не удалось сформировать файл авторов
КРИТИЧНАЯОШИБКА - {Модуль F:\Program Files\OneScript\lib\gitsync\oscript_modules\v8runner\src\v8runner.os / Ошибка в строке: 1544 / Хранилище конфигурации по адресу:
F:\1CGitProject\scr
не обнаружено.
}
**Сценарий воспроизведения**
Шаги по воспроизведению:
1. Открыть терминал windows 11

2. Запустить команду gitsync init --storage-user Администратор --storage-pwd "" F:\Base1C\Hran\test1 F:\1CGitProject\scr
3. Ошибка 1  выдается , но git иницализируется.
4. Ошибка 2 (на строке 1544)остается навсегда . При этом в папке F:\1CGitProject\scr создается файл 1cv8ddb.1CD.cfl
5. Опробовано с повышением привилегий тоже

В конечном итоге выгрузка не проходит.

**Окружение:**
 - Версия операционной системы: Windows 11 Home
 - Редакция 1С платформы  8.3.24.1342
 - Версия Gitsync 3.6.0
 - Версия OScript  1.9.0.6

**Дополнительный контекст**
Простая созданная руками конфигурация из двух справочников, документа и регистра сведений
Пользователей у базы совсем нет. У хранилища видно из строки

**Comment by nixel2007** [comment]
уберите --storage-pwd ""

**Comment by EuLeEr** [comment]
Да, вчера без ключа --storage-pwd - отказывался подключатся к хранилищу.
Сегодня - подключился
