### ISSUE TITLE
Параметр остановки выгрузки при пустом комментарии в хранилище

### ISSUE THREAD

**Issue by asosnoviy** [oscript-library/gitsync#32]
Хочу останавливать выгрузку, когда несознательный кодер не прокомментировал помещение в хранилище. О чем сигнализировать и с  CI отправлять гневное письмо.

**Comment by asosnoviy** [comment]
assign to me plz.

**Comment by artbear** [comment]
ИМХО здесь лучше юзать хук гита `commit-msg`, который как и обрабатывает сообщение коммита и может как проверять коммит, так и менять его.
А в гитсинк оставить чистую выгрузку исходников.

**Comment by artbear** [comment]
Хотя можно добавить спец.команду гитсинк для анализа сообщения коммита и устанавливать вызов этой команды в хуке `commit-msg`

ИМХО так лучше.

**Comment by artbear** [comment]
Выполнено в #67
