### ISSUE TITLE
При прерывании синхронизации пропускает версию

### ISSUE THREAD

**Issue by shureek** [oscript-library/gitsync#38]
Экспорт каждой версии состоит из:
1. Выгрузка очередной версии конфигурации из хранилища
2. Создании ИБ
3. Загрузки конфигурации в ИБ
4. Выгрузки конфигурации в файлы
5. git add
6. git commit

Если прервать экспорта версии №80 на шаге 3, а потом запустить снова, то он начнёт выгружать версию №81, версия 80 пропускается.

**Comment by ret-Phoenix** [comment]
и это правильно, раз прервали выгрузку - откатывайте ее. т.к. уже установлено что 80 выгружено.
Это не фича gitsync, это обычное поведение любой системы контроля версий.

**Comment by EvilBeaver** [comment]
Если выгрузка отвалилась после того, как уже установили версию в versions то там есть код отката к предыдущему. Но он не всегда наверное выполняется, надо смотреть.

**Comment by ret-Phoenix** [comment]
пока не сделан коммит - реверт и все хорошо,

**Comment by demidych** [comment]
Насколько помню там очень рано меняется VERSION (перед п.1?)
Лучше его менять как можно позже (перед п.4), чтобы сократить количество случаев, когда надо делать "реверт"

**Comment by shureek** [comment]
Сейчас произошла ошибка на этапе хуков прекоммита. После неё gitsync откатил VERSIONS.
Т. е. он её откатывает, если ВИДИТ, что где-то произошла ошибка. Но если снять задачу gitsync'а, то он, естественно, не может откатить версию.
Думаю, лучше этот файл менять непосредственно перед коммитом, не раньше.

**Comment by shureek** [comment]
Учтено в 662f70bf
