### ISSUE TITLE
Tool_1CD вернул код: 2

### ISSUE THREAD

**Issue by alehinsasha** [oscript-library/gitsync#39]
@awa15 

Платформа: 8.3.10.1877
Конфигурация: СППР 1.1
Режим совместимости: 8.3.8

Команда `gitsync export` прерывается ошибкой:

`{Модуль C:\Program Files (x86)\OneScript\lib\tool1cd\table-reader.os / Ошибка в строке: 46 / Tool_1CD вернул код: 2`}

![2017-02-09_14-29-41](https://cloud.githubusercontent.com/assets/8247178/22781700/b9029288-eed4-11e6-9c9b-67bedca40c63.png)

**Comment by EvilBeaver** [comment]
Код 2 это "Файл не найден" обычно. Пути точно указаны?

**Comment by alehinsasha** [comment]
Удалось решить так: скачал [отсюда](https://bitbucket.org/awa15/tool_1cd/src) файл `cTool_1CD.exe` и положил его (с заменой) в `OneScript\lib\tool1cd\bin`. Спасибо @demidych

**Comment by artbear** [comment]
Исправлено в 2.0
