### ISSUE TITLE
Нельзя управлять параметром `КоличествоКоммитовДоPush`

### ISSUE THREAD

**Issue by artbear** [oscript-library/gitsync#40]
В коде есть использование параметра `КоличествоКоммитовДоPush`
Но через командную строку нельзя управлять этим параметров.
В команде `sync` явно указывается `КоличествоКоммитовДоPush = 0`

Ни в исходном PR #11 ни в новом #37 этого нет.

@Khorevaa Посмотришь как автор обоих коммитов?

**Comment by Khorevaa** [comment]
Да посмотрю.

**Comment by Khorevaa** [comment]
Сделал RP в текущий PR рефакторинга.. 
https://github.com/bia-tech/gitsync/pull/4

**Comment by artbear** [comment]
Окончательно реализовано в #37

**Comment by artbear** [comment]
@Khorevaa Добавь, плиз, доку об этом параметре.

**Comment by artbear** [comment]
Выполнено еще в 2.2.0 или даже раньше
