### ISSUE TITLE
Зависание на последних релизах gitsync

### ISSUE THREAD

**Issue by artbear** [oscript-library/gitsync#41]
Исходная задача https://github.com/artbear/1commands/issues/14

Предлагаю:
- [ ] Проверять параметр core.autocrlf для текущего репо
- [ ] Если он задан в true, 
+ сообщать об этом 
+ отключить немедленный вывод командного файла при выполнении коммита
- [ ] Если он задан в другое значение, то ничего не делать

- [ ] Документировать подобное поведение

**Comment by artbear** [comment]
До последних релизов вывод от команд гита мы получали после завершении работы команды.
В последних релизах стали получать вывод сразу в процессе выполнения команды, до ее завершения.
При включенном параметре `core.autocrlf = true` подобный немедленный вывод из-за ошибки движка https://github.com/EvilBeaver/OneScript/issues/402 вызывает зависание

**Comment by EvilBeaver** [comment]
Чо ошибки то сразу? Просто сделано было неточно. Кстати эта задача теряет актуальность для 1.0.16

**Comment by artbear** [comment]
Как я уже отметил в https://github.com/EvilBeaver/OneScript/issues/402#issuecomment-279316147
проблема в движке еще не решена :(

**Comment by EvilBeaver** [comment]
Решена. Писать надо по другому. Я просто еще не знаю как )

**Comment by artbear** [comment]
Ты не умничай, ты рукой покажи :)
Ишуз https://github.com/EvilBeaver/OneScript/issues/402 переоткрывай

**Comment by artbear** [comment]
Исправлено зависание
