### ISSUE TITLE
Возможность переопределения части функционала (создание плагинов)

### ISSUE THREAD

**Issue by khorevaa** [oscript-library/gitsync#43]
Предлагаю, добавить возможность переопределения вследующих функций (возможностей)

- [x] 1. Переопределение коммита (перед коммитом, после коммита, вместо)
- [ ] 2. Переопределение процедуры чтения из файла authors. (перед чтением, после чтения, вместо)
- [ ] 2. Переопределение процедуры чтения из файла version. (перед чтением, после чтения, вместо)
- [x] 3. Переопределение пуша в url (перед, после , вместо)
 4 Добавить: 
- [x] перед (после, вместо) чтение версии из хранилища.
- [x] перед (после, вместо) выгрузки cf в исходников.
- [x] перед (после) запуском приложения.

**Comment by EvilBeaver** [comment]
По пп. 1-3 нужно подглядеть у 1С. 

    ПередКоммитом(Знач ТекстКоммита, СтандартнаяОбработка, Отказ)
    ПриПолученииАвторов(ТаблицаАвторов, СтандартнаяОбработка) // если СО=Ложь в таблице вернуть авторов. На входе - Авторы из стандартного чтения.

И сразу в одном обработчике - и вместо и после и перед. Как-то так.

**Comment by artbear** [comment]
@Khorevaa Добавишь ПР на эту тему? 

рассмотрю оперативно на этот раз :)

**Comment by KvestIn** [comment]
1-3 пункт имеет смысл. 4 - пока не понимаю зачем. На мой взгляд, 4 - это основной функционал, который переопределять не надо.

**Comment by khorevaa** [comment]
Сделано
