### ISSUE TITLE
gitsync all Ошибка в строке: 46

### ISSUE THREAD

**Issue by AlexStrizh** [oscript-library/gitsync#47]
Вызывается исключение при запуске с параметром all:
20.02.2017 23:43:47: ОШИБКА - {Модуль C:\Program Files (x86)\OneScript\lib\tool1cd\table-reader.os / Ошибка в строке: 46 / Tool_1CD вернул код: 2}

Вот xml:
```
<gitsync-options>
	<global>
		<email-domain>xxx@mail.ru</email-domain>
		<v8-version>8.3.9.2170</v8-version>
		<git-executable>git</git-executable>
	</global>
	<repositories>
		<repo name="xxx">
			<git-local-path>E:\v8_repo\xxx\src\config</git-local-path>
			<git-remote>https://xxx@bitbucket.org/xxx/xxx.git</git-remote>
			<v8-storage-dir>E:\v8_repo\xxx\src\Репозиторий</v8-storage-dir>
			<email-domain/>
			<v8-version/>
			<git-executable/>
		</repo>
	</repositories>
</gitsync-options>
```

При этом gitsync отлично отрабатывает с этим же хранилищем, если без all. Подскажите, где ошибка в файле настроек? То, что файл хранилища не держится другими процессами - это точно.

**Comment by artbear** [comment]
Решено в релиз 2.Х в https://github.com/oscript-library/gitsync/issues/39 

У тебя какой релиз гитсинк? `gitsync version` что показывает?
Если версия 2.Х, пиши, переоткрою баг

**Comment by AlexStrizh** [comment]
2.11.1

**Comment by artbear** [comment]
2.1, наверное?

проблема на самом деле не в гитсинк, а в пакете Tool_1cd

выполни команды последовательно `opm update opm` и `opm update -all` на той машине, где стартует гитсинк, а потом еще раз запусти гитсинк

**Comment by AlexStrizh** [comment]
Был невнимателен в вопросе. Дал версию git, а не gitsync.
v.1.1
Обновить через opm не смог. Ошибка установки пакета 404

**Comment by artbear** [comment]
что именно не смог установить?
какая команда упала?
дай ее лог

**Comment by artbear** [comment]
подозреваю, у тебя очень старый набор скриптов

**Comment by AlexStrizh** [comment]
Обновился. Все отлично с opm. Действительно старые скрипты. Однако теперь другая ошибка:
21.02.2017 0:27:23: ОШИБКА - {Модуль C:\Program Files (x86)\OneScript\lib\gitsync\src\multi-controller.os / Ошибка в строке: 64 / Метод объекта не обнаружен (ТребуетсяСинхронизироватьХранилище)}

**Comment by artbear** [comment]
ты точно обе команды выполнил?
пришли лог `opm list`

какая версия гитсинк сейчас стоит?

**Comment by AlexStrizh** [comment]
100%, теперь v2.1

если открыть multi-controller.os , то там на строке с ошибкой из лога следующее

file: 'file:///c%3A/Program%20Files%20%28x86%29/OneScript/lib/gitsync/src/multi-controller.os'
severity: 'Ошибка'
message: 'Внешнее исключение (System.NullReferenceException): Ссылка на объект не указывает на экземпляр объекта.'
at: '65,1'
source: ''

**Comment by AlexStrizh** [comment]
Может влиять что у меня 64, а не 32?

**Comment by AlexStrizh** [comment]
1commands@1.1
1testrunner@1.4.3
asserts@0.3.1
cmdline@0.4.1
fs@0.3
gitsync@2.1
json@0.2.1
logos@0.5
opm@0.9.3
precommit1c@2.0.6
strings@0.4.1
tempfiles@0.2.1
tool1cd@0.3
v8runner@0.7.1

**Comment by artbear** [comment]
Да, это новый баг, появившийся после принятия PR https://github.com/oscript-library/gitsync/pull/37
Проблема в строке https://github.com/oscript-library/gitsync/blob/master/src/core/%D0%9A%D0%BB%D0%B0%D1%81%D1%81%D1%8B/%D0%9A%D0%BE%D0%BC%D0%B0%D0%BD%D0%B4%D0%B0All.os#L67
`Контроллер.ВыполнитьСинхронизациюПоФайлуНастроек(ЭтотОбъект, ИмяФайлаНастроек, ПараметрыКоманды["-force"] = Истина);`

Раньше этот код был в `gitsync.os`, и `ЭтотОбъект` соответственно было объект `gitsync.os`, у которого был метод `ТребуетсяСинхронизироватьХранилище`
А после переноса в `КомандаAll` у объекта `КомандаAll` нет такого метода.

@theshadowco Сможешь посмотреть и исправить?

**Comment by theshadowco** [comment]
Да, сеня

21 февр. 2017 г. 9:57 пользователь "Artur Ayukhanov" <
notifications@github.com> написал:

**Comment by theshadowco** [comment]
Прошу посмотреть, тесты прошли, но верить им не могу, ибо прошлый раз тож прошли :(

**Comment by yarsergo** [comment]
пытаюсь сделать первичный Init хранилища конфигурации 8.2 в свой репозиторий (локальный) 
ничего не проходит... 
уже по readme.md   иду...  вручную  - скопировал весь src gitsync (2.1.1 версии)  в папку своего локального репозитория, сделал установку через opm...  (1-ый способ через oneScript не прошел)
и после этого делаю INIT
выдаёт во-первых ошибку о расхождении длины файла в блоках... (хранилище естественно рабочее и никто из него никогда не выходит!)
и после этого окончательно выкидывает 
и  выдаёт ошибку тоже  на 46 стоке в файле  table-reader.os   модуля tool1cd
![image](https://user-images.githubusercontent.com/20444819/27226835-81196994-52a9-11e7-9309-48aa865bbd32.png)

**Comment by nixel2007** [comment]
обновите tool1cd через opm

**Comment by artbear** [comment]
Проблема исправлена в 2.2.0

**Comment by yarsergo** [comment]
спасибо
