### ISSUE TITLE
ошибка при gitsync init 

### ISSUE THREAD

**Issue by EvilBeaver** [oscript-library/gitsync#52]
Перенаправил с https://github.com/EvilBeaver/OneScript/issues/409:

by @Dumsik
выполняю gitsync init D:\1c_Dev\Arautom_ХранилищеКонфигурации D:\1cGitSync\KA\SrcConfig выходит ошибка
GitSync v2.1
КРИТИЧНАЯОШИБКА - {Модуль C:\Program Files (x86)\OneScript\lib\gitsync\src\core\Классы\МенеджерСинхронизации.os / Ошибка в строке: 842 / Метод объекта не обнаружен (ДобавитьКоманду)}

oscript последний 1Script Execution Engine. Version 1.0.15.260
устанавливал все по инструкции с сайта. Библиотека 1commands есть.
вывод opm list
Пакеты в системном каталоге библиотек <C:\Program Files (x86)\OneScript\lib>:
1commands
1testrunner
asserts
cmdline
fs
gitsync
json
logos
opm
strings
tempfiles
tool1cd
v8runner

**Comment by nixel2007** [comment]
Явно старые библиотеки. 
opm update opm
opm update -all

**Comment by EvilBeaver** [comment]
@Dumsik, попробуйте предложенное решение

**Comment by Dumsik** [comment]
обновление библиотек не помогло (все действия выполнялись в консоле с административными правами) :
C:\Program Files (x86)\OneScript\bin>opm update opm
ИНФОРМАЦИЯ - Скачиваю файл: opm.ospx
ИНФОРМАЦИЯ - Устанавливаю пакет opm
ИНФОРМАЦИЯ - Устанавливаю зависимость: fs
ИНФОРМАЦИЯ - Устанавливаю зависимость: logos
ИНФОРМАЦИЯ - Устанавливаю зависимость: cmdline
ИНФОРМАЦИЯ - Устанавливаю зависимость: tempfiles
ИНФОРМАЦИЯ - Регистрация приложения: opm
ИНФОРМАЦИЯ - Установка завершена
C:\Program Files (x86)\OneScript\bin>opm update -all
OneScript Package Manager v0.9.3

ИНФОРМАЦИЯ - Скачиваю файл: 1commands.ospx
ИНФОРМАЦИЯ - Устанавливаю пакет 1commands
ИНФОРМАЦИЯ - Устанавливаю зависимость: logos
ИНФОРМАЦИЯ - logos уже установлен. Пропускаем.
ИНФОРМАЦИЯ - Устанавливаю зависимость: asserts
ИНФОРМАЦИЯ - asserts уже установлен. Пропускаем.
ИНФОРМАЦИЯ - Устанавливаю зависимость: tempfiles
ИНФОРМАЦИЯ - tempfiles уже установлен. Пропускаем.
ИНФОРМАЦИЯ - Установка завершена
ИНФОРМАЦИЯ - Скачиваю файл: 1testrunner.ospx
ИНФОРМАЦИЯ - Устанавливаю пакет 1testrunner
ИНФОРМАЦИЯ - Устанавливаю зависимость: logos
ИНФОРМАЦИЯ - logos уже установлен. Пропускаем.
ИНФОРМАЦИЯ - Устанавливаю зависимость: cmdline
ИНФОРМАЦИЯ - cmdline уже установлен. Пропускаем.
ИНФОРМАЦИЯ - Устанавливаю зависимость: tempfiles
ИНФОРМАЦИЯ - tempfiles уже установлен. Пропускаем.
ИНФОРМАЦИЯ - Устанавливаю зависимость: strings
ИНФОРМАЦИЯ - strings уже установлен. Пропускаем.
ИНФОРМАЦИЯ - Устанавливаю зависимость: 1commands
ИНФОРМАЦИЯ - 1commands уже установлен. Пропускаем.
ИНФОРМАЦИЯ - Регистрация приложения: 1testrunner
ИНФОРМАЦИЯ - Свойство объекта не обнаружено (СоздаватьShСкриптЗапуска)

C:\Program Files (x86)\OneScript\bin>d:

D:\1cGitSync\KA>gitsync init D:\1c_Dev\Arautom\_ХранилищеКонфигурации "D:\1cGitS
ync\KA\SrcConfig" -email severotorg.ru
GitSync v2.1
КРИТИЧНАЯОШИБКА - {Модуль C:\Program Files (x86)\OneScript\lib\gitsync\src\core\
Классы\МенеджерСинхронизации.os / Ошибка в строке: 842 / Метод объекта не обнару
жен (ДобавитьКоманду)}

**Comment by Khorevaa** [comment]
Почистить папки гитсинк и переустановить только его. Или удалить файл командыйфайл.os.

**Comment by theshadowco** [comment]
Есть прдложение допилить opm, эта проблема всплывает не первый раз. 
Здесь https://github.com/oscript-library/gitsync/pull/48 подобная весчь

**Comment by Dumsik** [comment]
@Khorevaa 
> Почистить папки гитсинк и переустановить только его. Или удалить файл командыйфайл.os из папки гитсинка

помогло

**Comment by nixel2007** [comment]
Дык допиливали опм. При обновлении гитсинка он должен был дропнуть все OS файлы

**Comment by Khorevaa** [comment]
У меня была просто аналогичная ошибка. Я списал ее на свою не внимательность в последовательности обновления.
Например, 
1. Я саначал запустил обновление gitsync
2. Потом запустил обновление opm
3. Потом обновил еще раз gitsync... 

Как то, так.... 

Но видимо гдето есть скрытый баг. 

п.с. в зависимость gitsync надо прописать зависимость от версии opm. Он должен устанавиливать новый opm и запускать установку пакета по новой.

**Comment by artbear** [comment]
Закрываю, т.к. проблема не повторяется.
@Khorevaa @Dumsik Если проблема повторится, пишите, переоткроем.
