### ISSUE TITLE
Ошибка кодировки тестовов

### ISSUE THREAD

**Issue by theshadowco** [oscript-library/gitsync#53]
При выполнении сценариев тестирования, в частности git-sync-test.os происходит переключение кодировки консоли, что приводит к выводу "кракозябр"

**Comment by dmpas** [comment]
@artbear видимо, твоя "магия"? :)
https://github.com/oscript-library/gitsync/commit/58705d1a46f1fda8f958441ff8c74a7ef7370537

**Comment by artbear** [comment]
ИМХО это какой-то старый баг.
У меня как раз и нет этой проблемы.

Какая версия гитсинка юзается?
Подробнее сценарий приведи

**Comment by theshadowco** [comment]
Просто, открываю последний гитсинк, последний VSC, в консоли VSC запускаю прогон тестовов - и получаю выхлоп сналача нормальный, а потом (ближе к середине) в тесте вызывается метод изменения кодовой страницы консоли и все едет.

**Comment by nixel2007** [comment]
Подтверждаю, видел такое в 1.2
