### ISSUE TITLE
Поведение `-limit`

### ISSUE THREAD

**Issue by dmpas** [oscript-library/gitsync#55]
Сейчас limit задаёт разницу в номерах ревизий. По-моему, более логично, чтобы limit задавал количество выгрузок ревизий. Разница проявляется, если в хранилище было объединение версий:

```
1 - Ревизия 1
10 - Ревизия 10
15 - Ревизия 15
17 - Ревизитя 17
```

В данном случае, если я хочу выгружать ревизии по одной, то я каждый раз вынужден высчитывать разницу, вместо того, чтобы просто задать `-limit 1`.

**Comment by artbear** [comment]
А сейчас какое поведение при лимите для сокращенного хранилища?

**Comment by dmpas** [comment]
если у меня VERSION=1 и -limit 5, к примеру, то 10-ю ревизию он не выгрузит, ибо ограничится выгрузкой 6-й, которой нет.
