### ISSUE TITLE
Не очищаются созданные файлы в tempdir

### ISSUE THREAD

**Issue by KokotovAlexandr** [oscript-library/gitsync#60]
Коллеги, добрый день!
В команде gitsync я использовал параметр -tempdir и указал каталог для временных файлов. После корректной отработки скрипта все созданные файлы в каталоге сохраняются. В результате этот каталог разрастается десятком гигабайт в день.

**Comment by EvilBeaver** [comment]
Тоже это замечал. Кто героически возьмется исправить?

**Comment by Khorevaa** [comment]
Вообще доработку делал я. И умения каталог темп не рос сильно.  Поправить не сложно 5-10 минут работы.

**Comment by Khorevaa** [comment]
Видимо ошибка в строке кода [137](https://github.com/oscript-library/gitsync/blob/master/src/core/%D0%9C%D0%BE%D0%B4%D1%83%D0%BB%D0%B8/%D0%9C%D0%B5%D0%BD%D0%B5%D0%B4%D0%B6%D0%B5%D1%80%D0%9A%D0%BE%D0%BC%D0%B0%D0%BD%D0%B4%D0%9F%D1%80%D0%B8%D0%BB%D0%BE%D0%B6%D0%B5%D0%BD%D0%B8%D1%8F.os#L137) 
Удаление файлов происходит только при "отладке", хотя по логике должно быть наоборот
