### ISSUE TITLE
cTool_1CD не может прочитать данные рабочего хранилища 1с

### ISSUE THREAD

**Issue by KokotovAlexandr** [oscript-library/gitsync#61]
Коллеги, добрый день!
Столкнулся с такой проблемой. При начале синхронизации cTool_1CD иногда возвращает ошибки, хотя хранилище в рабочем состоянии и активно используется. Спустя какое-то время (последний раз спустя 2 недели) данные из хранилища начинают снова корректно получаться. Недавно я обновил gitsync до версии 2.1, все заработало и я уж было обрадовался, но не тут-то было. Спустя пару дней снова возникла та же проблема. Хочу отметить, что хранилище в рабочем состоянии и с ним активно ведут работу.
Подскажите пожалуйста, в чем проблема и как с этим бороться? 
Опишу то, что возвращает отладчик:
gitsync "Адрес хранилища" "URL" "локальный репозиторий" -v8version 8.3
.9.1850 -debug on -email Домен -push-every-n-commits 1 -tempdir "каталог временных файлов"
GitSync v2.1.1
ИНФОРМАЦИЯ - Начинаю синхронизацию хранилища 1С и репозитария GIT
ОТЛАДКА - ПутьКХранилищу = Адрес хранилища
ОТЛАДКА - URLРепозитория = URL 
ОТЛАДКА - ЛокальныйКаталогГит = локальный репозиторий
ОТЛАДКА - ДоменПочты = Домен
ОТЛАДКА - ВерсияПлатформы = 8.3.9.1850
ОТЛАДКА - Формат = Hierarchical
ОТЛАДКА - ИмяВетки = master
ОТЛАДКА - НачальнаяВерсия = 0
ОТЛАДКА - КонечнаяВерсия = 0
ОТЛАДКА - Лимит = 0
ОТЛАДКА - КоличествоКоммитовДоPush = 1
ИНФОРМАЦИЯ - Получение изменений с удаленного узла (pull)
ОТЛАДКА - строкаКоманды = < git pull -v URL > "каталог временных файлов\izfge3wn.rr5.log" 2>&1>
ИНФОРМАЦИЯ - From URL
 * branch            master     -> FETCH_HEAD
Already up-to-date.

ИНФОРМАЦИЯ - Синхронизация изменений с хранилищем
ИНФОРМАЦИЯ - Начало синхронизации с git
ОТЛАДКА - Пользователю хранилища <antsyu_home> не сопоставлен пользователь git. Использую сопоставление по умолчанию
ОТЛАДКА - Предыдущая версия из хранилища 1С: 1494
ИНФОРМАЦИЯ - Номер синхронизированной версии: 1494
ОТЛАДКА - Используется формат выгрузки Hierarchical
ИНФОРМАЦИЯ - Номер последней версии в хранилище: 1508
ИНФОРМАЦИЯ - Получаем исходники для версии 1495
ОТЛАДКА - Выгружаем версию хранилища в файл "каталог временных файлов"\t4vqpz42.rxm.tmp\v1495.cf
ОТЛАДКА - Получаем файл версии <1495> из хранилища: "Адрес хранилища"\1cv8ddb.1CD
ОТЛАДКА - "C:\Program Files (x86)\OneScript\lib\tool1cd\bin\cTool_1CD.exe" "Адрес хранилища\1cv8ddb.1CD" -l "каталог временных файлов\ibhh4kd5.sqw.txt" -q -n
e -drc 1495 "каталог временных файлов\t4vqpz42.rxm.tmp\v1495.cf"
ОТЛАДКА - 15.03.2017 16:48:05 <ok> База данных 1CD открыта
        Файл = Адрес хранилища\1cv8ddb.1CD
        Версия базы = 8.2.14.0
        Locale = ru_RU
        Режим = Только чтение
        Количество таблиц = 10

15.03.2017 16:48:42 <error> Не найден файл
        Файл = Адрес хранилища\data\objects\d9\96d9dbb73f1eec6005fea15437b54f76bd060a
        Таблица = EXTERNALS
        Объект = b17cea0b-456c-4243-9f99-52ec28df7037.0
        Версия = 1495

15.03.2017 16:48:42 <error> Ошибка чтения объекта конфигурации
        Таблица = EXTERNALS
        Объект = b17cea0b-456c-4243-9f99-52ec28df7037.0
        Версия = 1495

15.03.2017 16:50:52 <error> Не найден файл
        Файл = Адрес хранилища\data\objects\01\7decbc85d2d8a5f1c3af08993b12ca94e2ffdc
        Таблица = EXTERNALS
        Объект = 280ce535-fcfb-4447-a373-bc94760ef1dd.0
        Версия = 1495

15.03.2017 16:50:52 <error> Ошибка чтения объекта конфигурации
        Таблица = EXTERNALS
        Объект = 280ce535-fcfb-4447-a373-bc94760ef1dd.0
        Версия = 1495

15.03.2017 16:51:22 <error> Не найден файл
        Файл = Адрес хранилища\data\objects\b1\0589566528f18fdfad86e78f7593350c0ebacf
        Таблица = EXTERNALS
        Объект = 90433152-f389-4d45-8ccc-3eb6c7a7e1f0.0
        Версия = 1495

15.03.2017 16:51:22 <error> Ошибка чтения объекта конфигурации
        Таблица = EXTERNALS
        Объект = 90433152-f389-4d45-8ccc-3eb6c7a7e1f0.0
        Версия = 1495

15.03.2017 16:51:54 <error> Не найден файл
        Файл = Адрес хранилища\data\objects\aa\dd13fad65d6a7a900d4ccfb1981c73de9eca5f
        Таблица = HISTORY
        Объект = 2e3c7954-5a1d-44c1-99db-6e19880f352d
        Версия = 1495

15.03.2017 16:51:55 <error> Ошибка чтения объекта конфигурации
        Таблица = HISTORY
        Объект = 2e3c7954-5a1d-44c1-99db-6e19880f352d
        Версия = 1495

15.03.2017 16:54:41 <ok> Сохранение конфигурации хранилища завершено.
        Файл = каталог временных файлов\t4vqpz42.rxm.tmp\v1495.cf

ОШИБКА - 15.03.2017 16:48:05 <ok> База данных 1CD открыта
        Файл = Адрес хранилища\1cv8ddb.1CD
        Версия базы = 8.2.14.0
        Locale = ru_RU
        Режим = Только чтение
        Количество таблиц = 10

15.03.2017 16:48:42 <error> Не найден файл
        Файл = Адрес хранилища\data\objects\d9\96d9dbb73f1eec6005fea15437b54f76bd060a
        Таблица = EXTERNALS
        Объект = b17cea0b-456c-4243-9f99-52ec28df7037.0
        Версия = 1495

15.03.2017 16:48:42 <error> Ошибка чтения объекта конфигурации
        Таблица = EXTERNALS
        Объект = b17cea0b-456c-4243-9f99-52ec28df7037.0
        Версия = 1495

15.03.2017 16:50:52 <error> Не найден файл
        Файл = Адрес хранилища\data\objects\01\7decbc85d2d8a5f1c3af08993b12ca94e2ffdc
        Таблица = EXTERNALS
        Объект = 280ce535-fcfb-4447-a373-bc94760ef1dd.0
        Версия = 1495

15.03.2017 16:50:52 <error> Ошибка чтения объекта конфигурации
        Таблица = EXTERNALS
        Объект = 280ce535-fcfb-4447-a373-bc94760ef1dd.0
        Версия = 1495

15.03.2017 16:51:22 <error> Не найден файл
        Файл = Адрес хранилища\data\objects\b1\0589566528f18fdfad86e78f7593350c0ebacf
        Таблица = EXTERNALS
        Объект = 90433152-f389-4d45-8ccc-3eb6c7a7e1f0.0
        Версия = 1495

15.03.2017 16:51:22 <error> Ошибка чтения объекта конфигурации
        Таблица = EXTERNALS
        Объект = 90433152-f389-4d45-8ccc-3eb6c7a7e1f0.0
        Версия = 1495

15.03.2017 16:51:54 <error> Не найден файл
        Файл = Адрес хранилища\data\objects\aa\dd13fad65d6a7a900d4ccfb1981c73de9eca5f
        Таблица = HISTORY
        Объект = 2e3c7954-5a1d-44c1-99db-6e19880f352d
        Версия = 1495

15.03.2017 16:51:55 <error> Ошибка чтения объекта конфигурации
        Таблица = HISTORY
        Объект = 2e3c7954-5a1d-44c1-99db-6e19880f352d
        Версия = 1495

15.03.2017 16:54:41 <ok> Сохранение конфигурации хранилища завершено.
        Файл = каталог временных файлов\t4vqpz42.rxm.tmp\v1495.cf

ОТЛАДКА - Откатываем файл VERSION после ошибки
ОТЛАДКА - ПутьКФайлуВерсий =<локальный репозиторий\VERSION>
КРИТИЧНАЯОШИБКА - {Модуль C:\Program Files (x86)\OneScript\lib\tool1cd\config-storage.os / Ошибка в строке: 39 / Tool_1CD вернул код возврата 1}

**Comment by milanse** [comment]
А какой версии хранилище ? 
У меня 8.3.8 постоянно падает, я так понимаю tool_cd  не корректно работает с 8.3.8

**Comment by KokotovAlexandr** [comment]
У меня версия 8.3.9.1850

**Comment by EvilBeaver** [comment]
Попробуйте пакет tool1cd обновить.

    opm update tool1cd

**Comment by Khorevaa** [comment]
У меня была аналогичная проблема. В случае если хранилище лежит на отдельной шаре и на эту шару настроены права доступа перед запуском гитсинка надо зайти на эту шару 1 раз.

**Comment by artbear** [comment]
Закрываю в связи с решенностью вопроса.
