### ISSUE TITLE
После выполнения коммита меняется кодировка консоли

### ISSUE THREAD

**Issue by nixel2007** [oscript-library/gitsync#62]
Берем консоль, делаем в ней chcp 65001, выполняем экспорт. первый коммит видим в консоли в кириллице, второй - кракозябрах.

**Comment by EvilBeaver** [comment]
У меня дежавю что я такое уже регал где-то

**Comment by nixel2007** [comment]
есть ишуз про тесты. возможно причина общая, и она не в тестах, а в самом гитсинке.

**Comment by nixel2007** [comment]
link #53

**Comment by Stepa86** [comment]
Может дело в этой строчке? https://github.com/oscript-library/gitsync/blob/master/src/core/%D0%9A%D0%BB%D0%B0%D1%81%D1%81%D1%8B/%D0%9C%D0%B5%D0%BD%D0%B5%D0%B4%D0%B6%D0%B5%D1%80%D0%A1%D0%B8%D0%BD%D1%85%D1%80%D0%BE%D0%BD%D0%B8%D0%B7%D0%B0%D1%86%D0%B8%D0%B8.os#L444

**Comment by dmpas** [comment]
Бить по рукам за всё, что отличается от юникода.

**Comment by EvilBeaver** [comment]
А вот и коммит. https://github.com/oscript-library/gitsync/commit/58705d1a46f1fda8f958441ff8c74a7ef7370537 Хотя камент над указанной строчкой, говорит о том, что этот коммит был лишь попыткой починить точно такое же поведение. Просто неудачная попытка.

**Comment by artbear** [comment]
Это была удачная попытка. В тот момент больше никаких проблем с кодировкой не было.
я же специально разбирался и исправлял.

**Comment by EvilBeaver** [comment]
@artbear а это уже в хабе? Просто ощущение, что недопочинено.

**Comment by artbear** [comment]
@EvilBeaver Конечно, в хабе.

Смотрим скриншот
![image](https://cloud.githubusercontent.com/assets/2920817/24541573/b9876a3c-1600-11e7-979b-462ba6fca545.png)

**Comment by nixel2007** [comment]
Этот ишуз не про тесты.
