### ISSUE TITLE
проблема

### ISSUE THREAD

**Issue by cupertino1** [oscript-library/gitsync#65]
День добрый!

Я так и не понял, как это работает. Что-то недонастроил?

1. Создал простую конфигурацию C:/1c/_test

2. Создал её хранилище C:/1c/_test222

3. Создал репо на github.com   https://github.com/cupertino1/_test222.git

4. запустил последовательно:

git clone https://github.com/cupertino1/_test222.git _test222
cd _test222 
oscript C:/1c-repo/gitsync/src/gitsync.os init C:/1C/_test222 ./src/cf 
oscript C:/1c-repo/gitsync/src/gitsync.os set-version ./src/cf 0
git add .
git commit -m "Инициализация"
git push origin master
oscript C:/1c-repo/gitsync/src/gitsync.os export C:/1C/_test222 ./src/cf/ -debug off -format hierarchical
git push origin master

При запуске вывалилась куча ошибок. Но при этом создалось внутри c:/1c/_test222/src/cf подкаталоги с XML моей конфигурации.

5. В установленном SourceTree добавляю репозиторий, смотрящий сюда c:/1c/_test222/src/cf и привязываю его к внешнему https://github.com/cupertino1/_test222.git

6. Меняю что-то в конфигурации, сохраняю, КОММИТЧУ в ХРАНИЛИЩЕ (сюда c:/1c/_test222).   
В репозитории при этом ничего не происходит (SourceTree смотрит сюда c:/1c/_test222/src/cf).   
Понимаю, что наверное надо что-то изменить тут c:/1c/_test222/src/cf - тогда и SourceTree увидит это. Но как?

Я ожидаю от этого решения следующее.... Когда я помещаю изменения в хранилище 1С, то автоматом хочу, чтобы это увидел SourceTree и предложил закоммитить в Git,
 
Как это настроить?

Спасибо.

**Comment by nixel2007** [comment]
Гитсинк сам по себе не следит за изменением файла хранилища. Либо запускайте его руками каждый раз, либо планировщиком, либо сервером сборок (в идеале)

**Comment by cupertino1** [comment]
понятно. Спасибо.
