### ISSUE TITLE
Ограничение на размер файла в GitHub 100Мб

### ISSUE THREAD

**Issue by yarsergo** [oscript-library/gitsync#74]
не даёт закомитить файл более 100 Мб ?

POST git-receive-pack (chunked)
remote: error: GH001: Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com.        
remote: error: Trace: b19c67e153f22be346ba125b726fbd83        
remote: error: See http://git.io/iEPt8g for more information.        
remote: error: File STORE/1cv8ddb.1CD is 536.79 MB; this exceeds GitHub's file size limit of 100.00 MB

**Comment by nixel2007** [comment]
Да, есть такое ограничение. Но зачем вы кладете *базу* в гит?

**Comment by yarsergo** [comment]
это хранилище базы... а не сама база... которая  размерами более 100 ГигабБат

**Comment by yarsergo** [comment]
https://git-lfs.github.com/   вроде должно помочь еще часик... и пойму что очередной облом :(

**Comment by nixel2007** [comment]
Сути это не меняет :) Зачем класть хранилище в гит? Гитсинк используется как для для того, чтобы из хранилища вытягивать все версии и раскладывать их по коммитам в гит. Само файл хранилища в гит при этом класть не нужно.
