### ISSUE TITLE
Медленно разбираются версии хранилища 1С

### ISSUE THREAD

**Issue by yarsergo** [oscript-library/gitsync#75]
очень медленно работает разбор по версиям хранилища - 10 версий в час... 
причем не зависимо от объёма изменений что 1 строка в 1 документе, что куча новых объектов

Делаю в cmd:
  gitsync sync <папка хранилища 1С>  <url .git>  <папка локального репозитария этого git>
1) сначала ругается что нет доступа к <url .git>
2) пишет текущую версию, версию хранилища и объём таблиц...
3) 1-2 мин ничего не показывает... потом пишет что идёт получение следующей версии
и запускает 8.3 конфигуратор (хотя у хранилище на 8.2)
4) долго моргает много "черных" окон и выдаёт ошибку коммита  <0>   
5) после этого приходится "тормозить" выполнение  и руками коммитить и пушить (через в git GUI)

подскажите что сделать для "ускорения"...

у нас с начала только этого года - накопилось около 1,5 тыс версий...  не хотелось бы на это убивать 150 часов ?!

**Comment by ret-Phoenix** [comment]
Выгрузка в файлы делается 1С-ным родным методом Выгрузить конфигурацию в файлы. Большие конфигурации выгружаются в файлы долго, это не проблема GitSync.

**Comment by yarsergo** [comment]
Спасибо за нерадостную новость...
пробую gitsync export .... -maxversion ...     порциями без выгрузки в git  
наверное быстрее всё таки будет

**Comment by dmpas** [comment]
@yarsergo ещё есть параметр `-limit 1` - чтобы -maxversion не высчитывать. ещё есть параметр, как часто забрасывать изменения на сервер.

**Comment by yarsergo** [comment]
@ret-Phoenix   выгрузка из конфигуратора - не самая долгая операция - 1 мин, 
2-3 мин - разбор по папкам делается
и еще 3 мин "лишние" на работу с git

export работает быстрее так как этого не делает... 
и выгрузка (на моей базе) идет за  4 мин на версию.... вместо 6 мин
тоже долго но все-таки быстрее

**Comment by dmpas** [comment]
разбор по папкам - это тот, когда много чёрных окон моргает? тут надо новой версии ждать, там чёрных окон нет и эта операция несколько шустрее идёт

**Comment by yarsergo** [comment]
@dmpas,  спасибо, будем ждать обновлений
