### ISSUE TITLE
Ошибка в строке: 64 / Метод объекта не обнаружен (ТребуетсяСинхронизироватьХранилище)

### ISSUE THREAD

**Issue by fenixnow** [oscript-library/gitsync#76]
Столкнулся с проблемой. 
Настроены три связки хранилище - git, если запускать руками, через gitsync export, а потом делать push все работает хорошо, но при использовании gitsync all _путь_к_файлу_ -log _путь_к_логу_, в лог записываются события и ничего не происходит. (лог прилагаю)
[log-gitsync.txt](https://github.com/oscript-library/gitsync/files/1147652/log-gitsync.txt)

Почему программа не может найти метод и что я сделал не так?

OneScript 1.0.16

**Comment by nixel2007** [comment]
Обновление библиотек не помогает? в частности v8runner

**Comment by fenixnow** [comment]
а подскажи пожалуйста как сделать обновление?
устанавливал гитсинк через комманду - opm install gitsync

**Comment by nixel2007** [comment]
opm install v8runner

**Comment by fenixnow** [comment]
не помогло, 
сделал opm install v8runner 
ошибка сохраняется
дополнительно сделал opm install gitsync 
ошибка сохраняется
перезагрузка тоже не помогла

**Comment by fenixnow** [comment]
opm update -all также не дало результатов....

Пытаюсь разобраться уже не первый раз с oscript, подскажите, можно ли отлаживать код из .os?

**Comment by nixel2007** [comment]
@fenixnow ну.... вообще *уже* можно, но оно пока не предназначено для каждодневного использования. что-то падает, что-то отваливается, требуется устанавливать кастомную экспериментальную версию движка (которую еще и собрать надо).

Бонусом - ошибка выглядит как ошибка компиляции, то есть отладчиком ее не поймать.

Призываю @artbear и @EvilBeaver, код поковырять.

**Comment by fenixnow** [comment]
а можно понять что возвращает _мКонтроллер_?
я так понимаю что это какой то общий модуль, дальше идет обращение к функции _ТребуетсяСинхронизироватьХранилище_

Если посмотреть по коду всего проекта описание функции встречается только в пару местах в одном из которых принудительно возвращает _Истина_

**Comment by EvilBeaver** [comment]
Я сто лет не залезал в гитсинк (

Данная задача актуальна?

**Comment by fenixnow** [comment]
для меня скорее уже нет, но думаю проблема осталась.

**Comment by EvilBeaver** [comment]
@fenixnow я почему и спрашиваю, потому что это я точно помню, что давно починили.

**Comment by artbear** [comment]
Закрываю ишуз, т.к. подозреваю, что давно исправлено.
Больше никто не жаловался.
Если ошибка вновь возникнет, переоткроем.
