### ISSUE TITLE
Ошибка при вызове gitsync init.

### ISSUE THREAD

**Issue by volkoffsasha** [oscript-library/gitsync#77]
Может подскажите куда рыть? Такая же ошибка при вызове gitsync clone.

WARNING! Deprecated method: 'SystemInfo.GetEnvironmentVariable' is deprecated, u
se 'GetEnvironmentVariable' from global context
GitSync v1.1

ИНФОРМАЦИЯ - "git" ?? ????? ???????? ??? ?????
????????, ??????? ?????? ??? ?????? ????.

ИНФОРМАЦИЯ - "git" ?? ????? ???????? ??? ?????
????????, ??????? ?????? ??? ?????? ????.

ОШИБКА - {Модуль c:\Program Files (x86)\OneScript\lib\gitsync\src\gitsync.os / О
шибка в строке: 230 / git init вернул код <9009>}

**Comment by nixel2007** [comment]
Гит на машине стоит? После установки перегружались?

**Comment by volkoffsasha** [comment]
Да гит стоит. И перегружался.

**Comment by artbear** [comment]
GitSync v1.1 очень старая версия.
сейчас последняя 2.1.1

**Comment by volkoffsasha** [comment]
Где взять? Качал вроде всё с официального сайта.

**Comment by artbear** [comment]
Официальный сайт это где?

официальный способ обновления/установки - выполнить команду `opm install gitsync`

**Comment by volkoffsasha** [comment]
Официальный сайт - http://oscript.io/downloads

**Comment by artbear** [comment]
все-таки RTFM :) 
https://github.com/oscript-library/gitsync#Установка

**Comment by volkoffsasha** [comment]
Вот результат:
d:\Program Files\OneScript\lib\gitsync>oscript.exe "d:\Program Files\OneScript\lib\gitsync\src\gitsync.os"
WARNING! Deprecated method: 'SystemInfo.GetEnvironmentVariable' is deprecated, use 'GetEnvironmentVariable' from global context
GitSync v2.1.1
ОШИБКА - Некорректные аргументы командной строки
Возможные команды:
 help         - Вывод справки по параметрам
 clone        - Клонирует существующий репозиторий и создает служебные файлы
 init         - Создает новый репозиторий и создает служебные файлы
 set-version  - Устанавливает необходимую версию в файл VERSION
 all          - Запускает синхронизацию по нескольким репозиториям
 export       - Выполнить локальную синхронизацию, без pull/push
 sync         - Выполняет синхронизацию хранилища 1С с git-репозиторием (указание имени команды необязательно)
 version      - Выводить версию приложения

**Comment by artbear** [comment]
все верно, нет команды для гитсинка, он просто пишет справку

читаем доку

**Comment by volkoffsasha** [comment]
Ну как бы из доки всё и сделано:
"Установка
Вручную
Вручную - Скопировать каталог gitsync/src на жесткий диск
Запустить приложение командой oscript.exe <каталог gitsync>\src\gitsync.os"

Что не так сделал?
Последняя строка в мануале уже не относится к установке? Тогда зачем всё это? После установки и так всё там лежало. И так всё запускалось со старой версией. Ошибка то никуда не делась.

**Comment by artbear** [comment]
`Запустить приложение командой oscript.exe <каталог gitsync>\src\gitsync.os`
это строка нужна для проверки запуска :)

читай далее, раздел Использование

**Comment by volkoffsasha** [comment]
Используем этапы:
Клонировать средствами Git исходный репозитарий (git clone) "
Примеры использования:
gitsync init "W:\Хранилище1С" .
Делаю по этой инструкции:
d:\WorkArea\ПустаяПапкаДляГит>gitsync init "\\ПутьКХранилищу\" .
WARNING! Deprecated method: 'SystemInfo.GetEnvironmentVariable' is deprecated, u
se 'GetEnvironmentVariable' from global context
GitSync v2.1.1
ИНФОРМАЦИЯ - "git" ?? ????? ???????? ??? ?????
????????, ??????? ?????? ??? ?????? ????.
ИНФОРМАЦИЯ - "git" ?? ????? ???????? ??? ?????
????????, ??????? ?????? ??? ?????? ????.
КРИТИЧНАЯОШИБКА - {Модуль c:\Program Files (x86)\OneScript\lib\gitsync\src\core\
Классы\КомандаInit.os / Ошибка в строке: 42 / git init вернул код <9009>}
Куда рыть?

**Comment by volkoffsasha** [comment]
Как я понимаю обычная история. Раз бесплатно, то ковыряйся сам. Ну прям линух какой-то. 
Что сказать?! Либо продукт сырой и корявый. Либо спецов по нему совсем нет, а гуру все круто заняты. 
Про то что я ламер ничего не понимающий можете не отвечать, - это очевидно. Знал бы что сделать не спрашивал бы.
Развития вашему проекту. Пусть работает из коробки лучше винды. 
Удаляю, забываю. Буду руками делать.

**Comment by nixel2007** [comment]
Пока вы не дадите полный лог ошибки без кракозябр - неважно как, в гитбаше, с передачей энкодинга оскрипту, через chcp - вам никто не сможет помочь. 

Мы тут рады помочь всем страждущим, но да, у каждого есть свои дела (удивительное дело!). Большая часть вообще в отпуске.

**Comment by nixel2007** [comment]
Плюс ко всему вы выдаёте описание справки с куском гит клона, а выполняете команду гитсинк инит. Я не могу найти место в справке, где бы эти команды были описаны последовательно.

**Comment by nixel2007** [comment]
@artbear а зачем ты ишуз закрыл? Вопрос не в установке гитсинка, а в ините

**Comment by volkoffsasha** [comment]
Никита, я выдал всё что у меня было. Какое есть. Почему оно вопросиками отображается знает только винда. 
Кусок справки полностью выглядел так:
"Клонировать средствами Git исходный репозитарий (git clone) или создать новый (git init)"
пришлось в комментарии обрезать не влазило описание ошибки.
Интернет не при чем. Я же создаю локальную репу в папку. Потом буду её помещать в сетевой гит. Или "gitsync init "W:\Хранилище1С" ." как-то по другому работет?
Тем более проделывал эту команду на машине где с интернетом всё хорошо и результат тот же.

**Comment by nixel2007** [comment]
Я правильно понимаю, что вы сначала сделали гит клон, а потом в этой папке гитсинк инит? Гитсинк инит сам по себе инициализирует репозиторий, вероятно ошибка говорит о том, что парка не пуста и в ней нельзя выполнить еще один git init. 

Если да, то либо сделайте гитсинк инит в любой другой папке и перенесите из него два созданных файла, либо создайте их вручную в готовом репо (VERSION и AUTHORS)

**Comment by volkoffsasha** [comment]
Последний раз просто создал папку пустую и её указал в аргументах. 
До этого создавал папку её вручную цеплял к гиту. Потому делал gitsync clone. Ошибка была та же.

**Comment by nixel2007** [comment]
Дабы не блокировать сейчас вашу работу рекомендую руками создать нужные файлы. А различные сценарии инициализации мы проверим и допишем доку по непонятным комбинациям

**Comment by artbear** [comment]
Я смотрел по последнему сообщению.
Автор запустил правильную версию гитсинк, кракозябров нет, автор не написал, что у него еще проблемы есть, я и закрыл :)

Переоткрою

**Comment by artbear** [comment]
>`d:\WorkArea\ПустаяПапкаДляГит>gitsync init "\ПутьКХранилищу" .`

+ что за "\ПутьКХранилищу" ? что за слеш?
опасно использовать подобное сочетание

+ как запускается гитсинк? из какой среды - напрямую из cmd, poweshell, git bash или вызов внутри бат-cmd-файла? что-то еще?

+ что выдает команда `where git` (или `which git`) ?

+ что выдает команда `git version` ?

**Comment by volkoffsasha** [comment]
Что-то сдвинулось. Я по ламерству своему запускал просто cmd и оттуда не видно было гит. Запустил ярлык gitcmd. Теперь пишет:
Initial commit
Untracked files:
  (use "git add <file>..." to include in what will be committed)
        gitsync
        gitsync.bat
nothing added to commit but untracked files present (use "git add" to track)
В папке появились файлы:
.git\
gitsync
AUTHORS
VERSION

**Comment by artbear** [comment]
>Я по ламерству своему запускал просто cmd и оттуда не видно было гит

вот это плохо. я ведь не зря написал вопросы по `where git` и `git version`

они должны работать в обычном cmd.

Либо не сделал перезапуск после установки гита, либо не выбрал флаг в гите насчет PATH.
для 2-го варианта лучше переустанови git

**Comment by volkoffsasha** [comment]
> я ведь не зря написал вопросы по where git и git version
Не зря, потому и понял что не видит гит 👍 

Спасибо, что вытерпели мои вопросы до конца!

**Comment by artbear** [comment]
Закрываю.
@volkoffsasha Если проблема осталась, переоткрывайте.

**Comment by ivnazarenko** [comment]
Господа, подскажите, пожалуйста, как в итоге решили эту проблему? 
Я в командной строке ввожу gitsync init "D:\1C_rep\money\1cv8ddb.1CD" D:\Repositories\money
и выдается сообщение следующего плана 
![Screenshot_14](https://user-images.githubusercontent.com/49858856/56595308-1418ae00-65f7-11e9-9f82-a46c88e37a37.png)
