### ISSUE TITLE
Ошибка при определении пути к Program Files на 64 битной ОС

### ISSUE THREAD

**Issue by ArchLord42RU** [oscript-library/gitsync#78]
Стояла платформа 8.3.8, обновился до 8.3.10, так же обновил OneScript до 1.0.17.90 и перестал работать gitsync со следующей ошибкой
![image](https://user-images.githubusercontent.com/4038422/29101505-804f3d9a-7cd4-11e7-8482-d883351dc4f9.png)
Собственно в параметрах командной строки указано -v8version 8.3.10, но при отладке выяснил, что в функцию в либе "v8runner"

> ПолучитьПутьКВерсииПлатформы(Знач ВерсияПлатформы)

передается ВерсияПлатформы как 8.3 (без минорной версии), в связи с этим цикле, который расположен ниже, в этой же функции

> Для Каждого ВозможныйПуть Из КаталогиУстановкиПлатформы Цикл

не удается найти нужный путь, т.к. априори нет папки с C:\Program Files (x86)\1C\8.3
Соотвественно, по условию цикла, если нужная папка не найдена, используется последний элемент массива спарсенных путей из конфига 1CEStart.cfg (как раз C:\Program Files), потом идет поиск макс версии в итоге путь получается
C:\Program Files\8.3.10.2466, где исполняемого exe файла попросту нет.

**Comment by nixel2007** [comment]
Обновите библиотеку v8runner. Это уже давно было исправлено.

**Comment by ArchLord42RU** [comment]
Ок, спасибо, что-то и не попробовал даже это сделать :(
