### ISSUE TITLE
Добавить прогон фич на билд-сервере

### ISSUE THREAD

**Issue by artbear** [oscript-library/gitsync#79]
http://build.oscript.io/job/oscript-library/job/gitsync

сейчас прогоняются только тесты `1testrunner`, но в проекте есть фичи для `1bdd`

**Comment by nixel2007** [comment]
https://github.com/oscript-library/gitsync/blob/master/tasks/test.os

**Comment by artbear** [comment]
Скопировать универсальный test.os для 1коммандс и т.п. репо из http://build.oscript.io/job/oscript-library/

**Comment by artbear** [comment]
Выполнено. 
Например, http://build.oscript.io/job/oscript-library/job/gitsync/job/feature%252Ffeature-for-ci-79/
