### ISSUE TITLE
Получение исходников конфигурации через штатные механизмы платформы

### ISSUE THREAD

**Issue by artbear** [oscript-library/gitsync#86]
Есть реализация https://github.com/VKokotova/gitsync_1c

nocamad @nocamad 12:53 https://gitter.im/EvilBeaver/oscript-library?at=59f302255a1758ed0f568341
>там ничего особенного просто убран один шаг и заменена работа с загрузкой cf во временную базу на штатную платформенную, далее еще пилили изменения под работу в контейнере запуск линуховых команд

**Comment by Khorevaa** [comment]
Реализация не доделанная т.к . не нашел получения истории хранилища (коммитов) штатными средствами. Я уже в своем репо https://github.com/Khorevaa/v8storage сделал заготовки необходимы а доделать никак не доходят руки

**Comment by nocamad** [comment]
@Khorevaa ее разве можно получить штатными средствами? У нас задача реализуется методом эмуляции вызова к серверу хранилища, но и это не штатные средства. Здесь же допиливалось то что может работать штатно.

**Comment by Stepa86** [comment]
Получение истории хранилища средствами 1С есть в гиттере https://github.com/Stepa86/1C-Gitter/blob/master/src/CommonModules/%D0%9F%D0%B0%D0%BA%D0%B5%D1%82%D0%BD%D1%8B%D0%B9%D0%A0%D0%B5%D0%B6%D0%B8%D0%BC/Ext/Module.bsl#L2

**Comment by nocamad** [comment]
@Stepa86 "средствами 1С"? в том виде который нужен чтобы без его обработки получить все что нужно для гита? или это кладется и обрабатывается "нештатными" средствами )?

**Comment by Stepa86** [comment]
@nocamad В проекте гитлер все на 1С, кроме распаковки обычных форм. Тут правда есть ньюанс. Прочитать mxl файл очень даже штатные средства 1С, но не очень для оскрипта

**Comment by nocamad** [comment]
@Stepa86 я под штатными понимаю не то что написано на 1с, а то что использует платформенные механизмы в шагах процесса - здесь вызовы заменены на штатные именно платформы, а не на загрузку версии хранилища из языка 1с.

**Comment by Stepa86** [comment]
@nocamad Ну вот у меня как раз все через пакетный режим 1С, кроме распаковки обычных форм.

**Comment by nocamad** [comment]
@Stepa86 это хорошо, надо будет посмотреть - нам прежде всего нужна скорость на таких конфах как ерп и уха, чтоб при ежедневных коммитах сборочная успевала в режиме дергания по коммиту распаковываться в гит - если будет быстро и штатно (обычные формы вроде уже не юзаем) будет заманчиво, спасибо.

**Comment by nocamad** [comment]
@Stepa86 "Гиттер хорош при инкрементальной выгрузке, что есть только в 8.3.10" - учитывает что типовая инкрементальная выгрузка сейчас не всегда удаляет удаленные объекты из каталога?

**Comment by Stepa86** [comment]
@nocamad типовая выгрузка никогда не удаляет удаленное или переименованное, но если сама 1Ска находит факт удаления/переименования, то в файл ConfigDumpInfo.xml она пишет "FullDump" и тогда гиттер делает обычную выгрузку, с предварительной очисткой каталога. В гитсинхе вроде б инкрементальную выгрузку такую же хотели прикрутить

**Comment by nocamad** [comment]
@Stepa86 удаляет

**Comment by nocamad** [comment]
Но, не всегда

**Comment by Khorevaa** [comment]
@nocamad сначала получение отчета по версиям из хранилища (штатным средством), потом парсинг mxl в json (см. [тут](https://github.com/Khorevaa/v8storage/blob/master/epf/%D0%9E%D0%B1%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%BA%D0%B0%D0%9A%D0%BE%D0%BD%D0%B2%D0%B5%D1%80%D1%82%D0%B0%D1%86%D0%B8%D0%B8MXLJSON/%D0%9E%D0%B1%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%BA%D0%B0%D0%9A%D0%BE%D0%BD%D0%B2%D0%B5%D1%80%D1%82%D0%B0%D1%86%D0%B8%D0%B8MXLJSON/Ext/ObjectModule.bsl) Как то вот так получается.

**Comment by Khorevaa** [comment]
@nocamad  @artbear  Если делать такую допилку она должна решать проблему работы с НЕ файловыми хранилищами, а  с tcp и http. А без получения истории штатным средством синхронизировать с git - нечего.

**Comment by nocamad** [comment]
@khorevaa как бы естественно получить и распарсить - этим оно и стает нештатным, о чем я и пытался донести выше. Что касается второго - как вы процесс построите, такие и ограничения у вас будут - нет никакой обязанности работая с серверным хранилищем делать коннект к нему также вызовом к серверу - можно просто гитсинку получить его себе локально и делать все что необходимо локально, что в свою очередь избавляет также от массы проблем параллельного доступа.

**Comment by Khorevaa** [comment]
@nocamad  получение хранилища - это время 5-7 минут на больших хранилищах. Да и собственно не всегда хранилище доступное по http, доступно для копирования. (я бы сказал в 90% случаев не доступно)
Штатное средство подразумевалось без дополнительных оберток из oscript только с помощью 1С. Выгрузить и распарсить на мой взгляд как раз и есть штатное средство не требующие v8unpack. ( как вариант научить unpack работать с http/tcp хранилищами, но это я не могу сделать т.к. не знаю на столько С(++)) Поэтому доступных штатный механизм 1С-ка - это оскрипт и 1С.

**Comment by nocamad** [comment]
@khorevaa ещё раз повторяю просьба говорить в контексте своих процессов - ваши 90 - наши 0 (при том что мы предоставляем сервис разным командам разработки). Все что я писал выше - не теория (я не теоретик), все что говорю только проверенный работающие вещи. Не понял про что все пытаетесь далее сказать - нашу разработку никому не пиарю, выложил потому что спросили - сам с самого первого поста пишу что в ваших процессах наши разработки не нужны, тк вы все пытаетесь подстроить под свои процессы :), вместо упрощения для стабильной работы стенда. Штатно значит штатно - используя вызовы с результатом штатными командами. Вот нам нужно получить табличку с версиями - берём смотрим как это делает сервер хранилища и вызываем также и кладём результат в ту же табличку (штатно, без парсинга, прозрачно заменяя шаг гитсинка)

**Comment by Khorevaa** [comment]
@nocamad  В контексте моих задач это выглядит так..  около 10 хранилищ (релизных, разные конфигурации), более 100 хранилищ по задачам.  И одна команда разработки. И все это на файловом ресурсе, в хаотичном порядке. Что хочется упорядочить, и автоматизировать (убрать работу программиста 1С-ка) из включения и отключения синхронизации с git.  
Сейчас не можем прейти на  сервер хранилища (http)  т.к. нарушится процессы синхронизации с git. Как то так. В общем я Вашу идею понял. И благодарю что выложили доработки, они будут очень полезны и используемы.  

> Вот нам нужно получить табличку с версиями - берём смотрим как это делает сервер хранилища и вызываем также и кладём результат в ту же табличку (штатно, без парсинга, прозрачно заменяя шаг гитсинка)

У Вас уже это сделано?

**Comment by PiskunovSS** [comment]
@Khorevaa используем сервер хранилища, а разбор на исходники делаем в локальной копии, которую актуализируем через "robocopy "\\repo1C****" "C:\temp\****" /MIR /R:0"
Синхронизация локальной копии проходит довольно быстро, т.к. копируются только измененные файлы.

**Comment by nocamad** [comment]
Неа, только задача на разработку висит, спроектировано

**Comment by khorevaa** [comment]
Решено в версии 3.0.0
